(()=>{'use strict';const C=window.R6_GAME,p=new URLSearchParams(location.search);let en=p.get('lang')==='en',paused=false;const f=document.getElementById('game'),v=(a,b)=>en?b:a;let ready=false;
function show(){document.documentElement.lang=en?'en':'zh-CN';document.title=v(...C.title)+' · R6';document.getElementById('home').textContent='HUB';document.getElementById('home').href=C.hub+'?lang='+(en?'en':'zh-CN');document.getElementById('report').textContent=v('测评','Review');document.getElementById('report').href=C.hub+'review.html?lang='+(en?'en':'zh-CN');document.getElementById('language').textContent=en?'中文':'EN';document.getElementById('pause').textContent=paused?v('继续','Play'):v('暂停','Pause');document.getElementById('full').textContent=v('全屏','Full');document.getElementById('reset').textContent=v('重开','Reset');document.getElementById('curtainText').textContent=v('游戏已暂停','Game paused');document.getElementById('resume').textContent=v('继续游戏','Resume game');document.getElementById('curtain').hidden=!paused;document.getElementById('status').textContent=v('单人 · 本机运行','Solo · on this device');}
function setPause(x){paused=x;f.contentWindow?.postMessage({type:'r6-pause',paused},location.origin);show();}
function load(){ready=false;f.src='game/index.html?lang='+(en?'en':'zh-CN')+'&mode=solo&touch=1&r6=1';show();}
document.getElementById('language').onclick=()=>{if(f.contentWindow?.__R6Game?.canSwitch?.()===false){document.getElementById('status').textContent=v('请先结束当前战斗，再切换语言','Finish the current battle before switching language');return;}f.contentWindow?.postMessage({type:'r6-save'},location.origin);en=!en;history.replaceState(null,'','?lang='+(en?'en':'zh-CN'));setTimeout(load,80);};document.getElementById('pause').onclick=()=>setPause(!paused);document.getElementById('resume').onclick=()=>setPause(false);
document.getElementById('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else throw Error();}catch{document.getElementById('status').textContent=v('可直接玩，无需全屏','Fullscreen is optional');}};
document.getElementById('reset').onclick=()=>{if(!confirm(v('重开这个单机版本？只清除本版本进度，其他版本不受影响。','Restart this solo edition? Only its own progress will be cleared.')))return;try{f.contentWindow.__R6Game=null;for(const k of C.keys||[])localStorage.removeItem(k);}catch{}paused=false;load();};
window.addEventListener('message',e=>{if(e.source!==f.contentWindow||e.origin!==location.origin)return;if(e.data?.type==='r6-ready'){ready=true;setPause(paused);}});document.addEventListener('visibilitychange',()=>{if(document.hidden)setPause(true);});window.addEventListener('pagehide',()=>f.contentWindow?.postMessage({type:'r6-save'},location.origin));
window.__r6Shell={version:'6.0.0',get ready(){return ready;},get paused(){return paused;},setPause};load();})();
