'use strict';
const assert=require('node:assert/strict'),C=require('../web/arranger-core.js');
let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS '+name)};
const fixture=()=>({schema:'classroom-audio-arrangement/1.0',version:'test',title:'Synthetic test',tracks:[{id:'a',gain:.5,pan:0,kind:'sample'},{id:'b',gain:.5,pan:0,kind:'sample'}],samples:[{id:'tone',track:'a',file:'audio/tone.wav',duration:1,midi_note:60}],scenes:[{id:'one',duration:4,stems:[],events:[{id:'e',sample:'tone',track:'a',at:.5,velocity:.8,offset:0,duration:1}]}]});
test('valid project',()=>assert.equal(C.validate(fixture()).scenes.length,1));
test('reject external audio',()=>{const p=fixture();p.samples[0].file='https://example.com/a.wav';assert.throws(()=>C.validate(p))});
test('reject traversal',()=>assert.equal(C.safePath('../secret.wav'),false));
test('reject backslash path',()=>assert.equal(C.safePath('a\\b.wav'),false));
test('reject excess cue tail',()=>{const p=fixture();p.scenes[0].events[0].at=3.5;assert.throws(()=>C.validate(p))});
test('reject wrong sample track',()=>{const p=fixture();p.scenes[0].events[0].track='b';assert.throws(()=>C.validate(p))});
test('reject excessive velocity',()=>{const p=fixture();p.scenes[0].events[0].velocity=1.2;assert.throws(()=>C.validate(p))});
test('reject NaN gain',()=>{const p=fixture();p.tracks[0].gain=NaN;assert.throws(()=>C.validate(p))});
test('solo and mute precedence',()=>{const p=fixture();p.tracks[1].solo=true;assert.equal(C.trackEnabled(p.tracks[0],p.tracks),false);p.tracks[1].mute=true;assert.equal(C.trackEnabled(p.tracks[1],p.tracks),false)});
test('MIDI variable-length encoding',()=>{assert.deepEqual(C.vlq(128),[129,0]);assert.deepEqual(C.vlq(0),[0])});
test('MIDI format and events',()=>{const p=fixture(),b=C.midi(p,p.scenes[0]),v=new DataView(b.buffer);assert.equal(Buffer.from(b.slice(0,4)).toString(),'MThd');assert.equal(v.getUint16(8),0);assert.equal(v.getUint16(12),480);assert.equal(Buffer.from(b.slice(14,18)).toString(),'MTrk');assert.equal(v.getUint32(18),b.length-22);assert(b.includes(144));assert.deepEqual([...b.slice(-4)],[0,255,47,0])});
test('WAV header and peak protection',()=>{const x=new Float32Array([0,1,-1,0]),b={numberOfChannels:1,length:4,sampleRate:48000,getChannelData:()=>x},w=C.wav(b),v=new DataView(w.bytes);assert.equal(w.normalizationGain,.891);assert.equal(v.getUint32(24,true),48000);assert.equal(v.getUint32(40,true),8);assert.equal(w.bytes.byteLength,52)});
test('envelope semantics',()=>{const b={sampleRate:100,getChannelData:()=>new Float32Array(100).fill(.1)},e=C.envelope(b,20);assert.equal(e.frames.length,20);assert.equal(e.frames[0].mouthOpen,.7);assert(e.method.includes('not phoneme'))});
if(process.argv[2])test('private arrangement metadata validates',()=>{const p=JSON.parse(require('node:fs').readFileSync(process.argv[2],'utf8'));C.validate(p);assert.equal(p.samples.length,8);assert.equal(p.scenes.reduce((n,s)=>n+s.events.length,0),68)});
console.log(JSON.stringify({passed:checks,failed:0}));
