// Reads only model usage records. Does not export conversation text or identifiers.
const fs=require('node:fs');
const args=process.argv.slice(2),options={};
while(args[0]?.startsWith('--')){const key=args.shift().slice(2);options[key]=args.shift();}
if(!args.length)throw new Error('Usage: node summarize-usage.cjs --before ISO --since ISO --out file.json session.jsonl [agent.jsonl]');
const fields=['input_tokens','cached_input_tokens','cache_write_input_tokens','output_tokens','reasoning_output_tokens','total_tokens'];
const zero=()=>Object.fromEntries(fields.map(k=>[k,0]));const seen=new Set(),rows=[];
for(const [index,file]of args.entries()){let model='unknown';for(const line of fs.readFileSync(file,'utf8').split('\n')){let e;try{e=JSON.parse(line);}catch{continue;}if(e.type==='turn_context'&&e.payload?.model)model=e.payload.model;if(e.type!=='token_usage_record'||!e.payload?.usage)continue;const key=e.payload.response_id;if(!key||seen.has(key))continue;seen.add(key);if(options.before&&e.timestamp>=options.before)continue;rows.push({role:index===0?'coordinator':'build-agent',model,timestamp:e.timestamp,usage:e.payload.usage});}}
function summarize(list){const totals=zero();let standard=0,unsupported=0,maxInput=0;for(const r of list){for(const f of fields)totals[f]+=Number(r.usage[f]||0);maxInput=Math.max(maxInput,r.usage.input_tokens||0);if(r.model!=='gpt-6-astra'){unsupported++;continue;}const u=r.usage,cache=u.cached_input_tokens||0,writes=u.cache_write_input_tokens||0,plain=Math.max(0,u.input_tokens-cache-writes),long=u.input_tokens>272000;standard+=(plain*10+cache+writes*12.5)*(long?2:1)/1e6+(u.output_tokens||0)*50*(long?1.5:1)/1e6;}return{requests:list.length,totals,uncached_input_tokens:totals.input_tokens-totals.cached_input_tokens-totals.cache_write_input_tokens,max_input_per_request:maxInput,standard_api_reference_usd:Math.round(standard*10000)/10000,unpriced_requests:unsupported};}
const report={schema_version:1,generated_at:new Date().toISOString(),cutoff_exclusive:options.before||null,evolve_since_inclusive:options.since||null,actual_billed_usd:null,actual_billed_status:'Unavailable: local token logs and account-wide limits are not task invoices.',rate_source:'https://developers.openai.com/api/docs/models/gpt-6-astra',reference_rates_usd_per_million:{uncached_input:10,cached_input:1,cache_write_input:12.5,output:50},notes:['Standard API text-token reference only; not actual Codex Pro charges.','Cached input is included in input tokens; reasoning output is included in output tokens. Neither is added twice.','Response identifiers are deduplicated locally and omitted from this report.','Excludes frontend voice, Antigravity, subscription allocation, paid speed modifiers, tools, taxes, and this later archival task.'],all_game_work:summarize(rows),evolve_upgrade:summarize(rows.filter(r=>!options.since||r.timestamp>=options.since)),by_role:Object.fromEntries([...new Set(rows.map(r=>r.role))].map(role=>[role,summarize(rows.filter(r=>r.role===role))]))};
if(options.out)fs.writeFileSync(options.out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
