import {syncViewport,watchViewport} from './viewport.js?v=ipad-hud-1';
const initialViewport=syncViewport();
import './solo.js';
import * as T from './three.module.js';
import {TREES,RINGS,ANIMALS,FIRE,CABIN,move} from './shared.js';
const $=id=>document.getElementById(id),scene=new T.Scene();
scene.background=new T.Color('#bce0e9');scene.fog=new T.Fog('#bce0e9',65,160);
const camera=new T.PerspectiveCamera(48,initialViewport.width/initialViewport.height,.1,230);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('joinStatus').textContent='无法启动 3D，请用支持 WebGL 的 Safari / Chrome 浏览器';throw e;}
renderer.setSize(initialViewport.width,initialViewport.height);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;$('scene').appendChild(renderer.domElement);
scene.add(new T.HemisphereLight('#f2fbff','#94a777',2.5));const sun=new T.DirectionalLight('#fff1cc',3.2);sun.position.set(-30,60,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-60,right:60,top:60,bottom:-60,near:1,far:130});sun.shadow.bias=-.001;scene.add(sun);
const mats=new Map();function mat(c){if(!mats.has(c))mats.set(c,new T.MeshStandardMaterial({color:c,roughness:.8}));return mats.get(c);}
function mesh(g,c,x=0,y=0,z=0,parent=scene){const m=new T.Mesh(g,mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,c,x,y,z,p){return mesh(new T.BoxGeometry(w,h,d),c,x,y,z,p);}
function ball(r,c,x,y,z,p){return mesh(new T.IcosahedronGeometry(r,1),c,x,y,z,p);}
function cyl(rt,rb,h,c,x,y,z,p,n=16){return mesh(new T.CylinderGeometry(rt,rb,h,n),c,x,y,z,p);}
function textSprite(text,color='#355f54',size=4){const cv=document.createElement('canvas');cv.width=768;cv.height=128;const cx=cv.getContext('2d');cx.fillStyle='#fffffff0';cx.beginPath();cx.roundRect(8,8,752,112,35);cx.fill();cx.font='bold 48px Segoe UI, Microsoft Yahei';cx.textAlign='center';cx.textBaseline='middle';cx.fillStyle=color;cx.fillText(text,384,67);const sp=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(cv),depthTest:false}));sp.scale.set(size*3,size*.5,1);return sp;}
function label(text,x,y,z,size=3){const sp=textSprite(text,'#355f54',size);sp.position.set(x,y,z);scene.add(sp);return sp;}
function tree(x,z,kind=0,scale=1){const g=new T.Group();g.position.set(x,0,z);g.scale.setScalar(scale);scene.add(g);cyl(.22,.4,3,'#9a7752',0,1.5,0,g,8);if(kind===1){for(let j=0;j<3;j++)cyl(0,2.4-j*.5,3,'#488b70',0,3+j*1.3,0,g,7);}else{ball(2.2,kind===2?'#e1afbf':'#74af76',0,4,0,g);ball(1.6,kind===2?'#f2c5d4':'#8ac886',1.3,3.6,.2,g);if(kind===3)for(let j=0;j<5;j++)ball(.27,'#f6a34b',Math.cos(j*1.7)*1.6,3.3+Math.sin(j)*.5,Math.sin(j*1.7)*1.5,g);}return g;}
// One connected island: every zone is reachable on foot.
cyl(55,51,5,'#b9a47a',0,-2.6,0,scene,64);cyl(54.8,55,.5,'#94bf83',0,-.15,0,scene,64);
const sea=mesh(new T.PlaneGeometry(800,800),'#8dcbd3',0,-5,0);sea.rotation.x=-Math.PI/2;sea.castShadow=false;
for(let i=0;i<18;i++){const a=i*2.399;const r=85+(i%3)*18;cyl(0,12+i%4,18+i%5*4,['#a4cad0','#acd1cc','#b1d6d5'][i%3],Math.cos(a)*r,-1,Math.sin(a)*r,scene,5);}
const clouds=[];for(let i=0;i<16;i++){const g=new T.Group();g.position.set(Math.cos(i*2.4)*80,25+i%4*3,Math.sin(i*2.4)*80);for(let j=-1;j<=1;j++)ball(3.8-Math.abs(j), '#ffffff',j*3,0,0,g);scene.add(g);clouds.push(g);}
function pathTo(x,z,w=6){const len=Math.hypot(x,z);const m=box(w,.1,len,'#e5d6ae',x/2,.17,z/2);m.rotation.y=Math.atan2(x,z);}
pathTo(-29,-20);pathTo(28,-19);pathTo(0,40);cyl(11,11,.15,'#eee1c0',0,.22,0,scene,48);
for(let i=0;i<12;i++){const a=i*Math.PI/6;box(.25,.14,1.4,'#dbbd87',Math.sin(a)*9,.33,Math.cos(a)*9).rotation.y=a;}
cyl(3.1,3.6,.45,'#d7d6bd',0,.48,-2);cyl(2.8,2.8,.12,'#80d9df',0,.77,-2);cyl(.3,.6,2.5,'#f3d194',0,1.8,-2);const plazaStar=ball(.9,'#ffe2a0',0,3.7,-2);label('✦ 星光大厅 · THE COMMONS',0,6,-3,3.2);
function arch(x,z,color,title){box(.6,5,.7,color,x-3,2.5,z);box(.6,5,.7,color,x+3,2.5,z);box(6.5,.7,.8,color,x,5,z);for(let i=0;i<5;i++)ball(.24,'#ffe9ab',x-2+i,5.7,z);label(title,x,6.7,z,2.6);}
arch(-15,-10,'#b09ad8','01 / 星环乐园');arch(16,-10,'#81a888','02 / 野外营地');arch(0,17,'#dbb57b','03 / 暖阳农场');
// Park: a rotating Ferris wheel, floating star rings, balloons and candy kiosks.
cyl(14,14,.12,'#afadcf',-30,.1,-21,scene,40);
const wheel=new T.Group();wheel.position.set(-35,7,-30);scene.add(wheel);const rim=mesh(new T.TorusGeometry(6,.22,6,40),'#fff2d9',0,0,0,wheel);const baskets=[];for(let i=0;i<8;i++){const a=i*Math.PI/4;const spoke=box(.16,12,.15,'#e9dcb8',0,0,0,wheel);spoke.rotation.z=a;const b=box(1.7,1.3,1.4,['#e997ab','#eec369','#83c9c2','#b497d1'][i%4],Math.sin(a)*6,Math.cos(a)*6,0,wheel);baskets.push(b);}for(const x of[-37,-33]){const leg=box(.45,8,.6,'#f0dcba',x,3.7,-30);leg.rotation.z=x===-37?-.25:.25;}
const rings=RINGS.map((p,i)=>{const g=new T.Group();g.position.set(p.x,3.6,p.z);scene.add(g);const ring=mesh(new T.TorusGeometry(1.5,.18,8,36),'#ffe299',0,0,0,g);const star=ball(.4,'#ffe299',0,0,0,g);cyl(1.8,1.8,.1,'#e2d7ed',p.x,.2,p.z);return{g,ring,star};});
label('飞行 → 靠近星环 → E 互动',-28,7,-17,2.5);
for(let i=0;i<6;i++){const x=-44+i*4,z=-7-i%2*2;cyl(.025,.025,5,'#e7d3b4',x,2.5,z);ball(.8,['#efb5bf','#eacc7e','#92cdd0'][i%3],x,5.4,z);}
for(let i=0;i<3;i++){box(3,2.3,2,'#fbebcf',-19-i*5,1.2,-32);cyl(0,2.4,1.5,['#e2a0b7','#9ca5d5','#7cbcaf'][i],-19-i*5,3,-32,scene,4);}
// Wild grove and a campfire.
cyl(14,14,.1,'#7aab79',29,.1,-20,scene,40);TREES.forEach(t=>tree(t.x,t.z,3,1.15));label('果树 · 摘水果',28,7,-25,2.4);
for(let i=0;i<10;i++){const a=i*Math.PI/5;ball(.4,'#a7aaa0',FIRE.x+Math.cos(a)*1.5,.35,FIRE.z+Math.sin(a)*1.5);}const logs=[];for(let i=0;i<3;i++){const l=box(.4,.4,2.3,'#896744',FIRE.x,.4,FIRE.z);l.rotation.y=i*Math.PI/3;logs.push(l);}const flame=new T.Group();flame.position.set(FIRE.x,.4,FIRE.z);scene.add(flame);cyl(0,.8,2,'#ffb950',0,1,0,flame,5);cyl(0,.4,1.3,'#ffe5a0',0,.6,.3,flame,5);flame.visible=false;
const tent=mesh(new T.ConeGeometry(3,3,4),'#e8be78',36,1.5,-9);tent.rotation.y=Math.PI/4;box(1.6,1.6,.1,'#746c56',36,.8,-6.87);label('营地 · 点燃篝火',28,4,-10,2.2);
for(let i=0;i<10;i++)tree(18+(i%5)*6,-34-Math.floor(i/5)*5,1,.7+i%3*.15);
// Warm farm with three animals and a shared cabin construction site.
box(28,.15,24,'#c6c887',0,.14,33);for(let i=-14;i<=14;i+=4){for(const z of[22,45]){if(z===22&&Math.abs(i)<5)continue;box(.18,1.3,.18,'#f0e5c7',i,.65,z);box(3.8,.16,.13,'#f0e5c7',i+1.7,.9,z);}}
for(const x of[-13,13])for(let z=24;z<43;z+=4){box(.18,1.3,.18,'#f0e5c7',x,.65,z);box(.13,.16,3.8,'#f0e5c7',x,.9,z+1.7);}
for(let i=0;i<12;i++){box(1.2,.15,1,'#aa8660',-10+i%4*1.7,.3,38+Math.floor(i/4)*1.5);ball(.3,'#e5a74f',-10+i%4*1.7,.6,38+Math.floor(i/4)*1.5);}
function animal(t){const g=new T.Group();g.position.set(t.x,0,t.z);scene.add(g);const color=t.type==='cow'?'#faf2d8':t.type==='sheep'?'#fff7df':'#f7d38f';ball(t.type==='chicken'?.7:1.05,color,0,1.2,0,g);ball(.55,color,0,1.65,.85,g);for(const x of[-.5,.5])for(const z of[-.5,.5])box(.2,.8,.2,'#806957',x,.5,z,g);for(const x of[-.22,.22])ball(.065,'#343d3d',x,1.8,1.31,g);if(t.type==='cow'){ball(.4,'#947866',-.6,1.6,-.2,g);box(.18,.4,.2,'#d4ba8b',-.4,2.1,.7,g);box(.18,.4,.2,'#d4ba8b',.4,2.1,.7,g);}if(t.type==='chicken'){ball(.18,'#dd7969',0,2.22,.8,g);box(.25,.18,.3,'#e5983f',0,1.65,1.4,g);}return g;}
const animals=ANIMALS.map(animal);label('喂动物 → 再互动收集农产品',0,5,29,2.7);
const cabin=new T.Group();cabin.position.set(CABIN.x,0,CABIN.z);scene.add(cabin);const foundation=box(7,.4,5,'#c6a77a',0,.25,0,cabin);const walls=box(6,3.8,4,'#ecd3a1',0,2.3,0,cabin);const roof=cyl(0,4.7,2.6,'#9cae95',0,5.4,0,cabin,4);roof.rotation.y=Math.PI/4;const door=box(1.3,2.5,.1,'#8a7157',0,1.7,-2.08,cabin);const win=box(1.1,1.1,.13,'#abd9dd',1.9,2.7,-2.1,cabin);label('我们的家 · 每份农产品建造一步',0,7,43,2.5);
for(let i=0;i<30;i++){const a=i*2.399;const r=43+(i%3)*3;tree(Math.cos(a)*r,Math.sin(a)*r,i%4===0?2:i%3===0?1:0,.65+(i%4)*.12);}
for(let i=0;i<90;i++){const a=i*2.399,r=12+(i*7%37);const x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(x)<4||Math.hypot(x+30,z+20)<15||Math.hypot(x-28,z+20)<15)continue;ball(.14,['#f9dc99','#f1bbc6','#f5eed7'][i%3],x,.28,z);}
const marker=new T.Group();const beacon=cyl(.2,.2,8,'#ffe3a1',0,4,0,marker);beacon.material=new T.MeshBasicMaterial({color:'#ffe3a1',transparent:true,opacity:.35});const markerRing=mesh(new T.TorusGeometry(2.1,.1,6,32),'#ffe1a0',0,.2,0,marker);markerRing.rotation.x=Math.PI/2;scene.add(marker);
const rainGeo=new T.BufferGeometry(),rainPos=new Float32Array(500*3);for(let i=0;i<500;i++){rainPos[i*3]=(Math.random()-.5)*115;rainPos[i*3+1]=Math.random()*30;rainPos[i*3+2]=(Math.random()-.5)*115;}rainGeo.setAttribute('position',new T.BufferAttribute(rainPos,3));const rain=new T.Points(rainGeo,new T.PointsMaterial({color:'#d5edf4',size:.12,transparent:true,opacity:.65}));scene.add(rain);rain.visible=false;
function avatar(skin=0){const g=new T.Group(),colors=['#6f9fcb','#b292c4','#d7a969'];g.userData.skin=skin;const body=box(.85,1,.5,colors[skin],0,1.35,0,g);const head=box(.69,.69,.65,'#f2cfaa',0,2.2,0,g);box(.75,.22,.7,skin===2?'#805c49':'#656b79',0,2.56,0,g);for(const x of[-.16,.16])box(.065,.08,.03,'#374251',x,2.23,.34,g);box(.14,.04,.03,'#bc8273',0,2.04,.34,g);const limbs=[];for(const x of[-.27,.27])limbs.push(box(.3,.75,.34,'#586e7d',x,.49,0,g));for(const x of[-.59,.59])limbs.push(box(.25,.9,.3,colors[skin],x,1.4,0,g));box(.6,.6,.25,'#f2d590',0,1.4,-.4,g);const sh=mesh(new T.CircleGeometry(.65,20),'#537862',0,.03,0,g);sh.rotation.x=-Math.PI/2;sh.material=new T.MeshBasicMaterial({color:'#537862',transparent:true,opacity:.18});g.userData.limbs=limbs;g.userData.body=body;scene.add(g);return g;}
let ws,myId=null,world=null,online=false,started=false,joining=false,chosen=0,yaw=0,lookPitch=.58,muted=false,audio,toastTimer,jumpAt=0,reconnectTimer=null;const actors=new Map(),keys=new Set(),local={x:0,z:6},stick={x:0,z:0};let target={x:-22,z:-19},last=performance.now(),netTime=0,walk=0,currentWeather=0,selectedRoom='';
const params=new URLSearchParams(location.search);$('room').value='SOLO';$('room').closest('label')?.style.setProperty('display','none');
document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{chosen=+b.dataset.skin;document.querySelectorAll('[data-skin]').forEach(x=>x.classList.toggle('selected',x===b));});
function tone(success=false){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();[0,.12,...(success?[.24]:[])].forEach((delay,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=[523,659,784][i];g.gain.setValueAtTime(.06,audio.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+delay+.25);o.connect(g).connect(audio.destination);o.start(audio.currentTime+delay);o.stop(audio.currentTime+delay+.3);});}catch{}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,3800);}
function send(m){if(ws?.readyState===1)ws.send(JSON.stringify(m));}
function action(a){if(!online){toast('正在重新连接，请稍候');return;}send({type:'action',action:a});if(a==='fly')tone();}
function connect(){clearTimeout(reconnectTimer);ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}`);ws.onopen=()=>send({type:'join',room:selectedRoom,name:$('nickname').value||'探险家',skin:chosen});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='welcome'){myId=m.id;online=started=true;joining=false;$('join').classList.add('hidden');$('start').disabled=false;history.replaceState(null,'','?room='+encodeURIComponent(selectedRoom));toast('欢迎来到云间！跟着金色路标，先去星环乐园');}
 if(m.type==='error'){$('joinStatus').textContent=m.text;$('start').disabled=false;joining=false;toast(m.text);ws.close();}
 if(m.type==='teleport'){local.x=m.x;local.z=m.z;resetInput();}
 if(m.type==='notice')toast(m.text);
 if(m.type==='event'){toast(m.text);tone(true);}
 if(m.type==='state'){world=m.world;currentWeather=m.weather;const ids=new Set(m.players.map(p=>p.id));for(const[id,a]of actors){if(!ids.has(id)){scene.remove(a);actors.delete(id);}}
  for(const p of m.players){let a=actors.get(p.id);if(!a){a=avatar(p.skin);a.position.set(p.x,0,p.z);const l=textSprite(p.name,'#355f54',.75);l.position.y=3.2;a.add(l);actors.set(p.id,a);if(p.id===myId){local.x=p.x;local.z=p.z;}}a.userData.net=p;if(a.userData.skin!==p.skin){a.userData.body.material=mat(['#6f9fcb','#b292c4','#d7a969'][p.skin]);a.userData.skin=p.skin;}}
  $('network').textContent='单人 · 本机存档';$('team').replaceChildren(...m.players.map(p=>{const el=document.createElement('div');el.className='teammate';el.textContent=`${['🔵','🟣','🟠'][p.skin]} ${p.name}${p.id===myId?' · 你':''}`;return el;}));updateQuest();}
 };ws.onerror=()=>{$('joinStatus').textContent='连接未成功，正在重试…';};ws.onclose=()=>{online=false;resetInput();$('network').textContent='○ 连接中…';if(started||joining)reconnectTimer=setTimeout(connect,1800);};}
$('start').onclick=()=>{selectedRoom=$('room').value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,16);if(selectedRoom.length<4){$('joinStatus').textContent='房间码至少 4 位字母或数字';return;}joining=true;$('start').disabled=true;$('joinStatus').textContent='正在连接共同的世界…';tone();connect();};
function updateQuest(){if(!world)return;const s=world;let title,desc;let stage=0;const r=s.rings.findIndex(x=>!x);if(r>=0){title=`01 / 飞过星环 · ${s.rings.filter(Boolean).length}/3`;desc='沿金色路标去乐园。按「飞行」，靠近星环，再按「互动」。';target=RINGS[r];}
 else if(s.gathered<3){stage=1;title=`02 / 森林的礼物 · ${s.gathered}/3`;desc='跟着路标来到果树旁，按「互动」摘 3 份水果。';target=TREES[s.gathered%3];}
 else if(!s.fire){stage=2;title='03 / 点亮我们的营地';desc='走到石头围成的篝火旁，按「互动」生火。';target=FIRE;}
 else if(s.eggs.some(x=>!x)){stage=3;const a=s.eggs.findIndex(x=>!x);title=`04 / 照顾小动物 · ${s.eggs.filter(Boolean).length}/3`;if(!s.fed[a]&&!s.fruit){desc='水果用完啦。回果树采一些，再来喂动物。';target=TREES.find((x,i)=>Date.now()-s.picked[i]>8000)||TREES[0];}else{desc=s.fed[a]?'这只动物吃饱了！再按「互动」，领取农产品。':'去农场喂动物，再按一次「互动」收集农产品。';target=ANIMALS[a];}}
 else if(s.cabin<3){stage=4;title=`05 / 建造我们的家 · ${s.cabin}/3`;desc='把农产品带到工地。每按一次「互动」完成一层！';target=CABIN;}
 else if(!s.celebrated){stage=5;title='06 / 回大厅一起庆祝';desc='回星光大厅，在喷泉附近按「互动」。';target={x:0,z:0};}
 else{stage=6;title='✦ 云间探险完成！';desc='小屋属于你们！继续飞行、照顾动物、一起逛小岛吧。';target={x:0,z:0};}
 $('questTitle').textContent=title;$('questText').textContent=desc;$('progressFill').style.width=(stage/6*100)+'%';$('badges').textContent=`${r<0?'★':'☆'} 乐园　 ${s.fire?'★':'☆'} 营地　 ${s.cabin===3?'★':'☆'} 农场`;$('bag').textContent=`🍎 ${s.fruit}　 🧺 ${s.produce}`;
 rings.forEach((o,i)=>{o.g.visible=!s.rings[i];});flame.visible=s.fire;foundation.visible=s.cabin>0;walls.visible=door.visible=win.visible=s.cabin>1;roof.visible=s.cabin>2;animals.forEach((a,i)=>a.scale.setScalar(s.fed[i]?1.08:1));marker.position.set(target.x,0,target.z);rain.visible=currentWeather===2;$('weather').textContent=(window.R6_LANG==='en'?['☀ SUNNY','☁ BREEZY','☂ RAIN']:['☀ 晴朗','☁ 微风','☂ 小雨'])[currentWeather];}
['interact','ability','power','home'].forEach(id=>$(id).onclick=()=>action({interact:'interact',ability:'fly',power:'power',home:'home'}[id]));$('skin').onclick=()=>send({type:'skin'});$('jump').onclick=()=>{jumpAt=performance.now();tone();};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'♫̸':'♫';};$('full').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('此设备不支持网页全屏，横屏游玩更舒适'));};$('invite').onclick=async()=>{const link=location.origin+'/?room='+encodeURIComponent(selectedRoom||$('room').value);try{await navigator.clipboard.writeText(link);toast('邀请链接已复制！发给另外两个伙伴');}catch{toast('伙伴输入相同房间码：'+(selectedRoom||$('room').value));}};
function resetInput(){keys.clear();stick.x=stick.z=0;$('joystick').firstElementChild.style.transform='';send({type:'input',x:0,z:0});}
addEventListener('keydown',e=>{if(!started||/INPUT/.test(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyE')action('interact');if(e.code==='KeyF')action('fly');if(e.code==='KeyQ')action('power');if(e.code==='Space')jumpAt=performance.now();if(e.code==='KeyH')action('home');});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetInput();});
let joyId=null;const joy=$('joystick');joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e);e.preventDefault();};function joyMove(e){if(e.pointerId!==joyId)return;const b=joy.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dz=e.clientY-b.top-b.height/2,n=Math.hypot(dx,dz),k=Math.min(n,42)/(n||1);stick.x=dx*k/42;stick.z=dz*k/42;joy.firstElementChild.style.transform=`translate(${dx*k}px,${dz*k}px)`;}joy.onpointermove=joyMove;function joyUp(e){if(e.pointerId!==joyId)return;joyId=null;resetInput();}joy.onpointerup=joyUp;joy.onpointercancel=joyUp;joy.onlostpointercapture=joyUp;
let drag=null;renderer.domElement.onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;yaw-=(e.clientX-drag.x)*.006;lookPitch=T.MathUtils.clamp(lookPitch+(e.clientY-drag.y)*.004,.25,.95);drag.x=e.clientX;drag.y=e.clientY;};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=()=>drag=null;document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
setInterval(()=>{if(!online)return;const ix=stick.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),iz=stick.z+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);send({type:'input',x:ix*Math.cos(yaw)+iz*Math.sin(yaw),z:-ix*Math.sin(yaw)+iz*Math.cos(yaw)});},70);
watchViewport(({width,height})=>{resetInput();camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height);});
const camTarget=new T.Vector3(),camWant=new T.Vector3(),mc=$('mapCanvas').getContext('2d');
function mapDraw(){mc.clearRect(0,0,180,150);mc.fillStyle='#eaf0dd';mc.beginPath();mc.arc(90,75,66,0,Math.PI*2);mc.fill();mc.lineWidth=10;mc.strokeStyle='#ded7b6';for(const p of[[-30,-20],[28,-20],[0,35]]){mc.beginPath();mc.moveTo(90,75);mc.lineTo(90+p[0]*1.1,75+p[1]*1.1);mc.stroke();}for(const p of[[-30,-20,'#b69ccb'],[28,-20,'#75aa7a'],[0,35,'#dcbf7f']]){mc.fillStyle=p[2];mc.beginPath();mc.arc(90+p[0]*1.1,75+p[1]*1.1,14,0,Math.PI*2);mc.fill();}if(target){mc.fillStyle='#dda43f';mc.beginPath();mc.arc(90+target.x*1.1,75+target.z*1.1,4,0,Math.PI*2);mc.fill();}for(const[id,a]of actors){mc.fillStyle=id===myId?'#244d43':'#f8ffff';mc.strokeStyle='#244d43';mc.lineWidth=1.5;mc.beginPath();mc.arc(90+a.position.x*1.1,75+a.position.z*1.1,3.5,0,Math.PI*2);mc.fill();mc.stroke();}}
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;const t=now/1000;wheel.rotation.z=t*.09;baskets.forEach(b=>b.rotation.z=-wheel.rotation.z);plazaStar.rotation.y=t*.7;plazaStar.position.y=3.7+Math.sin(t)*.15;rings.forEach((o,i)=>{o.star.rotation.y=t;o.g.position.y=3.6+Math.sin(t*2+i)*.2;});animals.forEach((a,i)=>{a.rotation.y=Math.sin(t*.5+i)*.3;a.position.y=Math.sin(t*2+i)*.025;});flame.scale.set(1+Math.sin(t*7)*.08,1+Math.sin(t*11)*.12,1);clouds.forEach((c,i)=>c.position.x+=Math.sin(t*.01+i)*dt*.07);if(rain.visible){for(let i=0;i<500;i++){rainPos[i*3+1]-=dt*17;if(rainPos[i*3+1]<0)rainPos[i*3+1]=28;}rainGeo.attributes.position.needsUpdate=true;}
 let ix=stick.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),iz=stick.z+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const dx=ix*Math.cos(yaw)+iz*Math.sin(yaw),dz=-ix*Math.sin(yaw)+iz*Math.cos(yaw),me=actors.get(myId);if(online&&me){const net=me.userData.net;move(local,dx,dz,dt,net.fly&&net.power===1?12:7);const err=Math.hypot(local.x-net.x,local.z-net.z);if(err>3){local.x=net.x;local.z=net.z;}else if(err>.2){local.x+=(net.x-local.x)*dt*2;local.z+=(net.z-local.z)*dt*2;}me.position.x=local.x;me.position.z=local.z;if(Math.hypot(dx,dz)>.05)me.rotation.y=Math.atan2(dx,dz);netTime+=dt;if(netTime>.05){netTime=0;send({type:'input',x:dx,z:dz});}walk+=dt*Math.min(Math.hypot(dx,dz),1)*11;
 $('ability').innerHTML=['✧ 飞行','ϟ 疾跑','◌ 隐身'][net.power]+' <small>F · 8 秒</small>';
 const d=Math.hypot(local.x-target.x,local.z-target.z);$('waypoint').textContent=(world?.celebrated?'✦ 自由探索':d<4?'✦ 目标就在这里 · 按互动 E':'✦ 跟着金色光柱 · '+Math.round(d)+' m');
 let zone=local.z>18?['SUNNY FARM','暖阳农场']:local.x<-14&&local.z<0?['STARLIGHT PARK','星环乐园']:local.x>14&&local.z<0?['WILD GROVE','野外营地']:['CENTRAL PLAZA','星光大厅'];$('zone').textContent=zone[0];$('zoneName').textContent=zone[1];}
 for(const[id,a]of actors){const p=a.userData.net;if(id!==myId){a.position.x+=(p.x-a.position.x)*Math.min(dt*13,1);a.position.z+=(p.z-a.position.z)*Math.min(dt*13,1);a.rotation.y=p.angle;}let h=p.fly&&p.power===0?3.3:0;if(id===myId&&now-jumpAt<650)h+=Math.sin((now-jumpAt)/650*Math.PI)*1.7;a.position.y+=(h-a.position.y)*Math.min(dt*10,1);a.userData.limbs.forEach((l,i)=>l.rotation.x=Math.sin((id===myId?walk:t*4)+i%2*Math.PI)*.4);a.traverse(o=>{if(o.isMesh)o.visible=!(p.fly&&p.power===2&&Math.floor(t*8)%3===0);});}
 if(started&&me){camTarget.set(me.position.x,me.position.y+1.8,me.position.z);camWant.set(camTarget.x+Math.sin(yaw)*13,camTarget.y+Math.sin(lookPitch)*15,camTarget.z+Math.cos(yaw)*13);camera.position.lerp(camWant,1-Math.exp(-dt*9));camera.lookAt(camTarget);}else{camera.position.set(52+Math.sin(t*.035)*8,43,64);camera.lookAt(-4,0,-6);}
 markerRing.rotation.z=t*.5;marker.visible=started&&!world?.celebrated;mapDraw();renderer.render(scene,camera);}
// Batch static scenery by material to keep tablet draw calls small.
scene.updateMatrixWorld(true);
const dynamic=new Set([wheel,plazaStar,flame,cabin,marker,rain,...clouds,...animals,...rings.map(r=>r.g)]),batches=new Map(),remove=[];
for(const root of [...scene.children]){if(dynamic.has(root))continue;root.traverse(o=>{if(!o.isMesh||Array.isArray(o.material))return;let g=o.geometry.clone();if(g.index)g=g.toNonIndexed();g.applyMatrix4(o.matrixWorld);const key=o.material.uuid;if(!batches.has(key))batches.set(key,{material:o.material,geometries:[]});batches.get(key).geometries.push(g);remove.push(o);});}
for(const o of remove)o.removeFromParent();for(const b of batches.values()){const g=new T.BufferGeometry();for(const name of ['position','normal','uv']){const ar=b.geometries.map(x=>x.getAttribute(name));if(ar.some(x=>!x))continue;const data=new Float32Array(ar.reduce((n,a)=>n+a.array.length,0));let offset=0;for(const a of ar){data.set(a.array,offset);offset+=a.array.length;}g.setAttribute(name,new T.BufferAttribute(data,ar[0].itemSize));}const m=new T.Mesh(g,b.material);m.castShadow=true;m.receiveShadow=true;scene.add(m);for(const geo of b.geometries)geo.dispose();}
foundation.visible=walls.visible=roof.visible=door.visible=win.visible=false;requestAnimationFrame(frame);
window.__skyvale={get state(){return{online,myId,world,players:[...actors.values()].map(a=>({...a.userData.net,x:a.position.x,z:a.position.z})),local:{...local},input:{...stick},drawCalls:renderer.info.render.calls};}};
