const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const deps=process.env.HUB_LIFECYCLE_DEPS||'/tmp/hub-lifecycle/node_modules',{chromium}=require(deps+'/playwright');const R=path.resolve(__dirname,'../..'),O=path.join(R,'shared/hub-r6/lifecycle-qa');fs.mkdirSync(O,{recursive:true});
const live=process.argv.includes('--live'),report={revision:'hub-r6-lifecycle-20260925',mode:live?'live-presentation':'isolated-presentation',started:new Date().toISOString(),checks:[],failures:[],scope:'Lifecycle calculations, evidence-led AI rating presentation, generated Mermaid topology, localization, layout and retained form input. No new gameplay or cloud-service acceptance is claimed.'};let browser,server;
function check(name,v,detail){report.checks.push({name,status:v?'PASS':'FAIL',detail});if(!v)report.failures.push(name+': '+JSON.stringify(detail));}
async function test(){try{
if(!live){server=http.createServer((req,res)=>{try{let u=new URL(req.url,'http://localhost').pathname;if(!u.startsWith('/student-works/'))throw Error('prefix');let p=path.resolve(R,u.slice('/student-works/'.length));if(p!==R&&!p.startsWith(R+path.sep))throw Error('path');if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',({'.html':'text/html;charset=utf-8','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.mmd':'text/plain;charset=utf-8'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.writeHead(404).end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));}
const base=live?'https://sydneygemstone-sudo.github.io/student-works/':`http://127.0.0.1:${server.address().port}/student-works/`;
browser=await chromium.launch({headless:true});const c=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce',acceptDownloads:true});c.setDefaultTimeout(15000);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const allLinks=new Set();
for(const[id,folder]of [['martin','martins-monster-quest'],['trio','adventure-world']]){
 const dir=path.join(R,folder,'hub'),lc=JSON.parse(fs.readFileSync(path.join(dir,'lifecycle.json'))),rv=JSON.parse(fs.readFileSync(path.join(dir,'ai-reviews.json'))),graphs=JSON.parse(fs.readFileSync(path.join(dir,'version-lineage.json')));
 check(id+' phase counts and ordering',lc.phases.map(x=>x.id).join(',')==='mvp,assets,release'&&lc.phases.map(x=>x.completed_gates+'/'+x.total_gates).join(',')==='6/7,0/8,0/6');
 check(id+' phase1 is 85.7%, overall is 28.6%',Math.abs(lc.phases[0].completion_percent-600/7)<1e-6&&Math.abs(lc.overall_percent-200/7)<1e-6);
 check(id+' no arbitrary unequal phase weights',lc.phases.every(x=>Math.abs(x.weight-1/3)<1e-9));
 check(id+' asset scope includes story guide music effects voice', ['a1','a2','a4','a5','a6','a7','a8'].every(k=>lc.phases[1].gates.some(x=>x.id===k)));
 check(id+' AI scoring arithmetic and rationale',rv.reviewer_type==='AI'&&rv.rubric.reduce((s,x)=>s+x.max,0)===100&&rv.reviews.every(x=>x.reviewer_type==='AI'&&x.total===x.points.reduce((s,n)=>s+n,0)&&Math.abs(x.stars-Math.round(x.total/20*10)/10)<1e-6&&x.reasons.length===5&&x.evidence.length>0&&x.risk&&x.next_test));
 for(const g of graphs.graphs){check(id+' '+g.id+' unique typed evidence edges',new Set(g.nodes.map(n=>n.id)).size===g.nodes.length&&g.edges.every(e=>g.nodes.some(n=>n.id===e.source)&&g.nodes.some(n=>n.id===e.target)&&graphs.edge_types[e.type]&&(e.evidence.length||e.type==='future')));for(const lang of ['zh','en']){const svg=fs.readFileSync(path.join(dir,'lineage-'+g.id+'-'+lang+'.svg'),'utf8'),mmd=fs.readFileSync(path.join(dir,'lineage-'+g.id+'-'+lang+'.mmd'),'utf8');check(id+' '+g.id+' '+lang+' Mermaid render',svg.includes('<svg')&&!svg.includes('Syntax error in text')&&g.edges.every(e=>mmd.includes(e.source+' ')));}}
 if(id==='trio'){const g=graphs.graphs[0],has=(a,b,type)=>g.edges.some(e=>e.source===a&&e.target===b&&e.type===type);check('Trio has both divergences and review-only convergence',has('brief','astra','requirements')&&has('brief','opus','requirements')&&has('opusTouch','opusSolo','derive')&&has('opusTouch','cloud1','derive')&&has('astraSolo','review','review')&&has('review','main','select'));check('No invented Astra-to-Opus source merge',!g.edges.some(e=>e.source.toLowerCase().includes('astra')&&(e.target.toLowerCase().includes('opus')||e.target.startsWith('cloud'))));}
 else{const g=graphs.graphs[0];check('Martin independent rebuild is not source inheritance',g.edges.some(e=>e.source==='brief'&&e.target==='v2'&&e.type==='requirements')&&!g.edges.some(e=>e.source==='old'&&e.target==='v2'&&e.type==='derive'));}
 for(const language of ['zh-CN','en'])for(const page of ['index','development','comparison','costs','parents','review']){
  await p.goto(base+folder+'/hub/'+page+'.html?lang='+language+'&lifecycle_verify=1',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__hubLifecycle?.revision==='hub-r6-lifecycle-20260925');
  const state=await p.evaluate(()=>({text:document.getElementById('app').innerText,overflow:document.documentElement.scrollWidth>innerWidth+2,language:document.getElementById('language').textContent,select:document.querySelector('#language')?.tagName,links:[...document.querySelectorAll('a[href],img[src],script[src],link[href]')].map(x=>x.href||x.src)}));state.links.forEach(x=>allLinks.add(x));
  check(id+' '+page+' '+language+' readable and no placeholder scoring',!state.overflow&&!/Awaiting teacher rating|待教师评分|NaN|undefined|Infinity/.test(state.text));
  check(id+' '+page+' '+language+' persistent target language button',state.language===(language==='en'?'中文':'English')&&state.select==='BUTTON');
  if(['index','development'].includes(page)){check(id+' '+page+' three phase bars',await p.locator('.lifecycle-phase').count()===3);check(id+' '+page+' truthful overall',await p.locator('[data-overall]').textContent().then(x=>x==='28.6%'));check(id+' '+page+' two graph sources',(await p.locator('[data-lineage]').count())===2);await p.locator('img[data-lineage]').evaluateAll(xs=>xs.forEach(x=>x.loading='eager'));await p.waitForFunction(()=>[...document.querySelectorAll('img[data-lineage]')].every(x=>x.complete&&x.naturalWidth>0));}
  if(page==='index'){check(id+' metrics retained',await p.locator('.project-dashboard .metric').count()===4);check(id+' current AI rating visible',await p.locator('.ai-featured [data-ai-rating]').count()===1);if(id==='trio'){check('Opus first and multiplayer extension retained',await p.locator('.builds .modelcard').first().getAttribute('id').then(x=>x==='opus-touch'));await p.waitForSelector('#onlineFeature');check('Actual Opus cloud URL retained',await p.locator('.hero .btn.primary').getAttribute('href').then(x=>x.startsWith('https://trio-world-opus.sydney-gemstone-games.workers.dev/')));}}
  if(page==='comparison')check(id+' AI evidence detail for every rated edition',(await p.locator('[data-ai-review]').count())===rv.reviews.length);
  if(language==='zh-CN'&&['index','development','comparison'].includes(page))await p.screenshot({path:path.join(O,(live?'live-':'')+id+'-'+page+'.png'),fullPage:true,animations:'disabled'});
 }
 for(const width of [1024,768,390]){await p.setViewportSize({width,height:900});await p.goto(base+folder+'/hub/index.html?lang=zh-CN&lifecycle_verify=1');await p.waitForFunction(()=>window.__hubLifecycle);check(id+' total page fits '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await p.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));const box=await p.locator('#language').boundingBox();check(id+' language remains on screen after scroll '+width,box&&box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=901);if(width===390)await p.screenshot({path:path.join(O,(live?'live-':'')+id+'-mobile-bottom.png'),animations:'disabled'});}
 await p.setViewportSize({width:1440,height:1000});
}
await p.goto(base+'adventure-world/hub/review.html?lang=zh-CN#retained-draft');await p.waitForFunction(()=>window.__hubLifecycle);await p.selectOption('#reviewer','Joey');await p.fill('#notes','QA unsaved draft: steps, expected, actual');await p.fill('#device','iPad Safari');await p.locator('#language').tap();check('Language switch preserves unsaved feedback and reviewer',await p.inputValue('#notes')==='QA unsaved draft: steps, expected, actual'&&await p.inputValue('#device')==='iPad Safari'&&await p.inputValue('#reviewer')==='Joey');check('Switch preserves current hash',p.url().includes('#retained-draft'));await p.locator('#language').tap();
await p.goto(base+'adventure-world/hub/online-reviews.html?lang=zh-CN');await p.waitForSelector('#language');check('Dynamic room review entry still present',await p.locator('#reviewApp').count()===1&&await p.locator('#language').textContent().then(x=>x==='English'));
const missing=[];if(!live)for(const u of allLinks){if(!u.startsWith(base))continue;let f=path.join(R,new URL(u).pathname.slice('/student-works/'.length));if(!fs.existsSync(f))missing.push(path.relative(R,f));}check('All rendered local evidence/diagram/asset links exist',!missing.length,missing);
check('No new browser runtime exceptions',errors.length===0,errors);await c.close();
}catch(e){report.failures.push(e.stack);console.error(e);}finally{if(browser)await browser.close();if(server){server.closeAllConnections?.();await new Promise(r=>server.close(r));}report.status=report.failures.length?'FAIL':'PASS';report.finished=new Date().toISOString();const target=path.join(O,live?'live-results.json':'results.json');fs.writeFileSync(target,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.failures},null,2));if(report.failures.length)process.exitCode=1;}}
test();
