(function(){'use strict';
const G=window.BeastGame,A=window.BeastArt,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const PROFILE_KEY='beast-kings-evolve-profile',SETTINGS_KEY='beast-kings-evolve-settings';
function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
function makeId(){try{if(globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function')return globalThis.crypto.randomUUID();}catch{}return 'bk-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);}
let profile=G.normalizeProfile(readJSON(PROFILE_KEY,{id:makeId(),name:'Player',character:'frost',energy:180}));
let settings={reduced:true,sound:false,...readJSON(SETTINGS_KEY,{})},mode='duel',arena='moon',tab='lobby';
let state=null,localWorld=null,localMode='practice',networkWanted=false,networkUp=false,ws=null,myId=profile.id,spectator=false,seq=0,retryTimer=null,rtt=0,lastStateAt=0,lastRound='',lastHUD=0,lastFrame=performance.now(),accumulator=0,lastFPS=performance.now(),frames=0,fps=60,toastTimer=null,boostRoundConsumed='';
const taps={},tapKeys=['jump','punch','kick','spin','dash','super','special'];const keys={},pointers=new Map(),keyboard=new Set(),positions=new Map(),seenRewards=new Set(profile.rewardIds),pendingPings=new Map();
const keyMap={KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',Space:'jump',ShiftLeft:'block',ShiftRight:'block',KeyJ:'punch',KeyI:'kick',KeyK:'spin',KeyL:'dash',KeyU:'super',KeyO:'special'};
const R=window.BeastGauntlet,GAUNTLET_KEY='beast-kings-sol-gauntlet-v1';let gauntletRun=null,gauntletHandledRound='',gauntletLastOutcome='';
const gameLang=()=>window.BeastKingsI18n?.get?.()||'zh',tt=(zh,en)=>gameLang()==='zh'?zh:en;
const charText=id=>{const s=G.MoveBook.styles[id]||G.MoveBook.styles.frost,c=G.CHARACTERS[id]||G.CHARACTERS.frost;return{name:c.name,title:gameLang()==='zh'?(s.zhTitle||s.title):s.title,description:gameLang()==='zh'?(s.zhDescription||s.description):s.description};};
const SHOP_ZH={
 attack:['力量增幅器','每级攻击 +8%'],armor:['护盾装甲','每级最大生命 +8，并增加 3% 伤害抗性'],energy:['飞行电容','每级飞行能量 +15'],
 'training-claws':['训练爪','攻击 +1'],'crystal-claws':['水晶爪','攻击 +4'],'nova-gauntlet':['新星拳套','攻击 +7'],
 'light-hide':['轻型兽皮','最大生命 +4'],'crystal-vest':['水晶背心','最大生命 +14，抗性 +4%'],'guardian-shell':['守护甲壳','最大生命 +25，抗性 +8%'],
 'flight-core':['飞行核心','飞行能量 +10'],'wing-booster':['翼能推进器','飞行能量 +30'],'phase-compass':['相位罗盘','飞行能量 +20，Blink 恢复加快 15%']
};

let audioCtx=null,lastSound=0;
function tone(kind){if(!settings.sound||performance.now()-lastSound<95)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),gain=audioCtx.createGain(),t=audioCtx.currentTime;o.type='sine';o.frequency.setValueAtTime(kind==='reward'?620:kind==='dash'?450:150,t);o.frequency.exponentialRampToValueAtTime(kind==='reward'?920:65,t+.13);gain.gain.setValueAtTime(.055,t);gain.gain.exponentialRampToValueAtTime(.001,t+.17);o.connect(gain);gain.connect(audioCtx.destination);o.start(t);o.stop(t+.18);lastSound=performance.now();}catch{}}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200);}
function save(next,announce){const oldTier=profile.evolution;profile=G.normalizeProfile(next);try{localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));$('#saveStatus').textContent=tt('进度已保存在这台设备','Progress saved on this device');}catch{$('#saveStatus').textContent=tt('浏览器存储不可用，请保持页面开启','Storage unavailable — keep this tab open');}renderProfile();if(networkUp&&state?.status==='lobby')send({type:'configure',profile});if(profile.evolution>oldTier){tone('reward');toast(tt('你的 Beast 进化到形态 '+(profile.evolution+1)+'！','Your beast evolved to Form '+(profile.evolution+1)+'!'));}else if(announce)toast(announce);}
function renderProfile(){const c=G.CHARACTERS[profile.character],ct=charText(profile.character),special=G.MoveBook.get(profile.character,'special');$('#gems').textContent=profile.gems;$('#reserve').textContent=profile.energy;$('#baseBalance').textContent=profile.gems+' '+tt('宝石','gems');if(document.activeElement!==$('#playerName'))$('#playerName').value=profile.name;$('#beastName').textContent=c.name;$('#beastSummary').textContent=ct.description;$('#specialLabel').textContent=gameLang()==='zh'?(special.zhLabel||special.label):special.label;$('#evolution').textContent=tt('形态 ','FORM ')+['I','II','III','IV'][profile.evolution];const thresholds=[0,50,140,300],lo=thresholds[profile.evolution],hi=thresholds[profile.evolution+1]||300;$('#xpBar').style.width=(profile.evolution===3?100:Math.min(100,(profile.xp-lo)/(hi-lo)*100))+'%';$('#xpLabel').textContent=profile.xp+' XP'+(profile.evolution<3?(gameLang()==='zh'?' / '+hi+' 进化':' / '+hi+' TO EVOLVE'):(gameLang()==='zh'?' / 最终形态':' / FINAL FORM'));A.portrait($('#portrait'),profile.character,profile.evolution);renderRoster();renderShop();renderMoves();renderBoosts();}
function renderMoves(){const c=G.CHARACTERS[profile.character],ct=charText(profile.character);$('#moveTitle').textContent=ct.title;$('#moveCharacter').textContent=c.name+' · '+tt('技能手册','Move book');const root=$('#moveCards');root.replaceChildren();for(const [key,shortcut]of [['punch','J'],['kick','I'],['spin','K'],['dash','L'],['super','U'],['special','O']]){const m=G.MoveBook.get(profile.character,key),card=document.createElement('article'),title=document.createElement('b'),detail=document.createElement('p'),hint=document.createElement('small');card.className='move-card';title.textContent=gameLang()==='zh'?(m.zhLabel||m.label):m.label;detail.textContent=gameLang()==='zh'?(m.zhDetail||m.detail):m.detail;hint.textContent=shortcut+' · '+m.cooldown+tt('秒冷却','s cooldown')+(m.cost?' · '+m.cost+' '+tt('能量','energy'):'');card.append(title,detail,hint);root.append(card);}}
function changeTab(next){tab=next;for(const id of ['lobby','roster','base','quests'])$('#'+id+'Panel').hidden=id!==next;all('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===next));}
function showHub(){document.body.classList.remove('playing');$('#hub').hidden=false;$('#game').hidden=true;positions.clear();changeTab(tab);renderProfile();}
function showGame(){document.body.classList.add('playing');$('#hub').hidden=true;$('#game').hidden=false;}
function renderRoster(){const root=$('#rosterCards');root.replaceChildren();for(const c of Object.values(G.CHARACTERS)){const ct=charText(c.id),specialMove=G.MoveBook.get(c.id,'special'),card=document.createElement('article');card.className='beast-card'+(profile.character===c.id?' selected':'');const cv=document.createElement('canvas');cv.width=400;cv.height=250;cv.setAttribute('aria-label',c.name+' character portrait');card.append(cv);const title=document.createElement('h3');title.textContent=c.name;card.append(title);const role=document.createElement('small');role.className='beast-role';role.textContent=ct.title;card.append(role);const p=document.createElement('p');p.textContent=ct.description;card.append(p);const special=document.createElement('div');special.className='special-note';special.textContent='◇ '+(gameLang()==='zh'?(specialMove.zhLabel||specialMove.label):specialMove.label);card.append(special);const b=document.createElement('button');b.dataset.character=c.id;b.textContent=profile.character===c.id?tt('已选择 ✓','Selected ✓'):tt('选择 ','Choose ')+c.name;b.onclick=()=>{save({...profile,character:c.id},tt('已选择 ','Selected ')+c.name);};card.append(b);root.append(card);A.portrait(cv,c.id,profile.evolution);}}
function shopCard(title,description,icon){const card=document.createElement('article');card.className='shop-card';const i=document.createElement('div');i.className='shop-icon';i.textContent=icon;const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=description;card.append(i,h,p);return card;}
function renderShop(){const root=$('#upgradeCards');root.replaceChildren();for(const u of Object.values(G.UPGRADES)){const level=profile.upgrades[u.id]||0,cost=u.costs[level],z=SHOP_ZH[u.id],card=shopCard(gameLang()==='zh'?(z?.[0]||u.name):u.name,gameLang()==='zh'?(z?.[1]||u.description):u.description,{attack:'✦',armor:'◒',energy:'ϟ'}[u.id]);const bars=document.createElement('div');bars.className='levels';for(let n=0;n<3;n++){const i=document.createElement('i');if(n<level)i.className='filled';bars.append(i);}card.append(bars);const b=document.createElement('button');b.dataset.upgrade=u.id;b.textContent=level>=u.maxLevel?'Maximum level ✓':'Level '+(level+1)+' · ◆ '+cost;b.disabled=level>=u.maxLevel||profile.gems<cost;b.onclick=()=>{const result=G.buyUpgrade(profile,u.id);if(result.ok)save(result.profile,u.name+' upgraded');else toast(result.error);};card.append(b);root.append(card);}
const equipment=$('#equipmentCards');equipment.replaceChildren();for(const e of Object.values(G.EQUIPMENT)){const own=profile.ownedEquipment.includes(e.id),equipped=profile.equipment[e.slot]===e.id,z=SHOP_ZH[e.id],card=shopCard(gameLang()==='zh'?(z?.[0]||e.name):e.name,gameLang()==='zh'?(z?.[1]||e.description):e.description,{weapon:'⚔',armor:'◈',tool:'⚙'}[e.slot]);const b=document.createElement('button');b.dataset.equipment=e.id;b.disabled=equipped||(!own&&profile.gems<e.cost);b.textContent=equipped?'Equipped ✓':own?'Equip':'Buy · ◆ '+e.cost;b.onclick=()=>{const result=own?G.equipItem(profile,e.id):G.buyEquipment(profile,e.id);if(result.ok)save(result.profile,e.name+' equipped');else toast(result.error);};card.append(b);equipment.append(card);}}
const BOOSTS={rush:{name:'Rush',zh:'疾冲',cost:60},guard:{name:'Guard',zh:'守护',cost:60},surge:{name:'Surge',zh:'爆发',cost:60}};
function renderBoosts(){const status=$('#boostStatus');if(!status)return;const boost=profile.boost?BOOSTS[profile.boost]:null;status.textContent=boost?(gameLang()==='zh'?boost.zh:boost.name)+tt(' 已装配到下一局。',' armed for the next round.'):(tt('未装配强化 · 当前 ','No boost armed · ')+profile.energy+tt(' Energy 可用。',' Energy available.'));all('[data-boost]').forEach(b=>{const selected=b.dataset.boost===profile.boost;b.classList.toggle('selected',selected);b.disabled=!profile.boost&&profile.energy<BOOSTS[b.dataset.boost].cost;b.setAttribute('aria-pressed',selected?'true':'false');});}
function armBoost(id){const boost=BOOSTS[id];if(!boost)return;const name=gameLang()==='zh'?boost.zh:boost.name;if(profile.boost===id){toast(tt('已经装配：','Already armed: ')+name);return;}const cost=profile.boost?0:boost.cost;if(profile.energy<cost){toast(tt('需要 ','Need ')+cost+' Energy '+tt('才能装配这个强化。','to arm this boost.'));return;}save({...profile,energy:profile.energy-cost,boost:id},name+tt(' 已装配到下一局',' armed for the next round'));}
function consumeArmedBoost(roundId){if(!profile.boost||boostRoundConsumed===roundId)return;const name=BOOSTS[profile.boost]?.name||'Boost';boostRoundConsumed=roundId;save({...profile,boost:''},name+' is active for this round');}
function renderArenas(){const root=$('#arenaChoices');root.replaceChildren();for(const a of Object.values(G.ARENAS)){const b=document.createElement('button');b.className='arena-option'+(a.id===arena?' selected':'');b.dataset.arena=a.id;b.textContent=a.name;b.onclick=()=>{arena=a.id;renderArenas();if(networkUp)send({type:'configure',arena,mode,profile});};root.append(b);}}
function send(msg){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(msg));}
function sendInput(){if(!networkUp||spectator)return;send({type:'input',seq:++seq,input:document.hidden?{}:{...keys}});}
function release(){for(const k of tapKeys)delete taps[k];pointers.clear();keyboard.clear();for(const k of G.INPUT_KEYS)keys[k]=false;all('[data-key].held').forEach(b=>b.classList.remove('held'));sendInput();}
function rebuild(){const previous={...keys};for(const k of G.INPUT_KEYS)keys[k]=false;for(const k of pointers.values())keys[k]=true;for(const k of keyboard)keys[k]=true;for(const k of tapKeys)if(keys[k]&&!previous[k])taps[k]=true;all('[data-key]').forEach(b=>b.classList.toggle('held',!!keys[b.dataset.key]));sendInput();}
all('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.key);rebuild();if(!['left','right','up','down','block','jump'].includes(b.dataset.key))tone(b.dataset.key);});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>{pointers.delete(e.pointerId);rebuild();});});
const gameSurface=$('#game');let lastTouchEnd=0;gameSurface.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<320)e.preventDefault();lastTouchEnd=now;},{passive:false});gameSurface.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});gameSurface.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)||$('#game').hidden)return;const k=keyMap[e.code];if(k){e.preventDefault();keyboard.add(k);rebuild();}});window.addEventListener('keyup',e=>{const k=keyMap[e.code];if(k){e.preventDefault();keyboard.delete(k);rebuild();}});
window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden){release();if(state?.status==='playing')pause();}});window.addEventListener('pagehide',()=>{release();if(ws)ws.close();});
function leaveNetwork(){networkWanted=false;networkUp=false;clearTimeout(retryTimer);retryTimer=null;const old=ws;ws=null;if(old)old.close();spectator=false;$('#joinOnline').hidden=false;$('#roomInfo').hidden=true;$('#networkStatus').textContent='Ready when you are';}
function joinNetwork(){if(location.hostname.endsWith('.github.io')){toast('For multiplayer, open the game link shared by your host. Practice and quests work here.');return;}if(ws&&[WebSocket.CONNECTING,WebSocket.OPEN].includes(ws.readyState))return;release();localWorld=null;state=null;networkWanted=true;$('#joinOnline').disabled=true;$('#networkStatus').textContent='Connecting through Tailscale…';const socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);ws=socket;socket.onopen=()=>send({type:'hello',profile});socket.onmessage=event=>{if(ws!==socket)return;let msg;try{msg=JSON.parse(event.data);}catch{return;}if(msg.type==='welcome'){myId=msg.id||profile.id;spectator=!!msg.spectator;networkUp=true;seq=0;$('#joinOnline').hidden=true;$('#joinOnline').disabled=false;$('#roomInfo').hidden=false;if(!spectator)send({type:'configure',profile,mode,arena});}else if(msg.type==='state'){const incoming=msg.state;const changedRound=lastRound!==incoming.roundId;state=incoming;lastStateAt=performance.now();if(changedRound){positions.clear();lastRound=incoming.roundId;release();}if(state.status==='playing')consumeArmedBoost(state.roundId);arena=state.arena;mode=state.mode;if(state.status==='lobby')renderRoom();if(state.status==='lobby'){if(!$('#game').hidden)showHub();}else showGame();handleRewards();if(changedRound)updateHUD();}else if(msg.type==='error'){toast(msg.message||'Unable to join this room');if(msg.message&&/already|duplicate/i.test(msg.message)){networkWanted=false;$('#joinOnline').disabled=false;}}else if(msg.type==='pong'){const sent=pendingPings.get(msg.t);if(sent){rtt=performance.now()-sent;pendingPings.delete(msg.t);}}};socket.onclose=()=>{if(ws!==socket)return;ws=null;networkUp=false;release();$('#joinOnline').disabled=false;$('#networkStatus').textContent='Connection lost. Keep Tailscale connected; retrying…';if(state&&state.status==='playing'){state={...state,status:'paused',reason:'Connection paused. Reconnecting to the host…'};updateHUD();}if(networkWanted)retryTimer=setTimeout(joinNetwork,1500);};socket.onerror=()=>{};}
function renderRoom(){const slots=state?.slots||[],connected=slots.filter(s=>s?.connected);const signature=JSON.stringify([slots,mode,arena,spectator,Math.round(rtt/25)]);if(signature===roomSignature)return;roomSignature=signature;$('#networkStatus').textContent=spectator?'Spectating — three player slots are occupied':connected.length+' / 3 players connected'+(rtt?' · '+Math.round(rtt)+' ms':'');$('#roomPlayers').replaceChildren();for(const s of slots.filter(Boolean)){const row=document.createElement('div');row.textContent=(s.connected?'● ':'○ ')+s.name+' · '+(G.CHARACTERS[s.character]?.name||s.character);$('#roomPlayers').append(row);}$('#startOnline').disabled=connected.length<2||spectator;all('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));renderArenas();}
function handleRewards(){if(!state)return;for(const reward of state.rewards||[]){if(reward.playerId!==myId||seenRewards.has(reward.id))continue;const result=G.grantReward(profile,reward);if(result.ok){seenRewards.add(reward.id);save(result.profile);tone('reward');}}}
function persistGauntlet(){try{localStorage.setItem(GAUNTLET_KEY,JSON.stringify(gauntletRun))}catch{}}
function gauntletStageLabel(){if(!gauntletRun)return'';return R.isFinalStage(gauntletRun)?tt('最终战 · BEAST KING','FINAL · BEAST KING'):tt('第 ','STAGE ')+(gauntletRun.stage+1)+' / '+(R.ORDER.length+1);}
function updateGauntletProgress(){const el=$('#gauntletProgress');if(!el)return;el.hidden=!gauntletRun;if(gauntletRun)el.textContent='♛ '+gauntletStageLabel();}
function startGauntlet(){release();leaveNetwork();gauntletRun=R.createRun(profile.id,profile.character);gauntletHandledRound='';gauntletLastOutcome='';persistGauntlet();startGauntletStage();}
function startGauntletStage(){if(!gauntletRun)return;release();leaveNetwork();localMode='gauntlet';myId=profile.id;const human={id:profile.id,name:profile.name,character:profile.character,profile};if(R.isFinalStage(gauntletRun)){localWorld=G.createGame({mode:'boss',arena,players:[human]});const boss=localWorld.players.find(p=>p.boss);R.tuneFinalBoss(boss);}else{const enemyId=R.nextOpponent(gauntletRun),enemyName=G.CHARACTERS[enemyId]?.name||enemyId;localWorld=G.createGame({mode:'duel',arena,players:[human,{id:'gauntlet-'+gauntletRun.stage,name:enemyName,character:enemyId,ai:true,profile:{id:'gauntlet-'+gauntletRun.stage,character:enemyId,xp:gauntletRun.stage>=5?140:gauntletRun.stage>=2?50:0}}]});const enemy=localWorld.players[1];enemy.maxHp+=gauntletRun.stage*12;enemy.hp=enemy.maxHp;enemy.attackMultiplier*=1+gauntletRun.stage*.04;enemy.sessionSpeed=(enemy.sessionSpeed||1)*(1+gauntletRun.stage*.018);}const me=localWorld.players.find(p=>p.id===myId);R.applyToPlayer(me,gauntletRun);localWorld.status='playing';state=localWorld;lastRound=state.roundId;gauntletHandledRound='';positions.clear();accumulator=0;$('#gauntletOverlay').hidden=true;$('#gameOverlay').hidden=true;showGame();updateGauntletProgress();updateHUD();tone('reward');}
function showGauntletChoices(){const picks=R.choicesForStage(gauntletRun.stage),root=$('#gauntletChoices');root.replaceChildren();$('#gauntletEyebrow').textContent=tt('击败守护兽 · 三选一强化','GUARDIAN DEFEATED · CHOOSE ONE');$('#gauntletTitle').textContent=tt('选择一项永久强化，继续本次车轮战','Choose one upgrade for the rest of this run');$('#gauntletText').textContent=tt('你已经赢下第 '+(gauntletRun.stage+1)+' 场。下一位敌人会更强。','You cleared stage '+(gauntletRun.stage+1)+'. The next opponent will be stronger.');for(const id of picks){const u=R.UPGRADES[id],b=document.createElement('button');b.className='gauntlet-choice';const icon=document.createElement('span');icon.className='choice-icon';icon.textContent=u.icon;const name=document.createElement('b');name.textContent=gameLang()==='zh'?u.zh:u.name;const detail=document.createElement('small');detail.textContent=gameLang()==='zh'?u.zhDetail:u.detail;b.append(icon,name,detail);b.onclick=()=>{gauntletRun=R.applyChoice(gauntletRun,id);persistGauntlet();$('#gauntletOverlay').hidden=true;startGauntletStage();};root.append(b);}$('#gauntletRestart').hidden=true;$('#gauntletContinue').hidden=true;$('#gauntletCertificate').hidden=true;$('#gauntletOverlay').hidden=false;}
function showGauntletDefeat(){gauntletLastOutcome='defeat';$('#gauntletEyebrow').textContent=tt('车轮战结束','RUN ENDED');$('#gauntletTitle').textContent=tt('这次倒在 '+gauntletStageLabel(),'Defeated at '+gauntletStageLabel());$('#gauntletText').textContent=tt('你保留常规游戏进度，但本次 Roguelike 强化到此结束。换 Beast 或换打法再来一次。','Your normal game progress is safe, but the roguelike upgrades end with this run. Try another beast or strategy.');$('#gauntletChoices').replaceChildren();$('#gauntletRestart').hidden=false;$('#gauntletCertificate').hidden=true;$('#gauntletContinue').hidden=true;$('#gauntletOverlay').hidden=false;}
function showGauntletVictory(){gauntletRun=R.complete(gauntletRun);persistGauntlet();gauntletLastOutcome='victory';$('#gauntletEyebrow').textContent='HALL OF LEGENDS';$('#gauntletTitle').textContent=tt('你就是 BEAST KING！','YOU ARE THE BEAST KING!');$('#gauntletText').textContent=tt(profile.name+' 以 '+G.CHARACTERS[profile.character].name+' 完成七连战，并单人击败原本按合作强度设计的最终王者。',profile.name+' cleared all seven guardians with '+G.CHARACTERS[profile.character].name+' and soloed the final king tuned at co-op-level strength.');$('#gauntletChoices').replaceChildren();$('#gauntletRestart').hidden=false;$('#gauntletCertificate').hidden=false;$('#gauntletContinue').hidden=true;$('#gauntletOverlay').hidden=false;tone('reward');}
function checkGauntletOutcome(){if(!gauntletRun||!state||state.status!=='ended'||gauntletHandledRound===state.roundId)return;gauntletHandledRound=state.roundId;const final=R.isFinalStage(gauntletRun),won=final?state.winnerId==='heroes':state.winnerId===myId;if(!won){showGauntletDefeat();return;}if(final)showGauntletVictory();else showGauntletChoices();}
function showCertificate(){const dialog=$('#certificateDialog');$('#certificateName').textContent=profile.name||'Player';$('#certificateBeast').textContent=G.CHARACTERS[profile.character]?.name||profile.character;$('#certificateId').textContent=profile.id;$('#certificateDate').textContent=new Date(gauntletRun?.completedAt||Date.now()).toLocaleDateString();if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');}
function certificateCanvas(){const cv=document.createElement('canvas');cv.width=1600;cv.height=1100;const c=cv.getContext('2d'),gold='#d6ad58',ink='#f8efd5';const g=c.createLinearGradient(0,0,1600,1100);g.addColorStop(0,'#102834');g.addColorStop(1,'#07131d');c.fillStyle=g;c.fillRect(0,0,1600,1100);c.strokeStyle=gold;c.lineWidth=12;c.strokeRect(46,46,1508,1008);c.strokeStyle='#7d6530';c.lineWidth=3;c.strokeRect(70,70,1460,960);c.textAlign='center';c.fillStyle='#9bcfc8';c.font='600 28px Arial';c.fillText('BEAST KINGS · HALL OF LEGENDS',800,145);c.fillStyle=gold;c.font='120px Georgia';c.fillText('♛',800,285);c.fillStyle=gold;c.font='bold 66px Arial';c.fillText('BEAST KING CERTIFICATE',800,380);c.fillStyle='#b7c6c4';c.font='30px Arial';c.fillText(tt('谨此表彰 / This certifies that','This certifies that / 谨此表彰'),800,445);c.fillStyle=ink;c.font='bold 72px Arial';c.fillText((profile.name||'Player').slice(0,28),800,545);const temp=document.createElement('canvas');temp.width=360;temp.height=270;A.portrait(temp,profile.character,profile.evolution);c.drawImage(temp,620,565,360,270);c.fillStyle='#dce7e4';c.font='32px Arial';c.fillText((G.CHARACTERS[profile.character]?.name||profile.character)+' · Game ID '+profile.id,800,875);c.fillStyle='#b7c6c4';c.font='26px Arial';c.fillText(tt('连续击败七位守护兽，并单人战胜最终 Beast King','Defeated all seven guardians and soloed the final Beast King'),800,930);c.fillStyle=gold;c.font='bold 34px Arial';c.fillText(new Date(gauntletRun?.completedAt||Date.now()).toLocaleDateString(),800,995);return cv;}
function downloadCertificate(){const cv=certificateCanvas();cv.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='beast-king-'+String(profile.name||profile.id).replace(/[^a-z0-9_-]+/gi,'-')+'.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);},'image/png');}
async function toggleFullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return;}const el=document.documentElement;if(el.requestFullscreen){await el.requestFullscreen({navigationUI:'hide'});return;}if(el.webkitRequestFullscreen){el.webkitRequestFullscreen();return;}}catch{}document.body.classList.toggle('pseudo-fullscreen');window.scrollTo(0,1);toast(document.body.classList.contains('pseudo-fullscreen')?tt('已进入网页全屏布局；iPad 仍可用“添加到主屏幕”获得更完整全屏。','Fullscreen layout enabled. On iPad, Add to Home Screen gives the cleanest full-screen view.'):tt('已退出全屏布局','Fullscreen layout closed'));}
function startLocal(nextMode){release();leaveNetwork();localMode=nextMode;myId=profile.id;localWorld=G.createGame({mode:nextMode,arena,players:[{id:profile.id,name:profile.name,character:profile.character,profile}]});localWorld.status='playing';state=localWorld;lastRound=state.roundId;positions.clear();accumulator=0;consumeArmedBoost(state.roundId);showGame();updateHUD();}
function returnLobby(){release();if(networkWanted)leaveNetwork();gauntletRun=null;gauntletHandledRound='';gauntletLastOutcome='';$('#gauntletOverlay').hidden=true;$('#gauntletProgress').hidden=true;localWorld=null;state=null;showHub();changeTab('lobby');}
function pause(){release();if(localWorld){localWorld.status='paused';localWorld.reason=tt('已暂停。准备好以后继续。','Paused. Take your time.');updateHUD();}else send({type:'control',action:'pause'});}
function resume(){release();if(localWorld){localWorld.status='playing';accumulator=0;updateHUD();}else if(networkUp)send({type:'control',action:'resume'});else toast('Reconnect to the host before resuming.');}
function replay(){release();if(localWorld)startLocal(localMode);else send({type:'control',action:'reset'});}
function applyGameLanguage(){
 const set=(sel,zh,en)=>{const el=$(sel);if(el)el.textContent=tt(zh,en)},html=(sel,zh,en)=>{const el=$(sel);if(el)el.innerHTML=tt(zh,en)};
 document.title=tt('Beast Kings · GPT-5.6 Sol 强化版','Beast Kings · GPT-5.6 Sol Enhanced');
 set('.profile label','玩家名称','YOUR NAME');$('#playerName').placeholder=tt('你的名字 / 游戏名','Your name / game name');
 set('[data-tab="lobby"]','⌂ 大厅','⌂ Lobby');set('[data-tab="roster"]','◇ Beast','◇ Beasts');set('[data-tab="base"]','⚒ 技术基地','⚒ Tech base');set('[data-tab="quests"]','◎ 任务','◎ Quests');
 set('.hero-heading .eyebrow','你的守护兽','YOUR GUARDIAN');set('#changeBeast','更换 ↗','Change ↗');
 set('.join-card .eyebrow','一起玩','PLAY TOGETHER');html('.join-card h2','更大的竞技场。<br>对战，或者合作。','Big arena.<br>Fight or team up.');set('.join-card>p:not(.eyebrow)','通过主机加入。现在可以左右、前后在 2.5D 场地中移动。','Join through the host. Move left, right, forward and back in the 2.5D arena.');
 html('[data-mode="duel"]','⚔ 对战<small>最后存活的 Beast 获胜</small>','⚔ Battle<small>Last beast standing</small>');html('[data-mode="boss"]','🐉 Boss 战<small>组队挑战 Apex Fluffy</small>','🐉 Boss Fight<small>Team vs Apex Fluffy</small>');html('[data-mode="crown"]','♛ 王冠冲刺<small>快速目标小游戏</small>','♛ Crown Dash<small>Fast target mini-game</small>');
 html('#joinOnline',tt('加入共享竞技场 <span>→</span>','Join the shared arena <span>→</span>'),tt('加入共享竞技场 <span>→</span>','Join the shared arena <span>→</span>'));set('#startOnline','一起开始 →','Start together →');set('#leaveOnline','离开房间','Leave room');
 set('.boost-station .eyebrow','使用储存 Energy','SPEND STORED ENERGY');set('.boost-station h3','为下一局装配一个临时强化','Arm one boost for your next round');
 html('[data-boost="rush"]','↗ 疾冲<small>移动速度 +18%</small>','↗ Rush<small>18% faster movement</small>');html('[data-boost="guard"]','◇ 守护<small>开局生命 +30</small>','◇ Guard<small>+30 starting HP</small>');html('[data-boost="surge"]','✦ 爆发<small>冷却更快 + 输出增强</small>','✦ Surge<small>Faster cooldowns + power</small>');
 set('.arena-choice .eyebrow','选择场景','SET THE SCENE');set('.arena-choice h3','选择战斗场地','Choose your battleground');
 set('#rosterPanel .section-title .eyebrow','找到你的打法','FIND YOUR PLAY STYLE');set('#rosterPanel .section-title h2','七位守护兽，也包括你们的使魔。','Seven guardians. Your familiars, too.');set('#rosterPanel .section-title .pill','全部 Beast 可用','ALL BEASTS AVAILABLE');
 set('#basePanel .section-title .eyebrow','建立你的优势','BUILD YOUR ADVANTAGE');set('#basePanel .section-title h2','技术基地','The technology base');set('#basePanel .section-title p:not(.eyebrow)','用实战获得的宝石购买永久升级和装备。这里没有真钱消费。','Spend earned gems on upgrades and equipment. Nothing here costs real money.');set('#basePanel>h3','永久升级','Permanent upgrades');set('#basePanel .section-gap','武器、护甲与工具','Weapons, armor & tools');
 set('#questsPanel .section-title .eyebrow','通过游玩获得成长','EARN BY PLAYING');set('#questsPanel .section-title h2','下一项任务','Your next mission');set('#questsPanel .section-title p:not(.eyebrow)','完成任务或练习挑战，获得宝石、XP 和储存 Energy。','Finish a quest or practice challenge to earn gems, XP, and stored energy.');
 const quests=all('.quest-card');if(quests[0]){set('#questsPanel .quest-card:first-child .quest-number','01 / 练习','01 / PRACTICE');set('#questsPanel .quest-card:first-child h2','目标训练师','Target technician');set('#questsPanel .quest-card:first-child p','击破五个训练目标，在安全场地实验你的技能。','Defeat five training targets. Experiment with your powers in a safe arena.');set('#questPractice','训练并获得奖励 →','Train and earn →');}if(quests[1]){set('#questsPanel .sentinel .quest-number','02 / 单人任务','02 / SOLO QUEST');set('#questsPanel .sentinel h2','守卫试炼','The sentinel trial');set('#questsPanel .sentinel p','与 AI 守卫打一整局。持续移动、格挡并使用特殊技能。','Face an AI guardian in one complete round. Keep moving, block, and use your special.');set('#questBattle','进入试炼 →','Enter the trial →');}
 set('#settings .section-title h2','游戏设置','Your play settings');const rows=all('#settings .setting-row');if(rows[0]){rows[0].querySelector('b').textContent=tt('减少特效','Reduced effects');rows[0].querySelector('small').textContent=tt('优先流畅度：减少粒子，不使用屏幕震动。','Smoother play, fewer particles, no screen shake.')}if(rows[1]){rows[1].querySelector('b').textContent=tt('音效','Sound effects');rows[1].querySelector('small').textContent=tt('为技能和结果播放轻量音效。','Quiet sounds for moves and results.')}
 const footer=$('footer');if(footer)footer.innerHTML=tt('NATHAN + LEO 共同创作 <span>探索 · 练习 · 进化</span>','CREATED WITH NATHAN + LEO <span>Explore. Practise. Evolve.</span>');
 renderProfile();if(state)updateHUD();updateGauntletProgress();
}
window.addEventListener('bk-language',applyGameLanguage);

let roomSignature='';
let hudSignature='';function updateHUD(){if(!state)return;const title=gauntletRun?tt('BEAST KING 车轮战','BEAST KING GAUNTLET'):state.mode==='practice'?tt('练习场','PRACTICE RANGE'):state.mode==='quest'?tt('守卫试炼','SENTINEL TRIAL'):state.mode==='boss'?tt('APEX BOSS 战','APEX BOSS FIGHT'):state.mode==='crown'?tt('王冠冲刺 · 小游戏','CROWN DASH · MINI-GAME'):state.players.filter(p=>!p.ai).length===3?tt('三兽乱斗','THREE-BEAST FREE-FOR-ALL'):tt('BEAST 对战','BEAST BATTLE');$('#gameMode').textContent=title;$('#gameNetwork').textContent=gauntletRun?tt('单机 · 连战升级','SOLO · ROGUELIKE RUN'):localWorld?tt('单机 · 游玩获得成长','SOLO · EARN BY PLAYING'):(networkUp?'TAILSCALE · SHARED ARENA':tt('重新连接中','RECONNECTING'));const root=$('#healthBars'),sig=state.players.map(p=>p.id+':'+p.character).join('|');if(sig!==hudSignature){hudSignature=sig;root.replaceChildren();for(const p of state.players){const card=document.createElement('div');card.className='health-card';card.dataset.player=p.id;const name=document.createElement('div');name.className='health-name';name.append(document.createElement('span'),document.createElement('b'));const track=document.createElement('div');track.className='health-track';track.append(document.createElement('i'));const detail=document.createElement('div');detail.className='health-detail';card.append(name,track,detail);root.append(card);}}
for(const [i,p] of state.players.entries()){const card=root.children[i];card.querySelector('.health-name span').textContent=p.name+(p.id===myId?' · YOU':'');card.querySelector('.health-name b').textContent=Math.ceil(p.hp)+' HP';card.querySelector('.health-track i').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';card.querySelector('.health-track i').style.background=G.CHARACTERS[p.character]?.color||'#fff';card.querySelector('.health-detail').textContent=(p.boss?(tt('BOSS 阶段 ','BOSS PHASE ')+(p.bossPhase||1)+' · '):'')+(G.CHARACTERS[p.character]?.name||p.character)+' · '+tt('形态 ','FORM ')+((p.evolution||0)+1)+(['practice','crown'].includes(state.mode)?' · '+p.charges+'/5 '+tt('目标','TARGETS'):'');}
const me=state.players.find(p=>p.id===myId)||state.players[0];if(me){$('#flightEnergy').style.width=(me.energy/me.maxEnergy*100)+'%';$('#flightValue').textContent=Math.round(me.energy)+' / '+me.maxEnergy;all('.actions [data-key]').forEach(b=>{const move=G.MoveBook.get(me.character,b.dataset.key),cd=me.cd[b.dataset.key]||0,label=gameLang()==='zh'?(move.zhLabel||move.label):move.label,detail=gameLang()==='zh'?(move.zhDetail||move.detail):move.detail;b.querySelector('span').textContent=label;b.title=detail;b.setAttribute('aria-label',label+': '+detail);b.classList.toggle('cooling',cd>.08);b.style.setProperty('--cooldown',Math.min(100,cd/move.cooldown*100)+'%');b.querySelector('em').textContent=cd>.08?cd.toFixed(1):'';});}
const paused=state.status==='paused',ended=state.status==='ended';$('#gameOverlay').hidden=gauntletRun&&ended?true:!paused&&!ended;$('#pause').disabled=state.status!=='playing';$('#resume').hidden=!paused;$('#resume').disabled=!localWorld&&!networkUp;$('#replay').hidden=!ended&&!paused;$('#replay').textContent=paused?'Reset round ↻':'Play again ↻';$('#replay').disabled=spectator;if(paused||ended){$('#resultEyebrow').textContent=ended?'ROUND COMPLETE':'TAKE YOUR TIME';$('#resultTitle').textContent=paused?'Paused':state.winnerId==='draw'?'A shared victory':state.mode==='boss'&&state.winnerId==='heroes'?'Team victory!':state.mode==='boss'&&state.winnerId==='boss'?'The boss wins this round':state.winnerId===myId?(state.mode==='practice'?'Challenge complete!':'You won!'):'A worthy battle';$('#resultText').textContent=state.reason||'';const reward=(state.rewards||[]).find(r=>r.playerId===myId);$('#resultReward').textContent=reward?'Earned ◆ '+reward.gems+' gems · '+reward.xp+' XP · ϟ '+reward.energy+' energy':ended?'Try a new strategy and play again.':'';}
}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;frames++;if(now-lastFPS>1000){fps=Math.round(frames*1000/(now-lastFPS));frames=0;lastFPS=now;}if(!$('#game').hidden&&state){if(localWorld&&state.status==='playing'){accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps++<5){G.step(localWorld,{[myId]:{...keys,...taps}},1/60);for(const k of tapKeys)delete taps[k];accumulator-=1/60;}handleRewards();}const age=Math.min(.12,(now-lastStateAt)/1000);for(const p of state.players){let x=p.x,y=p.y,depth=p.depth||0,face=p.face;if(!localWorld&&state.status==='playing'&&p.alive){const old=positions.get(p.id);if(p.id===myId){const dir=Number(keys.right)-Number(keys.left),dd=Number(keys.down)-Number(keys.up),diag=dir&&dd?.72:1,speed=G.MoveBook.styles[p.character].speed*(p.sessionSpeed||1)*(keys.block?.35:1)*(p.frozen||p.slowed?.5:1)*(p.rooted||p.bubbled?0:1),look=Math.min(.12,age+rtt/2000);x+=dir*speed*diag*look;depth+=dd*speed*.66*diag*look;if(dir)face=dir;y+=p.vy*Math.min(age,.06);}else if(old&&age<.1){x+=p.vx*Math.min(age,.05);depth+=(p.vdepth||0)*Math.min(age,.05);y+=p.vy*Math.min(age,.04);}}x=Math.max(60,Math.min(G.WIDTH-60,x));depth=Math.max(G.DEPTH_MIN,Math.min(G.DEPTH_MAX,depth));y=Math.max(120,Math.min(G.GROUND,y));const old=positions.get(p.id);if(!old||localWorld||state.status!=='playing'||Math.abs(x-old.x)>220||Math.abs(depth-(old.depth||0))>100||!p.alive)positions.set(p.id,{x,y,depth,face});else{const blend=1-Math.exp(-24*dt);old.x+=(x-old.x)*blend;old.y+=(y-old.y)*blend;old.depth+=(depth-(old.depth||0))*blend;old.face=face;}}
if(gauntletRun)checkGauntletOutcome();A.drawWorld($('#arena').getContext('2d'),state,now/1000,{positions,reduced:settings.reduced,myId});if(now-lastHUD>100){updateHUD();$('#perfStatus').textContent=(settings.reduced?'SMOOTH':'FULL')+' · '+fps+' FPS'+(!localWorld&&rtt?' · '+Math.round(rtt)+' ms':'');lastHUD=now;}}
requestAnimationFrame(frame);}
$('#playerName').addEventListener('change',()=>save({...profile,name:$('#playerName').value||'Player'}));all('[data-boost]').forEach(b=>b.onclick=()=>armBoost(b.dataset.boost));all('[data-tab]').forEach(b=>b.onclick=()=>changeTab(b.dataset.tab));$('#changeBeast').onclick=()=>changeTab('roster');all('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;all('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));if(networkUp)send({type:'configure',profile,mode});});$('#joinOnline').onclick=joinNetwork;$('#leaveOnline').onclick=()=>{leaveNetwork();state=null;};$('#startOnline').onclick=()=>{release();send({type:'control',action:'start'});};$('#practice').onclick=()=>startLocal('practice');$('#questPractice').onclick=()=>startLocal('practice');$('#questBattle').onclick=()=>startLocal('quest');$('#startGauntlet').onclick=startGauntlet;$('#gauntletRestart').onclick=startGauntlet;$('#gauntletContinue').onclick=startGauntletStage;$('#gauntletCertificate').onclick=showCertificate;$('#gauntletLobby').onclick=returnLobby;$('#downloadCertificate').onclick=downloadCertificate;$('#printCertificate').onclick=()=>window.print();$('#fullscreenButton').onclick=toggleFullscreen;$('#pause').onclick=pause;$('#resume').onclick=resume;$('#replay').onclick=replay;$('#backLobby').onclick=returnLobby;$('#resultLobby').onclick=returnLobby;$('#settingsButton').onclick=()=>$('#settings').showModal();$('#reducedEffects').checked=settings.reduced;$('#soundEnabled').checked=settings.sound;for(const id of ['reducedEffects','soundEnabled'])$('#'+id).onchange=()=>{settings.reduced=$('#reducedEffects').checked;settings.sound=$('#soundEnabled').checked;try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{}if(settings.sound)tone('reward');};
setInterval(()=>{if(networkUp)sendInput();},100);setInterval(()=>{if(networkUp){const t=Date.now();pendingPings.clear();pendingPings.set(t,performance.now());send({type:'ping',t});}},2000);
window.addEventListener('online',()=>{if(networkWanted&&!ws)joinNetwork();});
if(location.hostname.endsWith('.github.io')){$('#joinOnline').disabled=true;$('#networkStatus').textContent='Solo preview. For multiplayer, open your host’s shared game link.';$('#shareLink').hidden=true;}
fetch('./health').then(r=>r.json()).then(h=>{const url=h.playUrl||h.urls?.find(u=>u.startsWith('https:'))||new URL('./',location.href).href;$('#shareLink').href=url;$('#shareLink').textContent=url;}).catch(()=>{$('#shareLink').href=location.origin;$('#shareLink').textContent=location.origin;});
async function prepareOffline(){if(!('serviceWorker'in navigator)||!window.isSecureContext){$('#offlineStatus').textContent='OPEN HTTPS LINK TO SAVE OFFLINE';$('#cacheInfo').textContent='Use the Tailscale HTTPS game link once to save the game for offline quests. This open tab can already run solo practice.';return;}try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('#offlineStatus').textContent='OFFLINE QUESTS READY';$('#cacheInfo').textContent='This game is saved for offline quests. You can reopen it on this device without a connection.';}catch{$('#offlineStatus').textContent='KEEP THIS TAB OPEN FOR OFFLINE';$('#cacheInfo').textContent='Offline saving was unavailable. You can still play solo in this open tab.';}}
window.addEventListener('beast-art-ready',()=>renderProfile());
save(profile);renderArenas();showHub();applyGameLanguage();prepareOffline();if(new URLSearchParams(location.search).get('mode')==='gauntlet')setTimeout(startGauntlet,0);requestAnimationFrame(frame);
window.BeastApp={get state(){return state;},get profile(){return profile;},get keys(){return{...keys};},get networkUp(){return networkUp;},get myId(){return myId;},get fps(){return fps;},get position(){return positions.get(myId);}};
})();
