(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BeastMoves=api;})(globalThis,function(){
'use strict';
const styles={
 frost:{title:'THE CRYSTAL WOLF',role:'Control · 冰霜控制',speed:282,color:'#9fe5ff',accent:'#e9fbff',description:'Ice lances and crystal traps. Slow rivals, then keep your distance.'},
 ember:{title:'THE MAGMA RHINO',role:'Heavy · 熔岩重击',speed:235,color:'#ffab64',accent:'#ffe1a1',description:'Heavy armor, arcing bombs and delayed eruptions. Make the ground dangerous.'},
 moss:{title:'THE GROVE KEEPER',role:'Sustain · 藤蔓守护',speed:240,color:'#a0dea0',accent:'#ecf8ba',description:'Reach with vines. Hold your healing grove while roots catch rivals.'},
 volt:{title:'THE STORM LYNX',role:'Speed · 闪电突袭',speed:326,color:'#d2b5ff',accent:'#fff3bd',description:'Fast claws, chain lightning and three afterimage strikes. Stay on the move.'},
 twins:{title:'PIP + PEBBLE',role:'Combo · 双兽连招',speed:300,color:'#ffdb95',accent:'#a2e8ff',description:'Every paw has a partner. Echo strikes, returning comets and a pincer combo.'},
 fluffy:{title:"LEO'S FIRE FAMILIAR",role:'Air · 龙息俯冲',speed:272,color:'#ffb092',accent:'#ffe7ba',description:'Fluffy keeps his antlers and heart soulstone. Breathe fire, scatter petals and dive from a cloud.'},
 'water-rat':{title:"NATHAN'S WATER FAMILIAR",role:'Tricks · 泡泡水流',speed:306,color:'#a8d8f1',accent:'#e2f7ff',description:'Round ears, tiny paws and a blue heart. Slip away, shield with bubbles and launch a water jet.'}
};
const m=(label,detail,type,damage,range,cooldown,extra={})=>({label,detail,type,damage,range,cooldown,...extra});
const sets={
 frost:{punch:m('Ice claw','Quick claw; briefly chills a rival.','melee',8,100,.36,{fx:'ice-claw',slow:.35}),kick:m('Fang rise','An upward swipe lifts close rivals.','melee',12,135,.75,{fx:'ice-rise',launch:230}),spin:m('Snow ring','A lingering snow ring slows anyone inside.','zone',5,145,3.1,{fx:'snow-ring',duration:1.05,interval:.38,slow:.4,cost:8}),dash:m('Ice slide','Slide away and leave a slippery trail.','dash',0,190,2.9,{fx:'ice-slide',invul:.12,trail:true}),super:m('Ice lance','A fast crystal pierces two targets.','projectile',18,570,4.1,{fx:'ice-lance',speed:760,radius:18,pierce:2,slow:.7,cost:17}),special:m('Crystal cage','Three pulses from a marked crystal trap.','zone',9,140,6.8,{fx:'crystal-cage',offset:190,delay:.35,duration:1.25,interval:.5,freeze:.45,cost:25})},
 ember:{punch:m('Stone fist','A slow, heavy punch pushes rivals back.','melee',12,102,.52,{fx:'stone-fist',push:260}),kick:m('Quake kick','A low shockwave; airborne rivals can jump over it.','melee',16,155,.98,{fx:'quake',ground:true,push:310}),spin:m('Magma roll','Roll forward into a heavy close strike.','charge',17,120,3.3,{fx:'magma-roll',distance:95,push:330,cost:9}),dash:m('Armor rush','A short shoulder rush with a protective shell.','dash',0,125,3.2,{fx:'armor-rush',shield:14}),super:m('Lava bomb','Lob a bomb that bursts when it lands.','projectile',22,520,4.7,{fx:'lava-bomb',speed:370,vy:-330,gravity:720,radius:23,splash:120,cost:20}),special:m('Eruption','Three marked vents erupt in a row. Jump clear.','eruption',12,94,7.2,{fx:'eruption',cost:26})},
 moss:{punch:m('Vine whip','A long vine reaches further than most claws.','melee',7,143,.47,{fx:'vine-whip',slow:.2}),kick:m('Shell bash','A sturdy shell strike pushes rivals out.','melee',13,125,.82,{fx:'shell-bash',push:280}),spin:m('Briar ring','Thorns pulse around you for a moment.','zone',5,155,3.3,{fx:'briar-ring',duration:1.25,interval:.45,cost:8}),dash:m('Leaf guard','A short escape wrapped in a 20-point leaf shield.','dash',0,115,3.8,{fx:'leaf-guard',shield:20}),super:m('Root seed','A seed bursts into roots and holds one rival.','projectile',13,500,4.8,{fx:'root-seed',speed:485,radius:22,root:.85,cost:17}),special:m('Living grove','Stay in your grove to heal; rivals inside meet thorns.','grove',5,158,8.5,{fx:'living-grove',duration:2.7,interval:.85,heal:8,cost:27})},
 volt:{punch:m('Spark claw','Very fast claws; every third hit adds a spark.','melee',6,94,.25,{fx:'spark-claw',combo:true}),kick:m('Thunder heel','A rising kick launches a rival.','melee',10,136,.63,{fx:'thunder-heel',launch:270}),spin:m('Pulse ring','A wide delayed shock drains flight energy.','zone',14,205,3.4,{fx:'pulse-ring',delay:.22,duration:.1,interval:1,drain:15,cost:10}),dash:m('Flash step','Blink far; an electric line hits crossed rivals.','dash',5,245,3.1,{fx:'flash-step',invul:.16,line:true}),super:m('Chain bolt','Lightning jumps between nearby rivals and targets.','chain',19,350,4.9,{fx:'chain-bolt',cost:21}),special:m('Afterstrike','Three marked afterimages strike ahead, one after another.','afterstrike',11,90,6.9,{fx:'afterstrike',cost:25})},
 twins:{punch:m('Double paw','Pip hits first; Pebble follows a beat later.','echo',5,102,.52,{fx:'double-paw',echoDelay:.14}),kick:m('Twin flip','Two staggered kicks, with a rising second hit.','echo',7,142,.9,{fx:'twin-flip',echoDelay:.22,launch:150}),spin:m('Orbit dance','Two circles strike on either side of you.','orbit',6,95,3.5,{fx:'orbit-dance',cost:10}),dash:m('Partner swap','A quick swap leaves a harmless partner silhouette.','dash',0,180,2.9,{fx:'partner-swap',invul:.19}),super:m('Return comet','A comet hits on its way out and again on its return.','projectile',11,470,4.9,{fx:'return-comet',speed:500,radius:25,boomerang:true,pierce:8,cost:18}),special:m('Pincer star','Two partners close in on one marked spot.','pincer',15,112,7.3,{fx:'pincer-star',cost:25})},
 fluffy:{punch:m('Warm paw','A small fiery paw swipe.','melee',8,96,.38,{fx:'warm-paw'}),kick:m('Dragon tail','A broad tail swipe also catches rivals behind you.','melee',13,145,.85,{fx:'dragon-tail',all:true,push:185}),spin:m('Fire petals','Six fire petals fly outward in different directions.','petals',7,320,3.8,{fx:'fire-petals',cost:13}),dash:m('Cloud ride','Ride a cloud forward and upward.','dash',0,175,3.0,{fx:'cloud-ride',rise:150}),super:m('Dragon breath','Four close cone-shaped breaths; watch your direction.','breath',7,255,5.1,{fx:'dragon-breath',cost:22}),special:m('Sky dive','Leap, then crash onto the marked spot in a fiery ring.','dive',29,140,7.4,{fx:'sky-dive',cost:28})},
 'water-rat':{punch:m('Splash paw','A water slap briefly slows a rival.','melee',7,104,.35,{fx:'splash-paw',slow:.25}),kick:m('Foam flip','A splash kicks a rival upward.','melee',11,138,.78,{fx:'foam-flip',launch:230}),spin:m('Bubble guard','A 24-point bubble shield and a close splash.','guard',9,115,4.3,{fx:'bubble-guard',shield:24,cost:11}),dash:m('Ripple slip','Slip through danger beneath a rolling ripple.','dash',0,195,3.3,{fx:'ripple-slip',invul:.32}),super:m('Water jet','A fast, piercing water jet pushes everyone in its path.','projectile',16,630,4.6,{fx:'water-jet',speed:930,radius:24,pierce:8,push:310,cost:18}),special:m('Bubble prison','A slow bubble lifts one rival, then pops with a splash.','projectile',7,440,7.5,{fx:'bubble-prison',speed:285,radius:37,bubble:.8,cost:25})}
};
function get(character,key){return (sets[character]||sets.frost)[key];}
return {styles,sets,get};
});
