(function(){'use strict';
const G=window.BeastGame,A=window.BeastArt,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const PROFILE_KEY='beast-kings-evolve-profile',SETTINGS_KEY='beast-kings-evolve-settings';
function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
let profile=G.normalizeProfile(readJSON(PROFILE_KEY,{id:crypto.randomUUID(),name:'Player',character:'frost'}));
let settings={reduced:true,sound:false,...readJSON(SETTINGS_KEY,{})},mode='duel',arena='moon',tab='lobby';
let state=null,localWorld=null,localMode='practice',networkWanted=false,networkUp=false,ws=null,myId=profile.id,spectator=false,seq=0,retryTimer=null,rtt=0,lastStateAt=0,lastRound='',lastHUD=0,lastFrame=performance.now(),accumulator=0,lastFPS=performance.now(),frames=0,fps=60,toastTimer=null;
const taps={},tapKeys=['jump','punch','kick','spin','dash','super','special'];const keys={},pointers=new Map(),keyboard=new Set(),positions=new Map(),seenRewards=new Set(profile.rewardIds),pendingPings=new Map();
const keyMap={KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',Space:'jump',ArrowUp:'jump',KeyS:'block',ArrowDown:'block',KeyJ:'punch',KeyI:'kick',KeyK:'spin',KeyL:'dash',KeyU:'super',KeyO:'special'};
let audioCtx=null,lastSound=0;
function tone(kind){if(!settings.sound||performance.now()-lastSound<95)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),gain=audioCtx.createGain(),t=audioCtx.currentTime;o.type='sine';o.frequency.setValueAtTime(kind==='reward'?620:kind==='dash'?450:150,t);o.frequency.exponentialRampToValueAtTime(kind==='reward'?920:65,t+.13);gain.gain.setValueAtTime(.055,t);gain.gain.exponentialRampToValueAtTime(.001,t+.17);o.connect(gain);gain.connect(audioCtx.destination);o.start(t);o.stop(t+.18);lastSound=performance.now();}catch{}}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200);}
function save(next,announce){const oldTier=profile.evolution;profile=G.normalizeProfile(next);try{localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));$('#saveStatus').textContent='Progress saved on this device';}catch{$('#saveStatus').textContent='Storage unavailable — keep this tab open';}renderProfile();if(networkUp&&state?.status==='lobby')send({type:'configure',profile});if(profile.evolution>oldTier){tone('reward');toast('Your beast evolved to Form '+(profile.evolution+1)+'!');}else if(announce)toast(announce);}
function renderProfile(){const c=G.CHARACTERS[profile.character];$('#gems').textContent=profile.gems;$('#reserve').textContent=profile.energy;$('#baseBalance').textContent=profile.gems+' gems';if(document.activeElement!==$('#playerName'))$('#playerName').value=profile.name;$('#beastName').textContent=c.name;$('#beastSummary').textContent=c.description;$('#specialLabel').textContent=c.special;$('#evolution').textContent='FORM '+['I','II','III','IV'][profile.evolution];const thresholds=[0,50,140,300],lo=thresholds[profile.evolution],hi=thresholds[profile.evolution+1]||300;$('#xpBar').style.width=(profile.evolution===3?100:Math.min(100,(profile.xp-lo)/(hi-lo)*100))+'%';$('#xpLabel').textContent=profile.xp+' XP'+(profile.evolution<3?' / '+hi+' TO EVOLVE':' / FINAL FORM');A.portrait($('#portrait'),profile.character,profile.evolution);renderRoster();renderShop();renderMoves();}
function renderMoves(){const c=G.CHARACTERS[profile.character];$('#moveTitle').textContent=c.role;$('#moveCharacter').textContent=c.name+' · Move book';const root=$('#moveCards');root.replaceChildren();for(const [key,shortcut]of [['punch','J'],['kick','I'],['spin','K'],['dash','L'],['super','U'],['special','O']]){const m=G.MoveBook.get(profile.character,key),card=document.createElement('article'),title=document.createElement('b'),detail=document.createElement('p'),hint=document.createElement('small');card.className='move-card';title.textContent=m.label;detail.textContent=m.detail;hint.textContent=shortcut+' · '+m.cooldown+'s cooldown'+(m.cost?' · '+m.cost+' energy':'');card.append(title,detail,hint);root.append(card);}}
function changeTab(next){tab=next;for(const id of ['lobby','roster','base','quests'])$('#'+id+'Panel').hidden=id!==next;all('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===next));}
function showHub(){document.body.classList.remove('playing');$('#hub').hidden=false;$('#game').hidden=true;positions.clear();changeTab(tab);renderProfile();}
function showGame(){document.body.classList.add('playing');$('#hub').hidden=true;$('#game').hidden=false;}
function renderRoster(){const root=$('#rosterCards');root.replaceChildren();for(const c of Object.values(G.CHARACTERS)){const card=document.createElement('article');card.className='beast-card'+(profile.character===c.id?' selected':'');const cv=document.createElement('canvas');cv.width=400;cv.height=250;cv.setAttribute('aria-label',c.name+' character portrait');card.append(cv);const title=document.createElement('h3');title.textContent=c.name;card.append(title);const role=document.createElement('small');role.className='beast-role';role.textContent=c.role;card.append(role);const p=document.createElement('p');p.textContent=c.description;card.append(p);const special=document.createElement('div');special.className='special-note';special.textContent='◇ '+c.special;card.append(special);const b=document.createElement('button');b.dataset.character=c.id;b.textContent=profile.character===c.id?'Selected ✓':'Choose '+c.name;b.onclick=()=>{save({...profile,character:c.id},c.name+' selected');};card.append(b);root.append(card);A.portrait(cv,c.id,profile.evolution);}}
function shopCard(title,description,icon){const card=document.createElement('article');card.className='shop-card';const i=document.createElement('div');i.className='shop-icon';i.textContent=icon;const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=description;card.append(i,h,p);return card;}
function renderShop(){const root=$('#upgradeCards');root.replaceChildren();for(const u of Object.values(G.UPGRADES)){const level=profile.upgrades[u.id]||0,cost=u.costs[level],card=shopCard(u.name,u.description,{attack:'✦',armor:'◒',energy:'ϟ'}[u.id]);const bars=document.createElement('div');bars.className='levels';for(let n=0;n<3;n++){const i=document.createElement('i');if(n<level)i.className='filled';bars.append(i);}card.append(bars);const b=document.createElement('button');b.dataset.upgrade=u.id;b.textContent=level>=u.maxLevel?'Maximum level ✓':'Level '+(level+1)+' · ◆ '+cost;b.disabled=level>=u.maxLevel||profile.gems<cost;b.onclick=()=>{const result=G.buyUpgrade(profile,u.id);if(result.ok)save(result.profile,u.name+' upgraded');else toast(result.error);};card.append(b);root.append(card);}
const equipment=$('#equipmentCards');equipment.replaceChildren();for(const e of Object.values(G.EQUIPMENT)){const own=profile.ownedEquipment.includes(e.id),equipped=profile.equipment[e.slot]===e.id,card=shopCard(e.name,e.description,{weapon:'⚔',armor:'◈',tool:'⚙'}[e.slot]);const b=document.createElement('button');b.dataset.equipment=e.id;b.disabled=equipped||(!own&&profile.gems<e.cost);b.textContent=equipped?'Equipped ✓':own?'Equip':'Buy · ◆ '+e.cost;b.onclick=()=>{const result=own?G.equipItem(profile,e.id):G.buyEquipment(profile,e.id);if(result.ok)save(result.profile,e.name+' equipped');else toast(result.error);};card.append(b);equipment.append(card);}}
function renderArenas(){const root=$('#arenaChoices');root.replaceChildren();for(const a of Object.values(G.ARENAS)){const b=document.createElement('button');b.className='arena-option'+(a.id===arena?' selected':'');b.dataset.arena=a.id;b.textContent=a.name;b.onclick=()=>{arena=a.id;renderArenas();if(networkUp)send({type:'configure',arena,mode,profile});};root.append(b);}}
function send(msg){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(msg));}
function sendInput(){if(!networkUp||spectator)return;send({type:'input',seq:++seq,input:document.hidden?{}:{...keys}});}
function release(){for(const k of tapKeys)delete taps[k];pointers.clear();keyboard.clear();for(const k of G.INPUT_KEYS)keys[k]=false;all('[data-key].held').forEach(b=>b.classList.remove('held'));sendInput();}
function rebuild(){const previous={...keys};for(const k of G.INPUT_KEYS)keys[k]=false;for(const k of pointers.values())keys[k]=true;for(const k of keyboard)keys[k]=true;for(const k of tapKeys)if(keys[k]&&!previous[k])taps[k]=true;all('[data-key]').forEach(b=>b.classList.toggle('held',!!keys[b.dataset.key]));sendInput();}
all('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.key);rebuild();if(!['left','right','block','jump'].includes(b.dataset.key))tone(b.dataset.key);});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>{pointers.delete(e.pointerId);rebuild();});});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)||$('#game').hidden)return;const k=keyMap[e.code];if(k){e.preventDefault();keyboard.add(k);rebuild();}});window.addEventListener('keyup',e=>{const k=keyMap[e.code];if(k){e.preventDefault();keyboard.delete(k);rebuild();}});
window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden){release();if(state?.status==='playing')pause();}});window.addEventListener('pagehide',()=>{release();if(ws)ws.close();});
function leaveNetwork(){networkWanted=false;networkUp=false;clearTimeout(retryTimer);retryTimer=null;const old=ws;ws=null;if(old)old.close();spectator=false;$('#joinOnline').hidden=false;$('#roomInfo').hidden=true;$('#networkStatus').textContent='Ready when you are';}
function joinNetwork(){if(location.hostname.endsWith('.github.io')){toast('For multiplayer, open the game link shared by your host. Practice and quests work here.');return;}if(ws&&[WebSocket.CONNECTING,WebSocket.OPEN].includes(ws.readyState))return;release();localWorld=null;state=null;networkWanted=true;$('#joinOnline').disabled=true;$('#networkStatus').textContent='Connecting through Tailscale…';const socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);ws=socket;socket.onopen=()=>send({type:'hello',profile});socket.onmessage=event=>{if(ws!==socket)return;let msg;try{msg=JSON.parse(event.data);}catch{return;}if(msg.type==='welcome'){myId=msg.id||profile.id;spectator=!!msg.spectator;networkUp=true;seq=0;$('#joinOnline').hidden=true;$('#joinOnline').disabled=false;$('#roomInfo').hidden=false;if(!spectator)send({type:'configure',profile});}else if(msg.type==='state'){const incoming=msg.state;const changedRound=lastRound!==incoming.roundId;state=incoming;lastStateAt=performance.now();if(changedRound){positions.clear();lastRound=incoming.roundId;release();}arena=state.arena;mode=state.mode;if(state.status==='lobby')renderRoom();if(state.status==='lobby'){if(!$('#game').hidden)showHub();}else showGame();handleRewards();if(changedRound)updateHUD();}else if(msg.type==='error'){toast(msg.message||'Unable to join this room');if(msg.message&&/already|duplicate/i.test(msg.message)){networkWanted=false;$('#joinOnline').disabled=false;}}else if(msg.type==='pong'){const sent=pendingPings.get(msg.t);if(sent){rtt=performance.now()-sent;pendingPings.delete(msg.t);}}};socket.onclose=()=>{if(ws!==socket)return;ws=null;networkUp=false;release();$('#joinOnline').disabled=false;$('#networkStatus').textContent='Connection lost. Keep Tailscale connected; retrying…';if(state&&state.status==='playing'){state={...state,status:'paused',reason:'Connection paused. Reconnecting to the host…'};updateHUD();}if(networkWanted)retryTimer=setTimeout(joinNetwork,1500);};socket.onerror=()=>{};}
function renderRoom(){const slots=state?.slots||[],connected=slots.filter(s=>s?.connected);const signature=JSON.stringify([slots,mode,arena,spectator,Math.round(rtt/25)]);if(signature===roomSignature)return;roomSignature=signature;$('#networkStatus').textContent=spectator?'Spectating — three player slots are occupied':connected.length+' / 3 players connected'+(rtt?' · '+Math.round(rtt)+' ms':'');$('#roomPlayers').replaceChildren();for(const s of slots.filter(Boolean)){const row=document.createElement('div');row.textContent=(s.connected?'● ':'○ ')+s.name+' · '+(G.CHARACTERS[s.character]?.name||s.character);$('#roomPlayers').append(row);}$('#startOnline').disabled=connected.length<2||spectator;all('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));renderArenas();}
function handleRewards(){if(!state)return;for(const reward of state.rewards||[]){if(reward.playerId!==myId||seenRewards.has(reward.id))continue;const result=G.grantReward(profile,reward);if(result.ok){seenRewards.add(reward.id);save(result.profile);tone('reward');}}}
function startLocal(nextMode){release();leaveNetwork();localMode=nextMode;myId=profile.id;localWorld=G.createGame({mode:nextMode,arena,players:[{id:profile.id,name:profile.name,character:profile.character,profile}]});localWorld.status='playing';state=localWorld;lastRound=state.roundId;positions.clear();accumulator=0;showGame();updateHUD();}
function returnLobby(){release();if(networkWanted)leaveNetwork();localWorld=null;state=null;showHub();changeTab('lobby');}
function pause(){release();if(localWorld){localWorld.status='paused';localWorld.reason='Take your time. Your practice is paused.';updateHUD();}else send({type:'control',action:'pause'});}
function resume(){release();if(localWorld){localWorld.status='playing';accumulator=0;updateHUD();}else if(networkUp)send({type:'control',action:'resume'});else toast('Reconnect to the host before resuming.');}
function replay(){release();if(localWorld)startLocal(localMode);else send({type:'control',action:'reset'});}
let roomSignature='';
let hudSignature='';function updateHUD(){if(!state)return;const title=state.mode==='practice'?'PRACTICE RANGE':state.mode==='quest'?'SENTINEL TRIAL':state.mode==='crown'?'CROWN HUNT':state.players.length===3?'THREE-BEAST FREE-FOR-ALL':'BEAST BATTLE';$('#gameMode').textContent=title;$('#gameNetwork').textContent=localWorld?'SOLO · EARN BY PLAYING':(networkUp?'TAILSCALE · SHARED ARENA':'RECONNECTING');const root=$('#healthBars'),sig=state.players.map(p=>p.id+':'+p.character).join('|');if(sig!==hudSignature){hudSignature=sig;root.replaceChildren();for(const p of state.players){const card=document.createElement('div');card.className='health-card';card.dataset.player=p.id;const name=document.createElement('div');name.className='health-name';name.append(document.createElement('span'),document.createElement('b'));const track=document.createElement('div');track.className='health-track';track.append(document.createElement('i'));const detail=document.createElement('div');detail.className='health-detail';card.append(name,track,detail);root.append(card);}}
for(const [i,p] of state.players.entries()){const card=root.children[i];card.querySelector('.health-name span').textContent=p.name+(p.id===myId?' · YOU':'');card.querySelector('.health-name b').textContent=Math.ceil(p.hp)+' HP';card.querySelector('.health-track i').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';card.querySelector('.health-track i').style.background=G.CHARACTERS[p.character]?.color||'#fff';card.querySelector('.health-detail').textContent=G.CHARACTERS[p.character]?.name+' · FORM '+((p.evolution||0)+1)+(['practice','crown'].includes(state.mode)?' · '+p.charges+'/5 TARGETS':'');}
const me=state.players.find(p=>p.id===myId)||state.players[0];if(me){$('#flightEnergy').style.width=(me.energy/me.maxEnergy*100)+'%';$('#flightValue').textContent=Math.round(me.energy)+' / '+me.maxEnergy;all('.actions [data-key]').forEach(b=>{const move=G.MoveBook.get(me.character,b.dataset.key),cd=me.cd[b.dataset.key]||0;b.querySelector('span').textContent=move.label;b.title=move.detail;b.setAttribute('aria-label',move.label+': '+move.detail);b.classList.toggle('cooling',cd>.08);b.style.setProperty('--cooldown',Math.min(100,cd/move.cooldown*100)+'%');b.querySelector('em').textContent=cd>.08?cd.toFixed(1):'';});}
const paused=state.status==='paused',ended=state.status==='ended';$('#gameOverlay').hidden=!paused&&!ended;$('#pause').disabled=state.status!=='playing';$('#resume').hidden=!paused;$('#resume').disabled=!localWorld&&!networkUp;$('#replay').hidden=!ended&&!paused;$('#replay').textContent=paused?'Reset round ↻':'Play again ↻';$('#replay').disabled=spectator;if(paused||ended){$('#resultEyebrow').textContent=ended?'ROUND COMPLETE':'TAKE YOUR TIME';$('#resultTitle').textContent=paused?'Paused':state.winnerId==='draw'?'A shared victory':state.winnerId===myId?(state.mode==='practice'?'Challenge complete!':'You won!'):'A worthy battle';$('#resultText').textContent=state.reason||'';const reward=(state.rewards||[]).find(r=>r.playerId===myId);$('#resultReward').textContent=reward?'Earned ◆ '+reward.gems+' gems · '+reward.xp+' XP · ϟ '+reward.energy+' energy':ended?'Try a new strategy and play again.':'';}
}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;frames++;if(now-lastFPS>1000){fps=Math.round(frames*1000/(now-lastFPS));frames=0;lastFPS=now;}if(!$('#game').hidden&&state){if(localWorld&&state.status==='playing'){accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps++<5){G.step(localWorld,{[myId]:{...keys,...taps}},1/60);for(const k of tapKeys)delete taps[k];accumulator-=1/60;}handleRewards();}const age=Math.min(.12,(now-lastStateAt)/1000);for(const p of state.players){let x=p.x,y=p.y,face=p.face;if(!localWorld&&state.status==='playing'&&p.alive){const old=positions.get(p.id);if(p.id===myId){const dir=Number(keys.right)-Number(keys.left);x+=dir*G.MoveBook.styles[p.character].speed*(keys.block?.35:1)*(p.frozen||p.slowed?.5:1)*(p.rooted||p.bubbled?0:1)*Math.min(.12,age+rtt/2000);if(dir)face=dir;y+=p.vy*Math.min(age,.06);}else if(old&&age<.1){x+=p.vx*Math.min(age,.05);y+=p.vy*Math.min(age,.04);}}x=Math.max(50,Math.min(1150,x));y=Math.max(120,Math.min(480,y));const old=positions.get(p.id);if(!old||localWorld||state.status!=='playing'||Math.abs(x-old.x)>170||!p.alive)positions.set(p.id,{x,y,face});else{const blend=1-Math.exp(-24*dt);old.x+=(x-old.x)*blend;old.y+=(y-old.y)*blend;old.face=face;}}
A.drawWorld($('#arena').getContext('2d'),state,now/1000,{positions,reduced:settings.reduced,myId});if(now-lastHUD>100){updateHUD();$('#perfStatus').textContent=(settings.reduced?'SMOOTH':'FULL')+' · '+fps+' FPS'+(!localWorld&&rtt?' · '+Math.round(rtt)+' ms':'');lastHUD=now;}}
requestAnimationFrame(frame);}
$('#playerName').addEventListener('change',()=>save({...profile,name:$('#playerName').value||'Player'}));all('[data-tab]').forEach(b=>b.onclick=()=>changeTab(b.dataset.tab));$('#changeBeast').onclick=()=>changeTab('roster');all('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;all('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));if(networkUp)send({type:'configure',profile,mode});});$('#joinOnline').onclick=joinNetwork;$('#leaveOnline').onclick=()=>{leaveNetwork();state=null;};$('#startOnline').onclick=()=>{release();send({type:'control',action:'start'});};$('#practice').onclick=()=>startLocal('practice');$('#questPractice').onclick=()=>startLocal('practice');$('#questBattle').onclick=()=>startLocal('quest');$('#pause').onclick=pause;$('#resume').onclick=resume;$('#replay').onclick=replay;$('#backLobby').onclick=returnLobby;$('#resultLobby').onclick=returnLobby;$('#settingsButton').onclick=()=>$('#settings').showModal();$('#reducedEffects').checked=settings.reduced;$('#soundEnabled').checked=settings.sound;for(const id of ['reducedEffects','soundEnabled'])$('#'+id).onchange=()=>{settings.reduced=$('#reducedEffects').checked;settings.sound=$('#soundEnabled').checked;try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{}if(settings.sound)tone('reward');};
setInterval(()=>{if(networkUp)sendInput();},100);setInterval(()=>{if(networkUp){const t=Date.now();pendingPings.clear();pendingPings.set(t,performance.now());send({type:'ping',t});}},2000);
window.addEventListener('online',()=>{if(networkWanted&&!ws)joinNetwork();});
if(location.hostname.endsWith('.github.io')){$('#joinOnline').disabled=true;$('#networkStatus').textContent='Solo preview. For multiplayer, open your host’s shared game link.';$('#shareLink').hidden=true;}
fetch('./health').then(r=>r.json()).then(h=>{const url=h.playUrl||h.urls?.find(u=>u.startsWith('https:'))||new URL('./',location.href).href;$('#shareLink').href=url;$('#shareLink').textContent=url;}).catch(()=>{$('#shareLink').href=location.origin;$('#shareLink').textContent=location.origin;});
async function prepareOffline(){if(!('serviceWorker'in navigator)||!window.isSecureContext){$('#offlineStatus').textContent='OPEN HTTPS LINK TO SAVE OFFLINE';$('#cacheInfo').textContent='Use the Tailscale HTTPS game link once to save the game for offline quests. This open tab can already run solo practice.';return;}try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('#offlineStatus').textContent='OFFLINE QUESTS READY';$('#cacheInfo').textContent='This game is saved for offline quests. You can reopen it on this device without a connection.';}catch{$('#offlineStatus').textContent='KEEP THIS TAB OPEN FOR OFFLINE';$('#cacheInfo').textContent='Offline saving was unavailable. You can still play solo in this open tab.';}}
window.addEventListener('beast-art-ready',()=>renderProfile());
save(profile);renderArenas();showHub();prepareOffline();requestAnimationFrame(frame);
window.BeastApp={get state(){return state;},get profile(){return profile;},get keys(){return{...keys};},get networkUp(){return networkUp;},get myId(){return myId;},get fps(){return fps;},get position(){return positions.get(myId);}};
})();
