'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),G=require('./shared');
function setup(character,count=2){const g=G.createGame({mode:'duel',players:Array.from({length:count},(_,i)=>({id:'p'+i,name:'QA '+i,character:i?'frost':character}))});g.status='playing';g.players.forEach((p,i)=>{p.x=300+i*160;p.face=i?-1:1;p.maxHp=p.hp=500;});return g;}
function tick(g,key,n=1){for(let i=0;i<n;i++)G.step(g,key?{p0:{[key]:true}}:{},1/60);}
test('All 42 moves resolve with finite state and bounded effects',()=>{for(const id of Object.keys(G.CHARACTERS))for(const key of Object.keys(G.MoveBook.sets[id])){const g=setup(id,3);tick(g,key);assert(g.players[0].cd[key]>0,id+' '+key);tick(g,null,120);for(const p of g.players)for(const stat of ['x','y','hp','energy'])assert(Number.isFinite(p[stat]),id+' '+key+' '+stat);assert(g.projectiles.length<=32);assert(g.zones.length<=18);assert(g.pending.length<=32);assert(Buffer.byteLength(JSON.stringify(G.snapshot(g)))<24000);}});
test('Frost trap warns before damage, then freezes only nearby rivals',()=>{const g=setup('frost',3),p=g.players[1];p.x=490;g.players[2].x=1100;tick(g,'special');assert.equal(p.hp,500);assert(g.zones[0].wait>0);tick(g,null,16);assert.equal(p.hp,500);tick(g,null,8);assert(p.hp<500);assert(p.frozen>0);assert.equal(g.players[2].hp,500);});
test('Ice lance travels and pierces exactly two victims',()=>{const g=setup('frost',3);g.players[1].x=570;g.players[2].x=680;tick(g,'super');assert(g.projectiles.length);assert.equal(g.players[1].hp,500);tick(g,null,36);assert(g.players[1].hp<500);assert(g.players[2].hp<500);assert.equal(g.projectiles.length,0);});
test('Ember lobs an arcing bomb and three vents have staggered warnings',()=>{const g=setup('ember');g.players[1].x=720;tick(g,'super');const b=g.projectiles[0],start=b.y;tick(g,null,12);assert(b.y<start);tick(g,null,64);assert(g.effects.some(e=>e.type==='impact'&&e.style==='lava-bomb'));assert(g.players[1].hp<500);const h=setup('ember');tick(h,'special');assert.equal(h.zones.length,3);assert(h.zones[0].wait<h.zones[1].wait&&h.zones[1].wait<h.zones[2].wait);});
test('Moss grove heals inside its area and stops healing outside',()=>{const g=setup('moss');g.players[0].hp=250;g.players[1].x=1000;tick(g,'special');assert(g.players[0].hp>250);const hp=g.players[0].hp;g.players[0].x=900;tick(g,null,150);assert.equal(g.players[0].hp,hp);});
test('Root seed stops walking briefly, then releases',()=>{const g=setup('moss');g.players[1].x=490;tick(g,'super');tick(g,null,22);assert(g.players[1].rooted>0);g.players[1].vx=0;const x=g.players[1].x;G.step(g,{p1:{right:true}},1/60);assert.equal(g.players[1].x,x);tick(g,null,65);assert.equal(g.players[1].rooted,0);});
test('Volt chains to a second rival with reduced damage',()=>{const g=setup('volt',3);g.players[1].x=510;g.players[2].x=780;tick(g,'super');assert(g.players[1].hp<g.players[2].hp);assert(g.players[2].hp<500);assert.equal(g.effects.filter(e=>e.type==='chain').length,2);});
test('Twins comet returns and hits the same target again',()=>{const g=setup('twins');g.players[1].x=470;tick(g,'super');tick(g,null,20);const hp=g.players[1].hp;assert(hp<500);g.players[1].vx=0;tick(g,null,45);assert(g.players[1].hp<hp);});
test('Fluffy breath has four timed pulses and a directional cone',()=>{const g=setup('fluffy',3);g.players[1].x=410;g.players[2].x=250;tick(g,'super');const pulses=new Set(g.effects.filter(e=>e.type==='breath').map(e=>e.id));for(let i=0;i<40;i++){tick(g);for(const e of g.effects.filter(e=>e.type==='breath'))pulses.add(e.id);}assert.equal(pulses.size,4);assert(g.players[1].hp<480);assert.equal(g.players[2].hp,500);const h=setup('fluffy');tick(h,'special');assert(h.players[0].y<480);assert(h.effects.some(e=>e.type==='dive-mark'));tick(h,null,40);assert.equal(h.players[0].x,460);assert.equal(h.players[0].y,480);assert(h.players[1].hp<500);});
test('Water bubble captures, lifts, releases and pops',()=>{const g=setup('water-rat');g.players[1].x=455;tick(g,'special');tick(g,null,22);assert(g.players[1].bubbled>0);const hp=g.players[1].hp;tick(g,null,12);assert(g.players[1].y<480);tick(g,null,60);assert.equal(g.players[1].bubbled,0);assert(g.players[1].hp<hp);});
test('Water shield absorbs damage and expires; status projectiles pause exactly',()=>{const g=setup('water-rat');tick(g,'spin');assert(g.players[0].shield>0);g.players[1].x=350;const hp=g.players[0].hp;G.step(g,{p1:{punch:true}},1/60);assert.equal(g.players[0].hp,hp);tick(g,null,150);assert.equal(g.players[0].shield,0);const h=setup('water-rat');tick(h,'special');h.status='paused';const before=JSON.stringify(G.snapshot(h));tick(h,null,90);assert.equal(JSON.stringify(G.snapshot(h)),before);});
test('Different species speeds and escape mechanics are authoritative',()=>{const a=setup('volt'),b=setup('ember');for(let i=0;i<30;i++){G.step(a,{p0:{right:true}},1/60);G.step(b,{p0:{right:true}},1/60);}assert(a.players[0].x>b.players[0].x+40);const f=setup('fluffy'),w=setup('water-rat');tick(f,'dash');tick(w,'dash');assert(f.players[0].vy<0);assert(w.players[0].invulnerable>0);});


test('V4 depth axis: four-direction and diagonal movement are authoritative',()=>{const g=setup('frost');const p=g.players[0];G.step(g,{p0:{up:true}},1/60);const zUp=p.z;G.step(g,{p0:{down:true}},120);assert(p.z>zUp);assert(p.z<=G.DEPTH);const h=setup('volt');const diag=h.players[0];for(let i=0;i<60;i++)G.step(h,{p0:{right:true,up:true}},1/60);assert(diag.x>420);assert(diag.z<120);});
test('V4 melee and zones respect depth separation',()=>{const g=setup('frost');g.players[1].x=g.players[0].x+90;g.players[1].z=g.players[0].z+180;for(let i=0;i<20;i++)G.step(g,{p0:{punch:true}},1/60);assert.equal(g.players[1].hp,500);const h=setup('frost');h.players[1].x=h.players[0].x+90;h.players[1].z=h.players[0].z+30;for(let i=0;i<20;i++)G.step(h,{p0:{punch:true}},1/60);assert(h.players[1].hp<500);const z=setup('frost');z.players[1].x=z.players[0].x+90;z.players[1].z=z.players[0].z+180;for(let i=0;i<30;i++)G.step(z,{p0:{special:true}},1/60);assert.equal(z.players[1].hp,500);});
test('V4 boss mode: scripted golem rotates patterns and respects phases',()=>{const g=G.createGame({mode:'boss',players:[{id:'p0',name:'A'},{id:'p1',name:'B'}]});g.status='playing';const boss=g.players[2];assert(boss.boss&&boss.hp>700);const seen=new Set();for(let i=0;i<60*75;i++){g.players[0].invulnerable=99;g.players[1].invulnerable=99;G.step(g,{},1/60);seen.add(boss.pattern);}assert(seen.size>=3,'boss patterns rotate');});
test('V4 boss mode: weak point amplifies damage and team victory pays everyone',()=>{const g=G.createGame({mode:'boss',players:[{id:'p0',name:'A'},{id:'p1',name:'B'}]});g.status='playing';const boss=g.players[2],hero=g.players[0];hero.x=boss.x-90;hero.z=boss.z;boss.hp=2;boss.phase=3;boss.invulnerable=0;boss.weak=1;for(let i=0;i<30&&g.status==='playing';i++)G.step(g,{p0:{punch:true}},1/60);assert.equal(g.status,'ended');assert.equal(g.winnerId,'team');assert.equal(g.rewards.length,2);assert(g.rewards.every(r=>r.gems===14));});
test('V4 boss mode: idle team loses only after revives are spent',()=>{const g=G.createGame({mode:'boss',players:[{id:'p0',name:'A'}]});g.status='playing';for(let i=0;i<60*300&&g.status==='playing';i++)G.step(g,{},1/60);assert.equal(g.status,'ended');assert.equal(g.winnerId,'boss');assert.equal(g.players[0].revivesLeft,0);});
test('V4 boosts: cost gates, caps, mend healing and expiry',()=>{const g=setup('frost');assert.equal(G.applyBoost(g,'p0','nope').ok,false);assert.equal(G.applyBoost(g,'p0','swift').ok,true);assert.equal(G.applyBoost(g,'p0','swift').error,'Already running');assert.equal(G.applyBoost(g,'p0','aegis').ok,true);assert.equal(G.applyBoost(g,'p0','mend').error,'Two boosts already active');assert(g.players[0].shield>=30);const h=setup('moss');h.players[0].hp=40;assert.equal(G.applyBoost(h,'p0','mend').ok,true);for(let i=0;i<90;i++)G.step(h,{},1/60);assert(h.players[0].hp>40);for(let i=0;i<60*8;i++)G.step(h,{},1/60);assert.equal(h.players[0].boosts.length,0);});
test('V4 iPad shell: zoom lock, depth buttons and touch-action guards exist',()=>{const fs=require('fs'),path=require('path');const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');assert(/maximum-scale=1/.test(html));assert(/user-scalable=no/.test(html));assert(/data-key="up"/.test(html));assert(/data-key="down"/.test(html));const css=fs.readFileSync(path.join(__dirname,'style.css'),'utf8');assert(/touch-action:none/.test(css));assert(/env\(safe-area-inset-bottom\)/.test(css));const sw=fs.readFileSync(path.join(__dirname,'sw.js'),'utf8');assert(sw.includes('20260919-v4'));});
