'use strict';
const assert=require('node:assert/strict'),E=require('./shared.js'),{createServer}=require('./server.js'),{WebSocket}=require('ws');
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
function game(mode='duel',count=2){const g=E.createGame({mode,players:Array.from({length:count},(_,i)=>({id:'p'+i,name:'Player '+i,character:Object.keys(E.CHARACTERS)[i]}))});g.status='playing';return g;}
function tick(g,inputs,n=1){for(let i=0;i<n;i++)E.step(g,inputs,1/60);}
test('Seven playable beasts plus the boss golem, three arenas',()=>{assert.equal(Object.keys(E.CHARACTERS).length,8);assert.equal(E.CHARACTERS['crown-golem'].playable,false);assert.equal(E.normalizeProfile({character:'crown-golem'}).character,'frost');assert.equal(Object.keys(E.ARENAS).length,3);for(const character of ['fluffy','water-rat']){const p=E.normalizeProfile({id:'saved',character,gems:35,xp:60});assert.equal(p.character,character);assert.equal(p.gems,35);assert.equal(p.evolution,1);}});
test('Malformed profiles and unowned equipment are clamped',()=>{const p=E.normalizeProfile({id:'../x',name:'<script>',character:'__proto__',gems:-99,xp:Infinity,energy:9e12,upgrades:{attack:99,armor:-3},equipment:{weapon:'nova-gauntlet'}});assert.equal(p.character,'frost');assert.equal(p.gems,0);assert.equal(p.upgrades.attack,3);assert.equal(p.upgrades.armor,0);assert.equal(p.equipment.weapon,'training-claws');assert.equal(p.energy,1000);assert(!p.name.includes('<'));});
test('Upgrade costs, limits and equipment purchases',()=>{let p=E.normalizeProfile({id:'shop',gems:200});for(let i=0;i<3;i++){const r=E.buyUpgrade(p,'attack');assert(r.ok);p=r.profile;}assert.equal(p.gems,105);assert.equal(E.buyUpgrade(p,'attack').ok,false);let r=E.buyEquipment(p,'nova-gauntlet');assert(r.ok);assert.equal(r.profile.equipment.weapon,'nova-gauntlet');assert.equal(r.profile.gems,45);assert.equal(E.buyEquipment(r.profile,'nova-gauntlet').profile.gems,45);assert.equal(E.equipItem(p,'guardian-shell').ok,false);});
test('Rewards are idempotent and earned XP evolves',()=>{let p=E.normalizeProfile({id:'reward',xp:45});let r=E.grantReward(p,{id:'one',gems:10,xp:20,energy:15});assert(r.ok);p=r.profile;assert.equal(p.evolution,1);r=E.grantReward(p,{id:'one',gems:10,xp:20,energy:15});assert(r.duplicate);assert.equal(r.profile.gems,10);});
test('No offline earnings from elapsed time alone',()=>{const g=game('practice',1);tick(g,{},7200);assert.deepEqual(g.rewards,[]);assert.equal(g.players[0].charges,0);});
test('Held attacks obey cooldown and block reduces damage',()=>{const g=game();g.players[0].x=500;g.players[1].x=560;tick(g,{p0:{punch:true}});const hp=g.players[1].hp;tick(g,{p0:{punch:true}});assert.equal(g.players[1].hp,hp);const b=game();b.players[0].x=500;b.players[1].x=560;tick(b,{p0:{punch:true},p1:{block:true}});assert(b.players[1].hp>hp);});
test('Simultaneous final blows draw',()=>{const g=game();g.players[0].x=500;g.players[1].x=560;for(const p of g.players)p.hp=1;tick(g,{p0:{punch:true},p1:{punch:true}});assert.equal(g.status,'ended');assert.equal(g.winnerId,'draw');assert.equal(g.rewards.length,0);});
test('Three-player FFA continues until last living',()=>{const g=game('duel',3);g.players[0].x=300;g.players[1].x=350;g.players[2].x=1100;g.players[1].hp=1;tick(g,{p0:{punch:true}});assert.equal(g.status,'playing');g.players[0].hp=1;g.players[2].x=350;tick(g,{p2:{punch:true}});assert.equal(g.status,'ended');assert.equal(g.winnerId,'p2');});
test('Pause freezes physical state and rewards',()=>{const g=game();g.status='paused';const before=JSON.stringify(E.snapshot(g));tick(g,{p0:{punch:true,right:true,jump:true}},60);assert.equal(JSON.stringify(E.snapshot(g)),before);});
test('Flight and dash remain bounded',()=>{const g=game();tick(g,{p0:{right:true,jump:true,dash:true}},60);const p=g.players[0];assert(p.energy<p.maxEnergy);tick(g,{p0:{right:true,jump:true,dash:true}},440);assert(p.x<=E.WIDTH-60);assert(p.y>=120);assert(p.energy>=0);assert(p.energy<=p.maxEnergy);});
test('Crown knockout has delay and clean respawn',()=>{const g=game('crown');g.players[0].x=500;g.players[1].x=560;g.players[1].hp=1;tick(g,{p0:{punch:true}});assert.equal(g.players[1].alive,false);tick(g,{},20);assert.equal(g.players[1].alive,false);tick(g,{},100);assert.equal(g.players[1].alive,true);assert.equal(g.players[1].hp,g.players[1].maxHp);});
test('Practice target is awarded once and fifth target earns reward',()=>{const g=game('practice',1);const p=g.players[0],t=g.targets[0];p.x=t.x-25;t.hp=1;tick(g,{p0:{punch:true}});assert.equal(p.charges,1);tick(g,{p0:{punch:true}},5);assert.equal(p.charges,1);tick(g,{},90);p.charges=4;t.hp=1;tick(g,{p0:{punch:true}});assert.equal(g.status,'ended');assert.equal(g.rewards[0].gems,5);const before=JSON.stringify(g.rewards);tick(g,{p0:{punch:true}},100);assert.equal(JSON.stringify(g.rewards),before);});
test('Quest guardian acts and winning earns quest rewards',()=>{const g=game('quest',1);assert(g.players[1].ai);const x=g.players[1].x;tick(g,{},60);assert.notEqual(g.players[1].x,x);g.players[0].x=500;g.players[1].x=560;g.players[1].hp=1;g.players[0].face=1;tick(g,{p0:{punch:true}});assert.equal(g.winnerId,'p0');assert.equal(g.rewards[0].gems,12);});
test('Every special starts its own move and twins follow-up lands',()=>{for(const character of Object.keys(E.CHARACTERS)){const g=game();g.players[0].character=character;g.players[0].x=500;g.players[1].x=560;tick(g,{p0:{special:true}});assert(g.players[0].cd.special>0);assert(g.effects.some(e=>e.type==='cast'&&e.style===E.MoveBook.get(character,'special').fx));}const g=game();g.players[0].character='twins';g.players[0].x=500;g.players[1].x=560;tick(g,{p0:{punch:true}});const hp=g.players[1].hp;tick(g,{},12);assert(g.players[1].hp<hp);});
test('Snapshot does not expose profile or alias cooldown data',()=>{const g=game();let s=E.snapshot(g);assert.equal(s.players[0].profile,undefined);s.players[0].cd.punch=100;assert.equal(g.players[0].cd.punch,0);});
async function network(){const app=createServer({port:0});await app.listen();const port=app.server.address().port;const url='ws://127.0.0.1:'+port;const clients=[];const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function connect(id){const ws=new WebSocket(url);clients.push(ws);ws.messages=[];ws.on('message',raw=>ws.messages.push(JSON.parse(raw)));await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});ws.send(JSON.stringify({type:'hello',profile:{id,name:id}}));await delay(60);return ws;}
const send=(ws,msg)=>ws.send(JSON.stringify(msg));const latest=ws=>ws.messages.filter(m=>m.type==='state').at(-1)?.state;
try{const health=await fetch('http://127.0.0.1:'+port+'/health').then(r=>r.json());assert(health.ok);const a=await connect('alpha'),b=await connect('beta'),c=await connect('gamma'),d=await connect('delta');assert.equal(a.messages.find(m=>m.type==='welcome').slot,0);assert.equal(c.messages.find(m=>m.type==='welcome').slot,2);assert.equal(d.messages.find(m=>m.type==='welcome').spectator,true);passed++;console.log('PASS WebSocket three players and fourth spectator');
const duplicate=await connect('alpha');assert(duplicate.messages.some(m=>m.type==='error'));assert.equal(app.getState().connectedIds.length,3);passed++;console.log('PASS Active duplicate profile cannot hijack');
send(a,{type:'configure',mode:'crown',arena:'forge',profile:{character:'fluffy'}});send(b,{type:'configure',profile:{character:'water-rat'}});await delay(70);assert.equal(latest(c).arena,'forge');assert.equal(latest(c).mode,'crown');assert.deepEqual(latest(c).players.slice(0,2).map(p=>p.character),['fluffy','water-rat']);send(a,{type:'control',action:'start'});await delay(70);const x=latest(a).players[0].x;send(a,{type:'input',seq:2,input:{right:true}});await delay(160);assert(latest(b).players[0].x>x);send(a,{type:'input',seq:1,input:{left:true}});await delay(70);assert.equal(latest(a).ackSeq.alpha,2);passed++;console.log('PASS Shared familiar selection, configuration, movement and stale input rejection');
send(a,{type:'input',seq:3,input:{super:true}});send(a,{type:'input',seq:4,input:{}});await delay(70);assert(latest(a).players[0].cd.super>0);passed++;console.log('PASS Press and release between server ticks keeps one attack');
send(a,{type:'control',action:'pause'});await delay(70);let paused=latest(b).players[0].x;await delay(80);assert.equal(latest(c).players[0].x,paused);send(a,{type:'control',action:'resume'});await delay(40);b.close();await delay(70);assert.equal(latest(a).status,'paused');const rejoin=await connect('beta');assert.equal(rejoin.messages.find(m=>m.type==='welcome').slot,1);assert.equal(app.getState().connectedIds.length,3);passed++;console.log('PASS Shared pause, disconnect and retained rejoin slot');
send(a,{type:'control',action:'reset',mode:'duel'});await delay(60);assert.equal(latest(c).status,'lobby');assert.equal(latest(c).mode,'duel');assert(latest(c).players.every(p=>p.hp===p.maxHp));passed++;console.log('PASS Clean network rematch');
send(a,{type:'control',action:'reset',mode:'duel'});await delay(60);send(a,{type:'configure',profile:{id:'alpha',name:'alpha',energy:500}});await delay(60);send(a,{type:'control',action:'reset',mode:'boss'});await delay(60);assert.equal(latest(c).mode,'boss');send(a,{type:'control',action:'start'});await delay(80);const bossState=latest(c);const boss=bossState.players.find(p=>p.boss);assert(boss&&boss.hp>700);assert.equal(bossState.players.length,4);passed++;console.log('PASS Network boss mode spawns Crown Golem for the team');
send(a,{type:'boost',id:'swift'});await delay(80);const boosts=latest(a).players.find(p=>p.id==='alpha').boosts;assert.equal(boosts.length,1);const spend=latest(a).spendEvents;assert(spend.some(e=>e.playerId==='alpha'&&e.boostId==='swift'));passed++;console.log('PASS Server-authoritative energy boost with spend receipt');
send(a,{type:'boost',id:'fury'});await delay(60);send(a,{type:'boost',id:'mend'});await delay(60);assert(latest(a).spendEvents.filter(e=>e.playerId==='alpha').length<=2);passed++;console.log('PASS Boost caps and duplicate spends stay bounded');
}finally{for(const ws of clients)ws.terminate();await app.close();}}
network().then(()=>console.log('ALL '+passed+' CHECKS PASSED')).catch(e=>{console.error(e);process.exitCode=1;});
