(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BeastGame=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const MoveBook=typeof module==='object'&&module.exports?require('./moves.js'):globalThis.BeastMoves;
const Combat=typeof module==='object'&&module.exports?require('./combat.js'):globalThis.BeastCombat;
const WIDTH=1800,VIEW_WIDTH=1200,HEIGHT=600,GROUND=480,DEPTH_MIN=-150,DEPTH_MAX=150;
const CHARACTERS={
 frost:{id:'frost',name:'Frost',description:'An ice guardian. Freeze a rival with Crystal Storm.',special:'Crystal Storm',color:'#71dcff'},
 ember:{id:'ember',name:'Ember',description:'A flame guardian. Unleash a powerful fire burst.',special:'Flame Burst',color:'#ffab69'},
 moss:{id:'moss',name:'Moss',description:'A forest guardian. Heal while striking nearby rivals.',special:'Life Bloom',color:'#8eda99'},
 volt:{id:'volt',name:'Volt',description:'A thunder guardian. Blink forward with a lightning strike.',special:'Thunder Rush',color:'#d6b1ff'},
 twins:{id:'twins',name:'Pip & Pebble',description:'Two small beasts, one player. Chain punches into a twin combo.',special:'Twin Comet',color:'#ffdc86'},
 fluffy:{id:'fluffy',name:'Fluffy',description:"Leo's AI Familiar · Fire Dragon / Leo 的火龙使魔. A 2D arena adaptation with a blazing burst.",special:'Dragon Flame / 龙焰',color:'#ff9962'},
 'water-rat':{id:'water-rat',name:'壬子·水鼠 / Water Rat',description:"Nathan's AI Familiar / Nathan 的水鼠使魔. A 2D arena adaptation with a chilling tidal pulse.",special:'Tidal Pulse / 水潮',color:'#85dff2'}
};
for(const [id,c] of Object.entries(CHARACTERS)){c.description=MoveBook.styles[id].description;c.special=MoveBook.get(id,'special').label;c.role=MoveBook.styles[id].role;c.title=MoveBook.styles[id].title;}
const ARENAS={moon:{id:'moon',name:'Moon Sanctuary',description:'A quiet arena under a silver moon.'},forge:{id:'forge',name:'Ember Forge',description:'A glowing technology forge.'},grove:{id:'grove',name:'Ancient Grove',description:'A forest of giant roots and crystals.'}};
const UPGRADES={attack:{id:'attack',name:'Power amplifier',description:'+8% attack per level.',costs:[15,30,50],maxLevel:3},armor:{id:'armor',name:'Shield plating',description:'+8 maximum HP and 3% damage resistance per level.',costs:[15,30,50],maxLevel:3},energy:{id:'energy',name:'Flight capacitor',description:'+15 flight energy per level.',costs:[15,30,50],maxLevel:3}};
const EQUIPMENT={
 'training-claws':{id:'training-claws',name:'Training Claws',slot:'weapon',cost:0,description:'+1 attack.',stats:{attack:1}},
 'crystal-claws':{id:'crystal-claws',name:'Crystal Claws',slot:'weapon',cost:25,description:'+4 attack.',stats:{attack:4}},
 'nova-gauntlet':{id:'nova-gauntlet',name:'Nova Gauntlet',slot:'weapon',cost:60,description:'+7 attack.',stats:{attack:7}},
 'light-hide':{id:'light-hide',name:'Light Hide',slot:'armor',cost:0,description:'+4 maximum HP.',stats:{hp:4}},
 'crystal-vest':{id:'crystal-vest',name:'Crystal Vest',slot:'armor',cost:25,description:'+14 maximum HP and 4% resistance.',stats:{hp:14,resist:.04}},
 'guardian-shell':{id:'guardian-shell',name:'Guardian Shell',slot:'armor',cost:60,description:'+25 maximum HP and 8% resistance.',stats:{hp:25,resist:.08}},
 'flight-core':{id:'flight-core',name:'Flight Core',slot:'tool',cost:0,description:'+10 flight energy.',stats:{energy:10}},
 'wing-booster':{id:'wing-booster',name:'Wing Booster',slot:'tool',cost:25,description:'+30 flight energy.',stats:{energy:30}},
 'phase-compass':{id:'phase-compass',name:'Phase Compass',slot:'tool',cost:45,description:'+20 flight energy and 15% faster blink recovery.',stats:{energy:20,dash:.85}}
};
const DEFAULT_EQUIPMENT={weapon:'training-claws',armor:'light-hide',tool:'flight-core'};
const MOVES={punch:{cooldown:.34,damage:8,range:96},kick:{cooldown:.68,damage:13,range:140},spin:{cooldown:2.4,damage:17,range:155},dash:{cooldown:2.7,damage:0,range:0},super:{cooldown:3.8,damage:22,range:410},block:{cooldown:0},special:{cooldown:5.5,damage:20,range:210}};
const INPUT_KEYS=['left','right','up','down','jump','punch','kick','spin','dash','super','block','special'];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):min));
const integer=(v,min,max)=>Math.floor(clamp(v,min,max));
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const uid=()=> 'round-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12);
function normalizeProfile(raw){raw=raw&&typeof raw==='object'?raw:{};const upgrades={};for(const id of Object.keys(UPGRADES))upgrades[id]=integer(raw.upgrades&&raw.upgrades[id],0,3);
 const owned=[...new Set([...Object.values(DEFAULT_EQUIPMENT),...(Array.isArray(raw.ownedEquipment)?raw.ownedEquipment:[]).filter(id=>typeof id==='string'&&own(EQUIPMENT,id))])];
 const equipment={};for(const slot of Object.keys(DEFAULT_EQUIPMENT)){const id=raw.equipment&&raw.equipment[slot];equipment[slot]=typeof id==='string'&&own(EQUIPMENT,id)&&EQUIPMENT[id].slot===slot&&owned.includes(id)?id:DEFAULT_EQUIPMENT[slot];}
 const id=typeof raw.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(raw.id)?raw.id:'beast-'+Math.random().toString(36).slice(2,14);
 const xp=integer(raw.xp,0,100000),evolution=xp>=300?3:xp>=140?2:xp>=50?1:0;
 const boost=['rush','guard','surge'].includes(raw.boost)?raw.boost:'';return {id,name:(typeof raw.name==='string'?raw.name:'Beast').replace(/[<>\x00-\x1f]/g,'').trim().slice(0,24)||'Beast',character:typeof raw.character==='string'&&own(CHARACTERS,raw.character)?raw.character:'frost',gems:integer(raw.gems,0,100000),xp,energy:integer(raw.energy,0,9999),boost,upgrades,equipment,ownedEquipment:owned,rewardIds:[...new Set((Array.isArray(raw.rewardIds)?raw.rewardIds:[]).filter(v=>typeof v==='string'&&v.length<=140))].slice(0,2048),evolution};
}
function buyUpgrade(raw,id){let profile=normalizeProfile(raw);if(!own(UPGRADES,id))return{ok:false,profile,error:'Unknown upgrade'};const level=profile.upgrades[id],cost=UPGRADES[id].costs[level];if(level>=3)return{ok:false,profile,error:'Maximum level reached'};if(profile.gems<cost)return{ok:false,profile,error:'Earn more gems in a round or offline practice.'};profile.gems-=cost;profile.upgrades[id]++;return{ok:true,profile};}
function buyEquipment(raw,id){let profile=normalizeProfile(raw);if(!own(EQUIPMENT,id))return{ok:false,profile,error:'Unknown equipment'};const item=EQUIPMENT[id];if(!profile.ownedEquipment.includes(id)){if(profile.gems<item.cost)return{ok:false,profile,error:'Earn more gems first.'};profile.gems-=item.cost;profile.ownedEquipment.push(id);}profile.equipment[item.slot]=id;return{ok:true,profile};}
function equipItem(raw,id){const profile=normalizeProfile(raw);if(!own(EQUIPMENT,id)||!profile.ownedEquipment.includes(id))return{ok:false,profile,error:'Purchase this item first.'};profile.equipment[EQUIPMENT[id].slot]=id;return{ok:true,profile};}
function grantReward(raw,reward){const profile=normalizeProfile(raw);if(!reward||typeof reward.id!=='string'||!reward.id||reward.id.length>140)return{ok:false,profile,error:'Invalid reward'};if(profile.rewardIds.includes(reward.id))return{ok:true,profile,duplicate:true};if(profile.rewardIds.length>=2048)return{ok:false,profile,error:'Reward record full. Keep this profile backed up.'};profile.rewardIds.push(reward.id);profile.gems=integer(profile.gems+integer(reward.gems,0,100),0,100000);profile.xp=integer(profile.xp+integer(reward.xp,0,100),0,100000);profile.energy=integer(profile.energy+integer(reward.energy,0,100),0,9999);return{ok:true,profile:normalizeProfile(profile),duplicate:false};}
function inputOf(raw){const result={};for(let k of INPUT_KEYS)result[k]=!!raw&&raw[k]===true;return result;}
function playerOf(spec,index,total){spec=spec||{};const profile=normalizeProfile(spec.profile||spec);const character=own(CHARACTERS,spec.character)?spec.character:profile.character;const equipment=Object.values(profile.equipment).map(id=>EQUIPMENT[id].stats);const stat=k=>equipment.reduce((n,e)=>n+(e[k]||0),0);const boss=spec.boss===true,team=spec.team||((boss||spec.ai&&spec.id==='apex')?'boss':'heroes');let maxHp=100+profile.upgrades.armor*8+profile.evolution*5+stat('hp'),maxEnergy=100+profile.upgrades.energy*15+stat('energy')+Math.min(20,Math.floor(profile.energy/25));if(profile.boost==='guard')maxHp+=30;if(boss)maxHp=520;
 const spawnX=boss?WIDTH*.72:(total===1?WIDTH*.35:220+index*(WIDTH-440)/Math.max(1,total-1)),spawnDepth=0;return {id:String(spec.id||profile.id),name:String(spec.name||profile.name||CHARACTERS[character].name).slice(0,24),character,x:spawnX,y:GROUND,depth:spawnDepth,vx:0,vy:0,vdepth:0,face:index===total-1&&total>1?-1:1,hp:maxHp,maxHp,energy:maxEnergy,maxEnergy,alive:true,cd:{punch:0,kick:0,spin:0,dash:0,super:0,block:0,special:0},action:'idle',actionTime:0,charges:0,xp:profile.xp,evolution:boss?3:profile.evolution,flash:0,respawn:0,invulnerable:0,frozen:0,blocking:false,combo:0,comboTime:0,ai:spec.ai===true,boss,team,profile,attackBonus:stat('attack')+(profile.boost==='surge'?4:0)+(boss?10:0),attackMultiplier:(1+profile.upgrades.attack*.08+profile.evolution*.07)*(profile.boost==='surge'?1.08:1)*(boss?1.18:1),resistance:Math.min(.5,profile.upgrades.armor*.03+stat('resist')+(boss?.12:0)),dashMultiplier:equipment.find(e=>e.dash)?.dash||1,sessionSpeed:profile.boost==='rush'?1.18:1,sessionCooldown:profile.boost==='surge'?.85:1,jumpWas:false};
}
function createGame(options){options=options||{};let mode=['duel','crown','practice','quest','boss'].includes(options.mode)?options.mode:'duel';let specs=Array.isArray(options.players)?options.players.slice(0,mode==='practice'||mode==='quest'?1:3):[];if(!specs.length)specs=[{id:'local',name:'You',character:'frost'}];specs=specs.map((p,i)=>({...p,team:(mode==='boss'||mode==='quest')?'heroes':'player-'+i}));if(mode==='quest')specs.push({id:'guardian',name:'Forge Guardian',character:'ember',ai:true,team:'boss',profile:{id:'guardian',character:'ember'}});if(mode==='boss')specs.push({id:'apex',name:'Apex Fluffy',character:'fluffy',ai:true,boss:true,team:'boss',profile:{id:'apex',character:'fluffy',xp:300}});
 const g={mode,status:'lobby',arena:own(ARENAS,options.arena)?options.arena:'moon',tick:0,time:0,roundId:typeof options.roundId==='string'?options.roundId.slice(0,48):uid(),players:specs.map((p,i)=>playerOf(p,i,specs.length)),targets:[],effects:[],winnerId:null,reason:mode==='boss'?'Team up and defeat Apex Fluffy.':'Choose your beast, then start a round.',rewards:[],targetSerial:0};
 if(mode==='practice'||mode==='crown')for(let i=0;i<5;i++)g.targets.push({id:'target-'+(++g.targetSerial),x:180+i*330,y:GROUND,depth:(i%3-1)*85,hp:26,maxHp:26,respawn:0,flash:0});return g;
}
function effect(g,type,x,y,player,extra){g.effects.push({id:g.tick+'-'+g.effects.length,type,x,y,depth:player.depth||0,life:.35,color:CHARACTERS[player.character].color,playerId:player.id,face:player.face,...extra});if(g.effects.length>50)g.effects.shift();}
function aiInput(g,p){const rivals=g.players.filter(o=>o.alive&&o.id!==p.id&&o.team!==p.team);const opponent=rivals.sort((a,b)=>Math.hypot(a.x-p.x,(a.depth||0)-(p.depth||0))-Math.hypot(b.x-p.x,(b.depth||0)-(p.depth||0)))[0];if(!opponent)return{};const dx=opponent.x-p.x,dd=(opponent.depth||0)-(p.depth||0),near=Math.abs(dx)<145&&Math.abs(dd)<70,boss=p.boss===true;return {left:dx<-85,right:dx>85,up:dd<-28,down:dd>28,punch:near&&g.tick%(boss?58:90)<30,kick:Math.abs(dx)<175&&Math.abs(dd)<85&&g.tick%(boss?94:130)<24,super:Math.abs(dx)<440&&Math.abs(dd)<95&&g.tick%(boss?190:300)<16,jump:!boss&&opponent.y<p.y-85&&g.tick%180<65,block:near&&g.tick%210>165,special:Math.abs(dx)<240&&Math.abs(dd)<100&&g.tick%(boss?250:420)<9};}
function finish(g,winnerId,reason){g.status='ended';g.winnerId=winnerId;g.reason=reason;if(g.mode==='boss'&&winnerId==='heroes'){g.rewards=g.players.filter(p=>!p.ai).map(p=>({id:g.roundId+':'+p.id,playerId:p.id,gems:18,xp:35,energy:24}));return;}if(winnerId&&winnerId!=='draw'){const p=g.players.find(p=>p.id===winnerId);if(p&&!p.ai){const amounts=g.mode==='practice'?{gems:5,xp:12,energy:8}:g.mode==='quest'?{gems:12,xp:25,energy:15}:{gems:10,xp:20,energy:12};g.rewards=[{id:g.roundId+':'+p.id,playerId:p.id,...amounts}];}}}
function step(g,inputs,dt){return Combat.tick(g,inputs,clamp(dt==null?1/60:dt,0,1/30),{effect,aiInput,finish});}
function snapshot(g){return {mode:g.mode,status:g.status,arena:g.arena,tick:g.tick,time:g.time,roundId:g.roundId,players:g.players.map(p=>{const {profile,attackBonus,attackMultiplier,resistance,dashMultiplier,jumpWas,...visible}=p;return {...visible,cd:{...p.cd},equipment:{...p.profile.equipment}};}),targets:g.targets.map(t=>({...t})),effects:g.effects.map(e=>({...e})),projectiles:(g.projectiles||[]).map(({hit,...b})=>({...b})),zones:(g.zones||[]).map(z=>({...z})),winnerId:g.winnerId,reason:g.reason,rewards:g.rewards.map(r=>({...r}))};}
return {WIDTH,VIEW_WIDTH,HEIGHT,GROUND,DEPTH_MIN,DEPTH_MAX,CHARACTERS,ARENAS,MoveBook,UPGRADES,EQUIPMENT,MOVES,INPUT_KEYS,normalizeProfile,buyUpgrade,buyEquipment,equipItem,grantReward,inputOf,createGame,step,snapshot};
});
