(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BeastGame=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const MoveBook=typeof module==='object'&&module.exports?require('./moves.js'):globalThis.BeastMoves;
const Combat=typeof module==='object'&&module.exports?require('./combat.js'):globalThis.BeastCombat;
const WIDTH=1920,VIEW_WIDTH=1200,HEIGHT=600,GROUND=480,DEPTH=240,GROUND_BACK=408;
const BUILD={id:'glm53',label:'GLM 5.3 UPGRADE',date:'2026-09-19',baseline:'V4 20260919'};
const CHARACTERS={
 frost:{id:'frost',name:'Frost',description:'An ice guardian. Freeze a rival with Crystal Storm.',special:'Crystal Storm',color:'#71dcff'},
 ember:{id:'ember',name:'Ember',description:'A flame guardian. Unleash a powerful fire burst.',special:'Flame Burst',color:'#ffab69'},
 moss:{id:'moss',name:'Moss',description:'A forest guardian. Heal while striking nearby rivals.',special:'Life Bloom',color:'#8eda99'},
 volt:{id:'volt',name:'Volt',description:'A thunder guardian. Blink forward with a lightning strike.',special:'Thunder Rush',color:'#d6b1ff'},
 twins:{id:'twins',name:'Pip & Pebble',description:'Two small beasts, one player. Chain punches into a twin combo.',special:'Twin Comet',color:'#ffdc86'},
 fluffy:{id:'fluffy',name:'Fluffy',description:"Leo's AI Familiar · Fire Dragon / Leo 的火龙使魔. A 2D arena adaptation with a blazing burst.",special:'Dragon Flame / 龙焰',color:'#ff9962'},
 'crown-golem':{id:'crown-golem',name:'Crown Golem',description:'An ancient stone giant crowned in crystal. Telegraphed slams, sweeping arms and crystal rain.',special:'Crown Fall',color:'#cbb7ff',playable:false},'water-rat':{id:'water-rat',name:'壬子·水鼠 / Water Rat',description:"Nathan's AI Familiar / Nathan 的水鼠使魔. A 2D arena adaptation with a chilling tidal pulse.",special:'Tidal Pulse / 水潮',color:'#85dff2'}
};
for(const [id,c] of Object.entries(CHARACTERS)){c.description=MoveBook.styles[id].description;c.special=MoveBook.get(id,'special').label;c.role=MoveBook.styles[id].role;c.title=MoveBook.styles[id].title;}
const ARENAS={moon:{id:'moon',name:'Moon Sanctuary',description:'A quiet arena under a silver moon.'},forge:{id:'forge',name:'Ember Forge',description:'A glowing technology forge.'},grove:{id:'grove',name:'Ancient Grove',description:'A forest of giant roots and crystals.'}};
const UPGRADES={attack:{id:'attack',name:'Power amplifier',description:'+8% attack per level.',costs:[15,30,50],maxLevel:3},armor:{id:'armor',name:'Shield plating',description:'+8 maximum HP and 3% damage resistance per level.',costs:[15,30,50],maxLevel:3},energy:{id:'energy',name:'Flight capacitor',description:'+15 flight energy per level.',costs:[15,30,50],maxLevel:3}};
const EQUIPMENT={
 'training-claws':{id:'training-claws',name:'Training Claws',slot:'weapon',cost:0,description:'+1 attack.',stats:{attack:1}},
 'crystal-claws':{id:'crystal-claws',name:'Crystal Claws',slot:'weapon',cost:25,description:'+4 attack.',stats:{attack:4}},
 'nova-gauntlet':{id:'nova-gauntlet',name:'Nova Gauntlet',slot:'weapon',cost:60,description:'+7 attack.',stats:{attack:7}},
 'light-hide':{id:'light-hide',name:'Light Hide',slot:'armor',cost:0,description:'+4 maximum HP.',stats:{hp:4}},
 'crystal-vest':{id:'crystal-vest',name:'Crystal Vest',slot:'armor',cost:25,description:'+14 maximum HP and 4% resistance.',stats:{hp:14,resist:.04}},
 'guardian-shell':{id:'guardian-shell',name:'Guardian Shell',slot:'armor',cost:60,description:'+25 maximum HP and 8% resistance.',stats:{hp:25,resist:.08}},
 'flight-core':{id:'flight-core',name:'Flight Core',slot:'tool',cost:0,description:'+10 flight energy.',stats:{energy:10}},
 'wing-booster':{id:'wing-booster',name:'Wing Booster',slot:'tool',cost:25,description:'+30 flight energy.',stats:{energy:30}},
 'phase-compass':{id:'phase-compass',name:'Phase Compass',slot:'tool',cost:45,description:'+20 flight energy and 15% faster blink recovery.',stats:{energy:20,dash:.85}}
};
const DEFAULT_EQUIPMENT={weapon:'training-claws',armor:'light-hide',tool:'flight-core'};
const MOVES={punch:{cooldown:.34,damage:8,range:96},kick:{cooldown:.68,damage:13,range:140},spin:{cooldown:2.4,damage:17,range:155},dash:{cooldown:2.7,damage:0,range:0},super:{cooldown:3.8,damage:22,range:410},block:{cooldown:0},special:{cooldown:5.5,damage:20,range:210}};
const BOOSTS={swift:{id:'swift',name:'Swift Surge',icon:'»',cost:40,duration:18,description:'+32% move speed for 18s.'},rush:{id:'rush',name:'Cool Rush',icon:'◔',cost:50,duration:15,description:'Cooldowns recover 55% faster for 15s.'},aegis:{id:'aegis',name:'Aegis Shell',icon:'◒',cost:45,duration:0,description:'+34 shield now; fades like a normal shield.'},mend:{id:'mend',name:'Mend Bloom',icon:'✚',cost:45,duration:6,description:'Regenerate 7 HP per second for 6s.'},fury:{id:'fury',name:'Focus Fury',icon:'✦',cost:70,duration:12,description:'+30% damage for 12s.'}};
const INPUT_KEYS=['left','right','up','down','jump','punch','kick','spin','dash','super','block','special'];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):min));
const groundOf=z=>GROUND_BACK+clamp(z,0,DEPTH)*.6;
const PLAYABLE=id=>own(CHARACTERS,id)&&CHARACTERS[id].playable!==false;
const integer=(v,min,max)=>Math.floor(clamp(v,min,max));
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const uid=()=> 'round-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12);
function normalizeProfile(raw){raw=raw&&typeof raw==='object'?raw:{};const upgrades={};for(const id of Object.keys(UPGRADES))upgrades[id]=integer(raw.upgrades&&raw.upgrades[id],0,3);
 const owned=[...new Set([...Object.values(DEFAULT_EQUIPMENT),...(Array.isArray(raw.ownedEquipment)?raw.ownedEquipment:[]).filter(id=>typeof id==='string'&&own(EQUIPMENT,id))])];
 const equipment={};for(const slot of Object.keys(DEFAULT_EQUIPMENT)){const id=raw.equipment&&raw.equipment[slot];equipment[slot]=typeof id==='string'&&own(EQUIPMENT,id)&&EQUIPMENT[id].slot===slot&&owned.includes(id)?id:DEFAULT_EQUIPMENT[slot];}
 const id=typeof raw.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(raw.id)?raw.id:'beast-'+Math.random().toString(36).slice(2,14);
 const xp=integer(raw.xp,0,100000),evolution=xp>=300?3:xp>=140?2:xp>=50?1:0;
 return {id,name:(typeof raw.name==='string'?raw.name:'Beast').replace(/[<>\x00-\x1f]/g,'').trim().slice(0,24)||'Beast',character:typeof raw.character==='string'&&PLAYABLE(raw.character)?raw.character:'frost',gems:integer(raw.gems,0,100000),xp,energy:integer(raw.energy,0,1000),upgrades,equipment,ownedEquipment:owned,rewardIds:[...new Set((Array.isArray(raw.rewardIds)?raw.rewardIds:[]).filter(v=>typeof v==='string'&&v.length<=140))].slice(0,2048),evolution};
}
function buyUpgrade(raw,id){let profile=normalizeProfile(raw);if(!own(UPGRADES,id))return{ok:false,profile,error:'Unknown upgrade'};const level=profile.upgrades[id],cost=UPGRADES[id].costs[level];if(level>=3)return{ok:false,profile,error:'Maximum level reached'};if(profile.gems<cost)return{ok:false,profile,error:'Earn more gems in a round or offline practice.'};profile.gems-=cost;profile.upgrades[id]++;return{ok:true,profile};}
function buyEquipment(raw,id){let profile=normalizeProfile(raw);if(!own(EQUIPMENT,id))return{ok:false,profile,error:'Unknown equipment'};const item=EQUIPMENT[id];if(!profile.ownedEquipment.includes(id)){if(profile.gems<item.cost)return{ok:false,profile,error:'Earn more gems first.'};profile.gems-=item.cost;profile.ownedEquipment.push(id);}profile.equipment[item.slot]=id;return{ok:true,profile};}
function equipItem(raw,id){const profile=normalizeProfile(raw);if(!own(EQUIPMENT,id)||!profile.ownedEquipment.includes(id))return{ok:false,profile,error:'Purchase this item first.'};profile.equipment[EQUIPMENT[id].slot]=id;return{ok:true,profile};}
function grantReward(raw,reward){const profile=normalizeProfile(raw);if(!reward||typeof reward.id!=='string'||!reward.id||reward.id.length>140)return{ok:false,profile,error:'Invalid reward'};if(profile.rewardIds.includes(reward.id))return{ok:true,profile,duplicate:true};if(profile.rewardIds.length>=2048)return{ok:false,profile,error:'Reward record full. Keep this profile backed up.'};profile.rewardIds.push(reward.id);profile.gems=integer(profile.gems+integer(reward.gems,0,100),0,100000);profile.xp=integer(profile.xp+integer(reward.xp,0,100),0,100000);profile.energy=integer(profile.energy+integer(reward.energy,0,100),0,1000);return{ok:true,profile:normalizeProfile(profile),duplicate:false};}
function inputOf(raw){const result={};for(let k of INPUT_KEYS)result[k]=!!raw&&raw[k]===true;return result;}
function playerOf(spec,index,total){spec=spec||{};const profile=normalizeProfile(spec.profile||spec);const character=own(CHARACTERS,spec.character)?spec.character:profile.character;const equipment=Object.values(profile.equipment).map(id=>EQUIPMENT[id].stats);const stat=k=>equipment.reduce((n,e)=>n+(e[k]||0),0);const boss=spec.boss===true,humans=Math.max(1,total-(boss?1:0));const maxHp=boss?720+240*humans:100+profile.upgrades.armor*8+profile.evolution*5+stat('hp'),maxEnergy=100+profile.upgrades.energy*15+stat('energy')+Math.min(20,Math.floor(profile.energy/25));
 return {id:String(spec.id||profile.id),name:String(spec.name||profile.name||CHARACTERS[character].name).slice(0,24),character,x:total===1?420:380+index*((WIDTH-760)/Math.max(1,total-1)),y:GROUND,z:120,vx:0,vy:0,face:index===total-1&&total>1?-1:1,hp:maxHp,maxHp,energy:maxEnergy,maxEnergy,alive:true,cd:{punch:0,kick:0,spin:0,dash:0,super:0,block:0,special:0},action:'idle',actionTime:0,charges:0,xp:profile.xp,evolution:profile.evolution,flash:0,respawn:0,invulnerable:0,frozen:0,blocking:false,combo:0,comboTime:0,ai:spec.ai===true,boss,revivesLeft:boss?0:1,boosts:[],phase:1,weak:0,pattern:'stalk',patternTimer:1.2,chargeVX:0,profile,attackBonus:stat('attack'),attackMultiplier:(boss?1.5:1)*(1+profile.upgrades.attack*.08+profile.evolution*.07),resistance:Math.min(.4,profile.upgrades.armor*.03+stat('resist')),dashMultiplier:equipment.find(e=>e.dash)?.dash||1,jumpWas:false};
}
function createGame(options){options=options||{};let mode=['duel','crown','boss','practice','quest'].includes(options.mode)?options.mode:'duel';let specs=Array.isArray(options.players)?options.players.slice(0,mode==='practice'||mode==='quest'?1:3):[];if(!specs.length)specs=[{id:'local',name:'You',character:'frost'}];if(mode==='quest')specs.push({id:'guardian',name:'Forge Guardian',character:'ember',ai:true,profile:{id:'guardian',character:'ember'}});if(mode==='boss')specs.push({id:'boss',name:'Crown Golem',character:'crown-golem',ai:true,boss:true,profile:{id:'boss',character:'crown-golem'}});
 const g={mode,status:'lobby',arena:own(ARENAS,options.arena)?options.arena:'moon',tick:0,time:0,width:WIDTH,roundId:typeof options.roundId==='string'?options.roundId.slice(0,48):uid(),players:specs.map((p,i)=>playerOf(p,i,specs.length)),targets:[],effects:[],winnerId:null,reason:'Choose your beast, then start a round.',rewards:[],targetSerial:0};
 if(mode==='practice'||mode==='crown')for(let i=0;i<5;i++)g.targets.push({id:'target-'+(++g.targetSerial),x:200+i*360,z:[70,150,95,170,120][i],y:0,hp:26,maxHp:26,respawn:0,flash:0});for(const t of g.targets)t.y=groundOf(t.z);return g;
}
function effect(g,type,x,y,player,extra){g.effects.push({id:g.tick+'-'+g.effects.length,type,x,y,life:.35,color:CHARACTERS[player.character].color,playerId:player.id,face:player.face,...extra});if(g.effects.length>50)g.effects.shift();}
function aiInput(g,p){const opponent=g.players.find(o=>!o.ai&&o.alive);if(!opponent)return{};const dx=opponent.x-p.x,dz=opponent.z-p.z,dy=opponent.y-groundOf(p.z),near=Math.abs(dx)<120&&Math.abs(dz)<74;return {left:dx<-75,right:dx>75,up:dz<-30,down:dz>30,punch:near&&g.tick%90<45,kick:Math.abs(dx)<145&&g.tick%130<25,super:Math.abs(dx)<380&&g.tick%300<15,jump:dy<-85&&g.tick%180<65,block:near&&g.tick%210>160,special:Math.abs(dx)<190&&g.tick%420<5};}
function finish(g,winnerId,reason){if(g.status==='ended')return;g.status='ended';g.winnerId=winnerId;g.reason=reason;if(g.mode==='boss'&&winnerId==='team'){g.rewards=g.players.filter(p=>!p.ai&&!p.boss).map(p=>({id:g.roundId+':'+p.id,playerId:p.id,gems:14,xp:30,energy:18}));return;}if(winnerId&&winnerId!=='draw'){const p=g.players.find(p=>p.id===winnerId);if(p&&!p.ai){const amounts=g.mode==='practice'?{gems:5,xp:12,energy:8}:g.mode==='quest'?{gems:12,xp:25,energy:15}:{gems:10,xp:20,energy:12};g.rewards=[{id:g.roundId+':'+p.id,playerId:p.id,...amounts}];}}}
function step(g,inputs,dt){return Combat.tick(g,inputs,clamp(dt==null?1/60:dt,0,1/30),{effect,aiInput,finish,groundOf});}
function dangerAt(g,x,z){const zones=(g&&g.zones)||[];for(const zn of zones){const active=zn.wait>-0.05&&zn.life>0;if(!active)continue;const depthBand=(zn.range||0)*.42+40;if(Math.abs(x-zn.x)<=(zn.range||0)&&Math.abs(z-(zn.z??120))<=depthBand)return true;}return false;}
function applyBoost(g,playerId,boostId){const p=g.players.find(p=>p.id===playerId);if(!p||p.boss)return{ok:false,error:'No fighter'};if(g.status!=='playing')return{ok:false,error:'Boosts work during a live round'};const b=own(BOOSTS,boostId)?BOOSTS[boostId]:null;if(!b)return{ok:false,error:'Unknown boost'};if(p.boosts.length>=2)return{ok:false,error:'Two boosts already active'};if(b.duration&&p.boosts.some(x=>x.id===boostId))return{ok:false,error:'Already running'};p.boosts.push({id:boostId,until:g.time+b.duration});if(boostId==='aegis'){p.shield=Math.max(p.shield||0,34);p.shieldTime=Math.max(p.shieldTime||0,4);}effect(g,'cast',p.x,p.y-70,p,{style:'boost-'+boostId,life:.5,maxLife:.5});return{ok:true,spent:b.cost};}
function snapshot(g){return {mode:g.mode,status:g.status,arena:g.arena,tick:g.tick,time:g.time,roundId:g.roundId,players:g.players.map(p=>{const {profile,attackBonus,attackMultiplier,resistance,dashMultiplier,jumpWas,...visible}=p;return {...visible,cd:{...p.cd},equipment:{...p.profile.equipment}};}),targets:g.targets.map(t=>({...t})),effects:g.effects.map(e=>({...e})),projectiles:(g.projectiles||[]).map(({hit,...b})=>({...b})),zones:(g.zones||[]).map(z=>({...z})),winnerId:g.winnerId,reason:g.reason,rewards:g.rewards.map(r=>({...r}))};}
return {WIDTH,VIEW_WIDTH,HEIGHT,GROUND,DEPTH,groundOf,BOOSTS,CHARACTERS,ARENAS,MoveBook,UPGRADES,EQUIPMENT,MOVES,INPUT_KEYS,BUILD,BOSS_TELLS:Combat.BOSS_TELLS,BOSS_ACTIONS:Combat.BOSS_ACTIONS,bossReadout:Combat.bossReadout,dangerAt,normalizeProfile,buyUpgrade,buyEquipment,equipItem,grantReward,inputOf,createGame,step,applyBoost,snapshot};
});
