const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base='http://127.0.0.1:8765',results=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function post(route,data){const r=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return {status:r.status,data:await r.json()};}
async function until(fn,ms=3000){const end=Date.now()+ms;while(Date.now()<end){if(fn())return;await sleep(30);}throw Error('Timed out waiting for shared state');}
async function connect(c){c.abort=new AbortController();const r=await fetch(base+'/events?token='+encodeURIComponent(c.token),{signal:c.abort.signal});assert.equal(r.status,200);let pending='';c.read=(async()=>{try{for await(const chunk of r.body){pending+=Buffer.from(chunk).toString();let at;while((at=pending.indexOf('\n\n'))>=0){const event=pending.slice(0,at);pending=pending.slice(at+2);if(event.startsWith('data: '))c.state=JSON.parse(event.slice(6));}}}catch(e){if(e.name!=='AbortError')c.error=e.message;}})();}
(async()=>{let a,b,timer;try{
  const health=await (await fetch(base+'/health')).json();assert.equal(health.ok,true);results.push('Server health');
  a=(await post('/api/join',{})).data;b=(await post('/api/join',{})).data;assert(a.token&&b.token);assert.notEqual(a.slot,b.slot);a.input={};b.input={};await connect(a);await connect(b);
  timer=setInterval(()=>{for(const c of [a,b])post('/api/input',{token:c.token,input:c.input}).catch(()=>{});},120);
  await until(()=>a.state?.connected.every(Boolean)&&b.state?.connected.every(Boolean));assert.equal((await post('/api/join',{})).status,409);results.push('Two clients and third-player protection');
  await post('/api/control',{token:a.token,action:'rematch'});await post('/api/control',{token:a.token,action:'mode',mode:'duel'});assert.equal((await post('/api/control',{token:a.token,action:'start'})).status,200);await until(()=>a.state?.status==='playing');
  const initial=a.state.players[0].x;a.input={right:true};await until(()=>a.state.players[0].x>initial+65);a.input={};await sleep(170);assert(Math.abs(a.state.players[0].x-b.state.players[0].x)<20);results.push('Shared movement');
  await post('/api/control',{token:a.token,action:'pause'});await until(()=>a.state.status==='paused'&&b.state.status==='paused');const frozen=a.state.players[0].x;a.input={right:true,punch:true};await sleep(350);assert.equal(a.state.players[0].x,frozen);a.input={};results.push('Pause freezes both clients');
  await post('/api/control',{token:a.token,action:'resume'});a.input={right:true};b.input={left:true};await until(()=>a.state.players[1].x-a.state.players[0].x<70);a.input={punch:true,kick:true,spin:true,super:true};b.input={};await until(()=>a.state.status==='ended',15000);assert.equal(a.state.winner,b.state.winner);assert(a.state.players.some(p=>p.hp===0));results.push('Shared damage, knockout, and winner');
  a.input={};await post('/api/control',{token:a.token,action:'rematch'});await until(()=>a.state.status==='lobby');assert(a.state.players.every(p=>p.hp===100&&p.charges===0));results.push('Clean rematch');
  await post('/api/control',{token:a.token,action:'start'});b.abort.abort();await until(()=>a.state.status==='paused'&&!a.state.connected[b.slot]);const recovered=await post('/api/join',{token:b.token});assert.equal(recovered.data.slot,b.slot);await connect(b);await until(()=>a.state.connected.every(Boolean));await post('/api/control',{token:a.token,action:'resume'});await until(()=>a.state.status==='playing');results.push('Disconnect pause and same-slot rejoin');
  await post('/api/control',{token:a.token,action:'rematch'});await post('/api/control',{token:a.token,action:'mode',mode:'crown'});await until(()=>a.state.mode==='crown'&&a.state.targets.length>0);assert.equal(a.state.targets.length,b.state.targets.length);results.push('Shared Crown Hunt setup');
  await post('/api/control',{token:a.token,action:'mode',mode:'duel'});
}catch(e){results.push({failed:e.message});process.exitCode=1;}finally{if(timer)clearInterval(timer);for(const c of [a,b])if(c?.token){await post('/api/leave',{token:c.token}).catch(()=>{});c.abort?.abort();}fs.writeFileSync(path.join(__dirname,'network-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));}})();
