const {chromium}=require('playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--disable-gpu']});const context=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true});const page=await context.newPage(),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto('https://YOUR-HOST.YOUR-TAILNET.ts.net:8443/');await page.locator('.review-banner').click();await page.waitForSelector('.check-row');assert.equal(await page.locator('.check-row').count(),9);assert.equal(await page.locator('[name=decision]').inputValue(),'pending');assert((await page.locator('.check-row select').evaluateAll(ns=>ns.map(n=>n.value))).every(v=>v==='untested'));results.push('Lobby opens a bilingual review with nine untested checks and pending acceptance');
 await page.locator('[name=testers]').fill('QA reviewer');await page.locator('[name=device]').fill('Simulated iPad · Edge');await page.locator('[name=check_touch]').selectOption('fail');await page.locator('[name=note_touch]').fill('Holding fly | attack: observed delay');await page.locator('[name=issue]').fill('Example touch observation');await page.locator('[name=steps]').fill('1. Hold flight\n2. Press attack');await page.reload();assert.equal(await page.locator('[name=issue]').inputValue(),'Example touch observation');assert.equal(await page.locator('[name=check_touch]').inputValue(),'fail');results.push('Draft fields and results survive reload');
 const downloadPromise=page.waitForEvent('download');await page.locator('#exportMarkdown').click();const download=await downloadPromise;const exported=fs.readFileSync(await download.path(),'utf8');assert(exported.includes('试玩测评 / Playtest review'));assert(exported.includes('Holding fly \\| attack'));assert(exported.includes('Example touch observation'));results.push('Markdown exports bilingual labels and exact observations');
 const jsonPromise=page.waitForEvent('download');await page.locator('#exportJSON').click();const data=JSON.parse(fs.readFileSync(await(await jsonPromise).path(),'utf8'));assert.equal(data.fields.check_touch,'fail');assert.equal(data.fields.decision,'pending');results.push('JSON exports structured field data without changing teacher acceptance');
 await page.locator('#newSession').click();assert.equal(await page.locator('[name=issue]').inputValue(),'');await page.locator('summary').click();await page.locator('#history button').first().click();assert.equal(await page.locator('[name=issue]').inputValue(),'Example touch observation');results.push('New round preserves the previous draft and allows reopening it');
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForSelector('.check-row');assert.equal(await page.locator('[name=issue]').inputValue(),'Example touch observation');await page.locator('[name=observed]').fill('Saved while offline');await page.reload();assert.equal(await page.locator('[name=observed]').inputValue(),'Saved while offline');results.push('Form reopens fully offline and saves edits offline');
 await page.setViewportSize({width:768,height:1024});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(__dirname,'review-form.png')});results.push('iPad portrait form has no horizontal overflow');assert.deepEqual(errors,[]);
 }catch(e){results.push({failed:e.message});process.exitCode=1;}finally{await browser.close();fs.writeFileSync(path.join(__dirname,'review-results.json'),JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));}})();
