function setGameText(element,value){const raw=String(value);const text=window.__reviewLanguage?.translate(raw)??raw;if(element.textContent!==text)element.textContent=text;}
import * as THREE from './vendor/three.module.js';
import { installDisplay } from './display.js';
let screenSize = {width:innerWidth,height:innerHeight};
const $=id=>document.getElementById(id),roles=['fighter','mage','jet'],icons={fighter:'🥊',mage:'🔥',jet:'✈️'},colors={fighter:0xf6aa55,mage:0xc19aff,jet:0x70dceb},hex={fighter:'#ffba6b',mage:'#cda7ff',jet:'#83e9f4'},counter={armor:'fighter',magic:'mage',speed:'jet'},enemyColor={armor:0xd2a778,magic:0xa46bdf,speed:0xa4da49};
let selected='fighter',role=null,ws=null,state=null,isHost=false,lastEvent=0,yaw=0,first=false,muted=false,audio=null,toastUntil=0,connected=false;
const keys=new Set(),touch={x:0,z:0,attack:false,skill:false},heroMeshes=new Map(),enemyMeshes=new Map(),effects=[];
const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x8acfc8);
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x8acfc8,45,100);const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,160);scene.add(new THREE.HemisphereLight(0xf1ffdf,0x597861,2.5));const sun=new THREE.DirectionalLight(0xffe5b4,3);sun.position.set(-18,35,14);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.normalBias=.035;scene.add(sun);scene.add(sun.target);
const mats=new Map();function mat(color){if(!mats.has(color))mats.set(color,new THREE.MeshStandardMaterial({color,roughness:.85}));return mats.get(color);}
const cubeGeo=new THREE.BoxGeometry(1,1,1);function box(parent,color,x,y,z,w=1,h=1,d=1){const m=new THREE.Mesh(cubeGeo,mat(color));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
const terrain=new THREE.Group();scene.add(terrain);box(terrain,0x836446,0,-1.9,0,50,3,50);box(terrain,0x6fbe7f,0,-.32,0,50,.6,50);
const tile=new THREE.InstancedMesh(cubeGeo,mat(0xffffff),625),dummy=new THREE.Object3D();let ti=0;for(let x=-24;x<=24;x+=2)for(let z=-24;z<=24;z+=2){dummy.position.set(x,-.055,z);dummy.scale.set(1.97,.12,1.97);dummy.updateMatrix();tile.setMatrixAt(ti,dummy.matrix);tile.setColorAt(ti++,new THREE.Color([0x80b978,0x83c180,0x88c784,0x79b771][Math.floor(Math.random()*4)]));}tile.receiveShadow=true;terrain.add(tile);
for(let a=0;a<Math.PI*2;a+=.13){const x=Math.sin(a)*26,z=Math.cos(a)*26;box(terrain,0x658e70,x,.5,z,2,1.3,2);if(Math.random()>.5){box(terrain,0x567f60,x,1.5,z,1.6,1,1.6);}}
for(let i=0;i<38;i++){const a=i*2.3999,rr=29+(i%5)*2.5,x=Math.sin(a)*rr,z=Math.cos(a)*rr;const tree=new THREE.Group();tree.position.set(x,0,z);box(tree,0x805635,0,1.5,0,.8,3,.8);box(tree,[0x2f8265,0x478b59,0x388b76][i%3],0,4,0,3.6,3.2,3.6);box(tree,0x67a879,0,6,0,2.5,1.4,2.5);terrain.add(tree);}
for(let i=0;i<14;i++){const cloud=new THREE.Group();cloud.position.set(Math.sin(i*2.4)*43,16+(i%3)*3,Math.cos(i*2.4)*43);box(cloud,0xf9f6df,0,0,0,7,1.3,3);box(cloud,0xf9f6df,1,1,0,4,1.5,3);scene.add(cloud);}
for(const [i,r] of roles.entries()){const a=(i/3)*Math.PI*2,x=Math.sin(a)*23,z=Math.cos(a)*23;const gate=new THREE.Group();gate.position.set(x,0,z);gate.rotation.y=a;box(gate,0x607b69,-2,2,0,1,4,1);box(gate,0x607b69,2,2,0,1,4,1);box(gate,colors[r],0,4.3,0,5,1,1.2);box(gate,0xdde4c1,-2,4.9,0,.7,.4,.8);box(gate,0xdde4c1,2,4.9,0,.7,.4,.8);scene.add(gate);}
for(let i=-3;i<=3;i++)for(let j=-3;j<=3;j++)if(Math.abs(i)+Math.abs(j)<5)box(terrain,0xccd1a6,i*1.1,.06,j*1.1,1.06,.08,1.06);
function label(text,color='#ffffff'){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const c=canvas.getContext('2d');c.fillStyle='#123831cc';c.beginPath();c.roundRect(0,4,256,52,12);c.fill();c.font='bold 24px Arial';c.textAlign='center';c.fillStyle=color;c.fillText(text.slice(0,18),128,39);const texture=new THREE.CanvasTexture(canvas);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false}));s.scale.set(3.6,.9,1);s.position.y=3.6;return s;}
function hero(r){const g=new THREE.Group(),body=new THREE.Group();g.add(body);g.userData.body=body;const c=colors[r];if(r==='jet'){box(body,c,0,1.4,0,.85,.55,2.5);box(body,0x24495e,0,1.76,.3,.6,.35,.75);box(body,0xf2eac3,0,1.3,-.15,3.4,.2,.85);box(body,c,0,1.65,-1,.18,.7,.7);box(body,0xffbe52,-.55,1.3,-1.2,.35,.35,.55);box(body,0xffbe52,.55,1.3,-1.2,.35,.35,.55);box(body,0xffe99e,0,1.4,1.25,.45,.35,.4);}else{box(body,c,0,1.35,0,.95,1.1,.6);box(body,0xf4d2a2,0,2.25,0,.8,.8,.75);box(body,0x313a35,-.19,2.28,.4,.12,.14,.04);box(body,0x313a35,.19,2.28,.4,.12,.14,.04);box(body,0x75492f,0,2.69,-.05,.84,.15,.8);g.userData.legs=[box(body,0x384d54,-.26,.45,0,.36,.8,.5),box(body,0x384d54,.26,.45,0,.36,.8,.5)];g.userData.arms=[box(body,c,-.7,1.4,0,.42,.8,.5),box(body,c,.7,1.4,0,.42,.8,.5)];if(r==='fighter'){box(body,0xdc6148,-.74,1.1,.18,.65,.6,.7);box(body,0xdc6148,.74,1.1,.18,.65,.6,.7);box(body,0x394856,0,1.45,.33,.5,.6,.12);}else{box(body,0x653eae,0,2.78,0,1.25,.18,1.1);box(body,0x8659cb,0,3.05,0,.75,.45,.7);box(body,0xa174e1,0,3.4,0,.35,.3,.35);box(body,0x80613b,.9,1.5,.2,.15,2.1,.15);box(body,0xffbc4d,.9,2.65,.2,.4,.5,.4);}}
 const ring=new THREE.Mesh(new THREE.RingGeometry(.8,1,32),new THREE.MeshBasicMaterial({color:c,side:THREE.DoubleSide,transparent:true,opacity:.85}));ring.rotation.x=-Math.PI/2;ring.position.y=.12;g.add(ring);scene.add(g);return g;}
function monster(e){const g=new THREE.Group(),c=enemyColor[e.type];if(e.type==='armor'){box(g,c,0,1,0,1.35,1.5,1);box(g,0x687b72,0,1.85,0,1.25,.55,1.15);box(g,0xefba62,-.32,1.85,.6,.19,.12,.04);box(g,0xefba62,.32,1.85,.6,.19,.12,.04);box(g,0x77867b,-.9,1.2,.1,.6,.9,.65);box(g,0x77867b,.9,1.2,.1,.6,.9,.65);box(g,0xe5c18b,0,1.1,.6,.45,.65,.1);}else if(e.type==='magic'){box(g,0x734eae,0,.85,0,.95,1,.8);const gem=box(g,c,0,1.7,0,.95,.95,.95);gem.rotation.z=Math.PI/4;gem.rotation.y=Math.PI/4;box(g,0xebd4ff,-.24,1.65,.56,.14,.16,.05);box(g,0xebd4ff,.24,1.65,.56,.14,.16,.05);for(let i=0;i<3;i++){const s=box(g,0xb893f0,Math.sin(i*2.1)*1.05,1.4,Math.cos(i*2.1)*1.05,.3,.6,.3);s.rotation.z=.4;}}else{box(g,c,0,.7,0,.75,.75,1.3);box(g,0x47725c,0,1.15,.25,.85,.35,.85);box(g,0xf6f0a3,-.21,1.1,.7,.14,.12,.04);box(g,0xf6f0a3,.21,1.1,.7,.14,.12,.04);box(g,0xd4ed7b,-.45,.3,-.3,.25,.5,.5);box(g,0xd4ed7b,.45,.3,-.3,.25,.5,.5);box(g,c,0,.8,-.9,.2,.2,.8);}
 if(e.elite)g.scale.setScalar(1.35);if(e.boss){g.scale.setScalar(2.8);box(g,0xffd36c,-.45,2.4,0,.3,.7,.4);box(g,0xffd36c,.45,2.4,0,.3,.7,.4);const s=label('PRISM TITAN','#ffe092');s.position.y=3.1;g.add(s);}
 const hp=new THREE.Mesh(cubeGeo,new THREE.MeshBasicMaterial({color:0xecf9b4}));hp.position.set(0,e.type==='magic'?2.7:2.5,0);hp.scale.set(1,.1,.05);g.add(hp);g.userData.hp=hp;g.userData.type=e.type;scene.add(g);return g;}
roles.forEach((r,i)=>{const g=hero(r);g.position.set((i-1)*3,0,0);heroMeshes.set(r,g);});
const chest=new THREE.Group();box(chest,0xa86c32,0,.7,0,2,1.3,1.5);box(chest,0xffcc66,0,1.4,0,2.2,.35,1.7);box(chest,0xffd56b,-.7,.8,.8,.18,1.4,.12);box(chest,0xffd56b,.7,.8,.8,.18,1.4,.12);box(chest,0xffec92,0,.9,.86,.45,.5,.15);chest.visible=false;scene.add(chest);
function disposeObject(g){scene.remove(g);g.traverse(o=>{if(o.isSprite){o.material.map?.dispose();o.material.dispose();}});}
function effectRing(x,z,color,radius=4,time=.7){const mesh=new THREE.Mesh(new THREE.RingGeometry(.88,1,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:1,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.set(x,.18,z);scene.add(mesh);effects.push({mesh,life:time,total:time,radius,ring:true});}
function burst(x,z,color,n=12){for(let i=0;i<n;i++){const m=new THREE.Mesh(cubeGeo,mat(color));m.scale.setScalar(.14+Math.random()*.2);m.position.set(x,1,z);scene.add(m);effects.push({mesh:m,life:.7,total:.7,v:new THREE.Vector3((Math.random()-.5)*8,3+Math.random()*4,(Math.random()-.5)*8)});}}
function sound(freq=440,dur=.1,type='sine',vol=.035){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.6,audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur);}
function toast(msg,seconds=3){setGameText($('toast'),msg);toastUntil=performance.now()+seconds*1000;$('toast').style.opacity=1;}
function handleEvent(e){if(e.type==='wave'){toast(e.wave===5?'THE PRISM TITAN\nThree phases. One team!':e.wave===4?'ELITE WAVE\nStay together!':`WAVE ${e.wave}\nMatch the monster!`);sound(660,.25);}
 if(e.type==='clear'){toast('WAVE CLEAR!\nHealing your team…',2.5);sound(800,.25);}
 if(e.type==='phase'){toast(`${icons[e.role]} ${e.role.toUpperCase()}, YOUR TURN!`,3);burst(0,0,colors[e.role],20);sound(580,.25);}
 if(e.type==='attack'){const g=heroMeshes.get(e.role);g.userData.swing=.22;if(e.role==='fighter'){effectRing(e.tx,e.tz,0xffcf76,1.8,.22);}else{const beam=new THREE.Mesh(cubeGeo,new THREE.MeshBasicMaterial({color:e.role==='mage'?0xffa53d:0xa5f4ff}));const d=Math.hypot(e.tx-e.x,e.tz-e.z);beam.position.set((e.tx+e.x)/2,1.25,(e.tz+e.z)/2);beam.scale.set(e.role==='mage'?.22:.09,.15,d);beam.rotation.y=Math.atan2(e.tx-e.x,e.tz-e.z);scene.add(beam);effects.push({mesh:beam,life:.11,total:.11});}if(e.role===role)sound(e.role==='fighter'?110:e.role==='mage'?420:750,.07,'triangle',.018);}
 if(e.type==='skill'){effectRing(e.x,e.z,e.role==='mage'?0xff7e39:e.role==='fighter'?0xff4d20:0xf9d275,11,1);burst(e.x,e.z,colors[e.role],24);sound(100,.45,'sawtooth',.035);toast(`${icons[e.role]} ${e.role==='fighter'?'LAVA PUNCH':e.role==='mage'?'FIRE RING':'BOMB STRIKE'}!`,1.2);}
 if(e.type==='hit'){if(document.querySelectorAll('.floating').length<24){const p=new THREE.Vector3(e.x,2.8,e.z).project(camera);if(p.z<1){const el=document.createElement('div');el.className='floating'+(e.weak?' weak':'');el.style.left=((p.x+1)/2*screenSize.width)+'px';el.style.top=((-p.y+1)/2*screenSize.height)+'px';el.style.color=e.strong?'#ffef94':'#ffffff';el.textContent=(e.strong?'★ ':'')+e.damage;$('gameViewport').append(el);setTimeout(()=>el.remove(),850);}}}
 if(e.type==='poof')burst(e.x,e.z,enemyColor[e.type],e.boss?40:8);
 if(e.type==='warning'){effectRing(e.x,e.z,0xff533c,5.8,1.3);toast('MOVE OUT OF THE RED RING!',1.3);sound(190,.2,'square',.018);}
 if(e.type==='slam'){effectRing(e.x,e.z,0xff5031,6,.4);burst(e.x,e.z,0xffb253,16);}
 if(e.type==='treasure'){toast('THE TITAN IS DOWN!\nFind the golden chest!',5);sound(1000,.4);}
 if(e.type==='revive')toast(`${icons[e.role]} ${e.role.toUpperCase()} IS BACK!`,2);
 if(e.type==='ouch'&&e.role===role)sound(90,.13,'triangle');}
function send(data){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data));}
function connect(){const name=$('name').value.trim();if(!name){setGameText($('error'),'Enter your name first! / 先输入你的名字');$('name').focus();return;}document.activeElement?.blur();$('join').disabled=true;setGameText($('error'),'Connecting…');audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}`);ws.onopen=()=>send({type:'join',name,role:selected,room:$('room').value});ws.onmessage=ev=>{const m=JSON.parse(ev.data);if(m.type==='error'){setGameText($('error'),m.message);$('join').disabled=false;ws.close();return;}if(m.type==='joined'){role=m.role;isHost=m.host;connected=true;$('landing').hidden=true;$('hud').hidden=false;setGameText($('roomLabel'),'ROOM '+m.room);setGameText($('error'),'');lastEvent=0;history.replaceState(null,'','?room='+encodeURIComponent(m.room));}if(m.type==='host'){isHost=true;toast('You are now the team host.');}if(m.type==='state'){const prev=state;state=m;if(prev&&(m.time<prev.time||m.events.at(-1)?.id<lastEvent))lastEvent=0;for(const e of m.events)if(e.id>lastEvent){handleEvent(e);lastEvent=e.id;}updateHUD();}};ws.onclose=()=>{if(connected){connected=false;toast('CONNECTION LOST\nReload to rejoin your team.',600);$('pause').disabled=true;}else{$('join').disabled=false;}};ws.onerror=()=>{setGameText($('error'),'Connection failed. Keep the game server running.');$('join').disabled=false;};}
$('join').onclick=connect;document.querySelectorAll('.role').forEach(b=>b.onclick=()=>{selected=b.dataset.role;document.querySelectorAll('.role').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b?'true':'false');});});const roomParam=new URLSearchParams(location.search).get('room');if(roomParam)$('room').value=roomParam;
$('start').onclick=()=>send({type:'start'});$('pause').onclick=$('resume').onclick=()=>send({type:'pause'});$('restart').onclick=()=>send({type:'restart'});$('camera').onclick=()=>{first=!first;setGameText($('camera'),first?'👁 1ST PERSON':'👁 3RD PERSON');$('crosshair').style.display=first?'block':'none';};$('sound').onclick=()=>{muted=!muted;setGameText($('sound'),muted?'♪ SOUND OFF':'♪ SOUND ON');};$('openChest').onclick=()=>{send({type:'input',interact:true});};
let hudKey='';function updateHUD(){if(!state||!role)return;const p=state.players.find(p=>p.role===role);$('waiting').hidden=state.state!=='lobby';$('pauseModal').hidden=state.state!=='paused';$('ending').hidden=!['victory','defeat'].includes(state.state);$('start').disabled=!isHost;setGameText($('start'),isHost?'START THE RUSH →':'WAITING FOR THE HOST…');setGameText($('hostnote'),isHost?'You are the host · 你来开始':'The first player starts the game · 等待队长开始');$('pause').disabled=!isHost;$('resume').disabled=!isHost;$('restart').disabled=!isHost;
 const rosterKey=state.players.map(p=>p.name+p.bot).join('|');if(rosterKey!==hudKey){hudKey=rosterKey;$('team').replaceChildren();$('roster').replaceChildren();for(const player of state.players){const card=document.createElement('div');card.className='teammate'+(player.role===role?' mine':'');card.style.setProperty('--c',hex[player.role]);card.innerHTML='<b></b><small></small><div class="hp"><i></i></div><div class="healthnum"></div>';card.querySelector('b').textContent=icons[player.role]+' '+player.name;card.querySelector('small').textContent=player.bot?'BOT':player.role===role?'YOU':'PLAYER';card.dataset.role=player.role;$('team').append(card);const entry=document.createElement('div');const icon=document.createElement('span');icon.textContent=icons[player.role];entry.append(icon,document.createTextNode(player.name));$('roster').append(entry);const g=heroMeshes.get(player.role);if(g.userData.label){g.remove(g.userData.label);g.userData.label.material.map.dispose();g.userData.label.material.dispose();}g.userData.label=label(player.name,hex[player.role]);g.add(g.userData.label);}}
 for(const player of state.players){const el=$('team').querySelector(`[data-role="${player.role}"]`);el.querySelector('.hp i').style.width=(player.hp/player.maxHp*100)+'%';el.querySelector('.healthnum').textContent=player.hp>0?`${Math.ceil(player.hp)} / ${player.maxHp} HP`: `HELP ME! ${Math.ceil(12-player.down)}s`;}
 setGameText($('waveCaption'),state.state==='treasure'?'FINAL REWARD':state.state==='victory'?'TEAMWORK WINS':'SURVIVE TOGETHER');setGameText($('wave'),state.state==='lobby'?'YOUR TEAM':state.state==='treasure'?'TREASURE TIME':state.wave===5?'BOSS BATTLE':state.wave===4?'ELITE WAVE':`WAVE ${state.wave} / 5`);$('progress').style.width=(state.wave/5*100)+'%';const boss=state.enemies.find(e=>e.boss);$('bossbar').hidden=!boss;if(boss){$('bosshp').style.width=(boss.hp/boss.maxHp*100)+'%';setGameText($('bosshelp'),`${icons[counter[boss.type]]} ${boss.type.toUpperCase()} PHASE → ${counter[boss.type].toUpperCase()}`);}
 const skillNames={fighter:'LAVA PUNCH',mage:'FIRE RING',jet:'BOMB STRIKE'},cds={fighter:12,mage:14,jet:10};setGameText($('skillname'),skillNames[role]);$('skill').querySelector('span').textContent={fighter:'🌋',mage:'🔥',jet:'💣'}[role];setGameText($('cooldown'),p.cd>.1?`${p.cd.toFixed(1)}s`:'READY · E');$('skillshade').style.height=(p.cd/cds[role]*100)+'%';$('openChest').hidden=state.state!=='treasure'||Math.hypot(p.x,p.z)>4;chest.visible=['treasure','victory'].includes(state.state);
 if(!['playing','treasure'].includes(state.state))setGameText($('target'),'');else if(p.hp<=0)setGameText($('target'),'DOWN! A teammate nearby helps you recover faster.');else if(state.state==='treasure')setGameText($('target'),'Walk to the golden chest at the center!');else{const near=state.enemies.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];setGameText($('target'),near?`${icons[counter[near.type]]} ${near.type==='armor'?'STONE ARMOR':near.type==='magic'?'CRYSTAL CASTER':'GREEN RUNNER'} → ${counter[near.type].toUpperCase()}!`:state.intermission?'Next wave incoming…':'Monsters incoming…');}
 if(state.state==='victory'||state.state==='defeat'){setGameText($('endIcon'),state.state==='victory'?'🧰':'💛');setGameText($('endtitle'),state.state==='victory'?'TEAM VICTORY!':'TRY TOGETHER AGAIN');setGameText($('endcopy'),state.state==='victory'?'Three heroes. Three strengths. One legendary team.\n宝箱属于整个队伍！':'Stay close, match the monsters, and save your super skills!');setGameText($('endstats'),`${state.kills} monsters · ${Math.floor(state.time/60)}m ${Math.floor(state.time%60)}s · ${state.bossPhases.length}/3 boss phases`);}}
function input(){if(!role||!connected)return;if(keys.has('q'))yaw+=.055;if(keys.has('r'))yaw-=.055;let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+touch.x,z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+touch.z;send({type:'input',x:x*Math.cos(yaw)+z*Math.sin(yaw),z:z*Math.cos(yaw)-x*Math.sin(yaw),attack:touch.attack||keys.has(' ')||keys.has('j'),skill:touch.skill||keys.has('e'),interact:keys.has('f')});}setInterval(input,1000/30);
addEventListener('keydown',e=>{if(document.activeElement.tagName==='INPUT')return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(!e.repeat&&k==='c')$('camera').click();if(!e.repeat&&k==='escape')$('pause').click();keys.add(k);if(k==='e'||k===' ')input();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));function release(){keys.clear();touch.x=touch.z=0;touch.attack=touch.skill=false;send({type:'input'});$('stick').style.transform='';}addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden)release();});
for(const name of ['attack','skill']){const btn=$(name);btn.onpointerdown=e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);touch[name]=true;input();audio?.resume();};btn.onpointerup=btn.onpointercancel=()=>touch[name]=false;}
let joyId=null;const joy=$('joystick');function moveJoy(e){if(e.pointerId!==joyId)return;const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,scale=r.width/joy.offsetWidth,mag=Math.max(1,Math.hypot(dx,dy)/(35*scale));touch.x=dx/mag/(35*scale);touch.z=dy/mag/(35*scale);$('stick').style.transform=`translate(${dx/mag/scale}px,${dy/mag/scale}px)`;}joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e);};joy.onpointermove=moveJoy;joy.onpointerup=joy.onpointercancel=()=>{joyId=null;touch.x=touch.z=0;$('stick').style.transform='';};let drag=null;$('world').onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX};$('world').setPointerCapture(e.pointerId);};$('world').onpointermove=e=>{if(drag&&drag.id===e.pointerId){yaw-=(e.clientX-drag.x)*display.getSize().scale*.006;drag.x=e.clientX;}};$('world').onpointerup=$('world').onpointercancel=()=>drag=null;
function resize(size){screenSize=size;renderer.setSize(size.width,size.height,false);camera.aspect=size.width/size.height;camera.updateProjectionMatrix();}
const display=installDisplay({onResize:resize,onInterrupt:()=>{release();joyId=null;drag=null;}});
let last=performance.now(),frame=0;const targetCam=new THREE.Vector3(),look=new THREE.Vector3();function render(now){requestAnimationFrame(render);const dt=Math.min(.05,(now-last)/1000);last=now;frame++;const t=now*.001;if(state){for(const p of state.players){const g=heroMeshes.get(p.role);const moving=Math.hypot(g.position.x-p.x,g.position.z-p.z)>.06;g.position.lerp(new THREE.Vector3(p.x,0,p.z),.3);let angle=p.facing-g.rotation.y;angle=Math.atan2(Math.sin(angle),Math.cos(angle));g.rotation.y+=angle*.25;g.visible=!(p.role===role&&first);g.userData.body.rotation.z=p.hp<=0?Math.PI/2:0;g.userData.body.position.y=p.hp<=0?.1:p.role==='jet'?Math.sin(t*4)*.1:moving?Math.abs(Math.sin(t*12))*.1:0;if(g.userData.legs)g.userData.legs.forEach((leg,i)=>leg.rotation.x=moving?Math.sin(t*12+i*Math.PI)*.5:0);g.userData.swing=Math.max(0,(g.userData.swing||0)-dt);if(g.userData.arms)g.userData.arms.forEach(a=>a.rotation.x=g.userData.swing>0?-1.3:0);}
 const ids=new Set();for(const e of state.enemies){ids.add(e.id);let g=enemyMeshes.get(e.id);if(g&&g.userData.type!==e.type){disposeObject(g);enemyMeshes.delete(e.id);g=null;}if(!g){g=monster(e);g.position.set(e.x,0,e.z);enemyMeshes.set(e.id,g);}g.position.x+=(e.x-g.position.x)*.35;g.position.z+=(e.z-g.position.z)*.35;g.position.y=Math.abs(Math.sin(t*(e.type==='speed'?14:6)+e.id))*.12;const target=state.players.filter(p=>p.hp>0).sort((a,b)=>Math.hypot(a.x-e.x,a.z-e.z)-Math.hypot(b.x-e.x,b.z-e.z))[0];if(target)g.rotation.y=Math.atan2(target.x-e.x,target.z-e.z);g.userData.hp.scale.x=Math.max(.01,e.hp/e.maxHp);}
 for(const [id,g]of enemyMeshes)if(!ids.has(id)){disposeObject(g);enemyMeshes.delete(id);}const p=state.players.find(p=>p.role===role);if(p){if(first){targetCam.set(p.x,role==='jet'?2.2:2.6,p.z);look.set(p.x-Math.sin(yaw)*12,1.7,p.z-Math.cos(yaw)*12);}else{const distance=screenSize.width<screenSize.height?17:13;targetCam.set(p.x+Math.sin(yaw)*distance,12.5,p.z+Math.cos(yaw)*distance);look.set(p.x,1,p.z);}camera.position.lerp(targetCam,.15);camera.lookAt(look);}}
 else{const a=.32+Math.sin(t*.12)*.12;camera.position.set(Math.sin(a)*17,10,Math.cos(a)*17);camera.lookAt(-3,1,0);heroMeshes.forEach((g,i)=>{g.userData.body.position.y=Math.sin(t*3+(g.position.x))*.1;g.rotation.y=Math.sin(t*.4)*.3;});}
 chest.rotation.y=Math.sin(t)*.15;for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.life<=0){scene.remove(e.mesh);if(e.ring)e.mesh.geometry.dispose();if(e.mesh.material.type==='MeshBasicMaterial')e.mesh.material.dispose();effects.splice(i,1);continue;}if(e.ring){const p=1-e.life/e.total;e.mesh.scale.setScalar(e.radius*(.15+p*.85));e.mesh.material.opacity=e.life/e.total;}if(e.v){e.mesh.position.addScaledVector(e.v,dt);e.v.y-=dt*12;e.mesh.rotation.x+=dt*5;}}
 if(now>toastUntil)$('toast').style.opacity=0;if(chest.visible&&frame%12===0)burst(0,0,0xffde77,1);renderer.render(scene,camera);}
requestAnimationFrame(render);
window.__rps={getState:()=>state,getCamera:()=>({first,yaw}),renderer};
