const $=s=>document.querySelector(s), canvas=$('#canvas'),ctx=canvas.getContext('2d');
let token=sessionStorage.getItem('beastToken'),slot=null,state=null,es=null,online=false,joining=false,lastFrame=0,reconnectTimer=null,retryDelay=1000,leaving=false;const input={},pointers=new Map(),keymap={KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',Space:'jump',ArrowUp:'jump',KeyJ:'punch',KeyI:'kick',KeyK:'spin',KeyL:'teleport',KeyU:'super'},pressedKeys=new Set();
async function api(route,data={}){const r=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...data}),keepalive:true});const b=await r.json();if(!r.ok)throw Error(b.error);return b;}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000);}
function release(){pointers.clear();pressedKeys.clear();for(let k of Object.keys(input))input[k]=false;document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));if(token&&online)api('input',{input}).catch(()=>{});}
function rebuild(){for(let k of Object.values(keymap))input[k]=false;for(let k of pressedKeys)input[k]=true;for(let k of pointers.values())input[k]=true;document.querySelectorAll('[data-key]').forEach(b=>b.classList.toggle('held',!!input[b.dataset.key]));if(online)api('input',{input}).catch(()=>{});}
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.key);rebuild();});const up=e=>{pointers.delete(e.pointerId);rebuild();};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up);});
window.addEventListener('keydown',e=>{if(keymap[e.code]){e.preventDefault();pressedKeys.add(keymap[e.code]);rebuild();}});window.addEventListener('keyup',e=>{if(keymap[e.code]){e.preventDefault();pressedKeys.delete(keymap[e.code]);rebuild();}});window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden)release();});window.addEventListener('pagehide',()=>{release();if(es)es.close();});
function connectionLost(){online=false;release();$('#connection').textContent='Reconnecting...';$('#overlay').hidden=false;$('#title').textContent='Connection paused';$('#explain').textContent='Keep Tailscale connected on both iPads. We will reconnect automatically.';$('#reconnect').hidden=false;for(const id of ['join','start','resume','rematch','modes'])$('#'+id).hidden=true;$('#pause').disabled=true;}
function retryJoin(){if(leaving||!token||reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;join();},retryDelay);retryDelay=Math.min(5000,retryDelay*1.5);}
async function join(){if(joining||leaving)return;joining=true;clearTimeout(reconnectTimer);reconnectTimer=null;if(es){es.close();es=null;}try{let b=await api('join');if(leaving)return;token=b.token;slot=b.slot;sessionStorage.setItem('beastToken',token);const stream=new EventSource('/events?token='+encodeURIComponent(token));es=stream;stream.onmessage=e=>{if(es!==stream||leaving)return;state=JSON.parse(e.data);online=true;retryDelay=1000;clearTimeout(reconnectTimer);reconnectTimer=null;$('#reconnect').hidden=true;updateUI();};stream.onerror=()=>{if(es!==stream||leaving)return;connectionLost();if(stream.readyState===EventSource.CLOSED)retryJoin();};}catch(e){toast(e.message);if(token){connectionLost();retryJoin();}}finally{joining=false;}}
$('#join').onclick=join;$('#reconnect').onclick=join;$('#leave').onclick=async()=>{leaving=true;clearTimeout(reconnectTimer);release();if(token)await api('leave').catch(()=>{});if(es)es.close();sessionStorage.removeItem('beastToken');location.reload();};
window.addEventListener('offline',()=>{if(!token||leaving)return;if(es)es.close();connectionLost();retryJoin();});
window.addEventListener('online',()=>{if(token&&!online&&!leaving)join();});
window.addEventListener('pageshow',()=>{if(token&&!leaving&&(!es||es.readyState===EventSource.CLOSED))join();});
async function control(action,mode){try{release();await api('control',{action,mode});}catch(e){toast(e.message);}}
$('#pause').onclick=()=>control('pause');$('#start').onclick=()=>control('start');$('#resume').onclick=()=>control('resume');$('#rematch').onclick=()=>control('rematch');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(slot===null){toast('Enter the arena first, then choose your mode.');return;}control('mode',b.dataset.mode);});
setInterval(()=>{if(online&&token)api('input',{input:document.hidden?{}:input}).catch(()=>{});},150);
fetch('/health').then(r=>r.json()).then(h=>{const tail=h.urls.find(u=>{const parts=new URL(u).hostname.split('.').map(Number);return parts[0]===100&&parts[1]>=64&&parts[1]<=127;});$('#joinLink').textContent=(tail?'Tailscale: ':'Join link: ')+(tail||location.origin)+'  |  room BEASTS';}).catch(()=>{$('#joinLink').textContent='Open this same address on both iPads. Keep Tailscale connected.';});
function updateUI(){const s=state;$('#connection').textContent=''+(s.connected.every(Boolean)?'Both beasts connected': 'Waiting for another beast');$('#you').textContent='YOU ARE '+s.players[slot].name;$('#modeLabel').textContent=s.mode==='duel'?'DUEL':'CROWN HUNT';for(let i=0;i<2;i++){let p=s.players[i];$('#hp'+i).textContent=Math.ceil(p.hp)+' HP';$('#bar'+i).style.width=p.hp+'%';$('#power'+i).textContent=(i?'FIRE':'ICE')+' GUARDIAN  |  '+(s.mode==='crown'?p.charges+'/5 TARGETS  |  +'+Math.round(p.charges*12)+'% POWER':(s.connected[i]?'CONNECTED':'WAITING'));}let p=s.players[slot];$('#energyBar').style.width=p.energy+'%';document.querySelectorAll('.actions button').forEach(b=>{let cd=p.cd[b.dataset.key]||0;b.querySelector('em').textContent=cd>.1?cd.toFixed(1):'';});$('#overlay').hidden=s.status==='playing';$('#join').hidden=true;$('#start').hidden=s.status!=='lobby';$('#start').disabled=!s.connected.every(Boolean);$('#resume').hidden=s.status!=='paused';$('#resume').disabled=!s.connected.every(Boolean);$('#rematch').hidden=!['ended','paused'].includes(s.status);$('#modes').hidden=!['lobby','ended'].includes(s.status);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===s.mode));if(s.status==='lobby'){$('#title').textContent='Two beasts. One crown.';$('#explain').textContent=s.connected.every(Boolean)?'Both ready! Choose your mode and start.':'You are '+p.name+'. Open this link on the other iPad.';}else if(s.status==='paused'){$('#title').textContent='Take a breath.';$('#explain').textContent=s.reason;}else if(s.status==='ended'){$('#title').textContent=s.winner==='DRAW'?'Double legends!':s.winner+' reigns!';$('#explain').textContent=s.reason;}$('#pause').disabled=s.status!=='playing';}
const colors=[['#71e3ff','#287fac','#153f67'],['#ffc071','#d96639','#7b3643']];
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill();}
function beast(p,t){let c=colors[p.id],bob=p.y===470?Math.sin(t*3+p.id)*2:0;ellipse(p.x,483,48-(470-p.y)*.05,10,'#0005');ctx.save();ctx.translate(p.x,p.y+bob);ctx.scale(p.face,1);if(!p.hp){ctx.rotate(Math.PI/2);ctx.globalAlpha=.5;}if(p.invuln)ctx.globalAlpha=.55+.3*Math.sin(t*30);if(p.flash)c=['#fff','#fff','#b5e6ff'];let active=p.anim>0;
 if(p.y<460){poly([[-26,-40],[-94,-94],[-79,-24],[-36,-9]],c[2]);poly([[26,-40],[83,-91],[72,-17],[30,-8]],c[1]);}
 poly([[-29,-35],[-85,-9],[-100,-28],[-80,-36],[-55,-52]],c[2]);ellipse(-22,-13,19,17,c[2]);ellipse(24+(active&&p.action==='kick'?35:0),-12,20,17,c[1]);ellipse(0,-54,43,49,c[1]);ellipse(8,-48,25,33,c[0]);
 ellipse(-2,-96,43,35,c[1]);poly([[-33,-113],[-35,-151],[-12,-123]],'#e2f5ef');poly([[19,-120],[37,-146],[38,-104]],'#e2f5ef');poly([[-35,-80],[-49,-93],[-45,-60],[-29,-70]],c[0]);ellipse(23,-91,26,19,c[0]);ellipse(29,-96,5,4,c[2]);ellipse(8,-112,10,11,'#f5ffff');ellipse(12,-111,4,7,'#12253b');poly([[0,-124],[21,-117],[20,-122],[2,-132]],c[2]);ctx.strokeStyle=c[2];ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(14,-82);ctx.lineTo(37,-84);ctx.stroke();poly([[23,-84],[26,-76],[30,-85]],'#fff');
 let reach=active&&p.action==='punch'?42:0;ellipse(38+reach,-52,23,18,c[1]);for(let z=0;z<3;z++)poly([[49+reach,-62+z*8],[60+reach,-58+z*8],[49+reach,-55+z*8]],'#eefbff');ellipse(-32,-58,15,23,c[2]);
 if(p.charges){ctx.globalAlpha=1;ctx.strokeStyle='#ffdb72';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-65,68,0,Math.PI*2);ctx.stroke();for(let j=0;j<p.charges;j++)ellipse(Math.cos(t+j*1.25)*69,-65+Math.sin(t+j*1.25)*69,5,5,'#ffe99d');}ctx.restore();ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillStyle=p.id?'#ffc889':'#a8edff';ctx.fillText(p.name+(p.id===slot?'  |  YOU':''),p.x,p.y-169);if(p.respawn>0){ctx.fillStyle='#fff';ctx.fillText('BACK IN '+Math.ceil(p.respawn),p.x,p.y-190);}}
function render(ms){let t=ms/1000;ctx.clearRect(0,0,1200,580);let grad=ctx.createLinearGradient(0,0,0,580);grad.addColorStop(0,'#111c38');grad.addColorStop(.7,'#384468');grad.addColorStop(1,'#1b2c42');ctx.fillStyle=grad;ctx.fillRect(0,0,1200,580);ellipse(600,140,95,95,'#ffebba');ellipse(600,140,118,118,'#ffdf9b0b');for(let i=0;i<55;i++){let x=(i*193)%1200,y=(i*47)%260;ellipse(x,y,1.2,1.2,'#e0eaff77');}
 poly([[0,290],[120,185],[240,306],[385,142],[520,324],[720,206],[880,304],[1030,130],[1200,282],[1200,580],[0,580]],'#172b45');poly([[0,355],[156,300],[260,374],[434,272],[602,360],[803,315],[1000,371],[1200,291],[1200,580],[0,580]],'#243a51');
 for(let i=0;i<6;i++){let x=i*240-30;poly([[x,459],[x+9,295],[x+27,264],[x+51,298],[x+62,459]],'#172a3d');poly([[x+14,314],[x+29,284],[x+35,363],[x+23,406]],i%2?'#d77a5360':'#55cbd660');}
 ellipse(600,523,650,82,'#080f20');poly([[20,470],[1180,470],[1144,520],[56,520]],'#607185');poly([[56,520],[1144,520],[1100,555],[97,555]],'#263b50');ctx.strokeStyle='#b7d6d680';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(25,470);ctx.lineTo(1175,470);ctx.stroke();for(let i=0;i<13;i++){ctx.strokeStyle='#8196a33b';ctx.beginPath();ctx.moveTo(80+i*85,474);ctx.lineTo(65+i*86,513);ctx.stroke();}ellipse(600,493,105,12,'#ffe6a218');
 const s=state||{players:[{id:0,name:'FROST',x:280,y:470,face:1,hp:100,charges:0},{id:1,name:'EMBER',x:920,y:470,face:-1,hp:100,charges:0}],targets:[],effects:[]};
 for(let target of s.targets)if(target.hp>0){ctx.save();ctx.translate(target.x,target.y);let b=Math.sin(t*3+target.id)*4;ellipse(0,8,24,7,'#0004');poly([[-26,-30+b],[-19,-63+b],[0,-78+b],[23,-58+b],[29,-28+b],[0,-12+b]],target.flash?'#fff':'#b0a0e7');ellipse(-8,-48+b,4,6,'#2d294c');ellipse(9,-48+b,4,6,'#2d294c');ctx.fillStyle='#332e50';ctx.fillRect(-24,-95,48,5);ctx.fillStyle='#d6c5ff';ctx.fillRect(-24,-95,48*target.hp/28,5);ctx.restore();}
 for(let p of s.players)beast(p,t);
 for(let e of s.effects){let a=e.life/.5,c=e.color?'#ffb766':'#83e8ff';ctx.save();ctx.globalAlpha=a;ctx.strokeStyle=c;ctx.lineWidth=5;ctx.translate(e.x,e.y);if(e.type==='super'){ctx.fillStyle=c;ctx.shadowBlur=30;ctx.shadowColor=c;ctx.fillRect(e.color?-330:0,-7,330,14);}else if(e.type==='crown'){ctx.font='50px Arial';ctx.textAlign='center';ctx.fillStyle='#ffe389';ctx.fillText('\u265b',0,-30*(1-a));}else{ctx.beginPath();ctx.arc(0,0,(1-a)*80+15,0,Math.PI*2);ctx.stroke();for(let j=0;j<8;j++){let ang=j*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(ang)*30*(1-a),Math.sin(ang)*30*(1-a));ctx.lineTo(Math.cos(ang)*100*(1-a),Math.sin(ang)*100*(1-a));ctx.stroke();}}ctx.restore();}
 requestAnimationFrame(render);}
requestAnimationFrame(render);if(token)join();


