/* Martin's Monster Quest V2: independent implementation. Three.js is the only reused runtime. */
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='martin-monster-quest-v2-wildbound-1';
const SPECIES={
 Flameling:{type:'fire',color:0xf28b52,shape:'fox',icon:'🔥',next:'Pyrowhisker',stage:0},Pyrowhisker:{type:'fire',color:0xe96849,shape:'fox',icon:'🔥',next:'Pyrostryke',stage:1},Pyrostryke:{type:'fire',color:0xd94d3c,shape:'dragon',icon:'🔥',stage:2},
 Leafbit:{type:'grass',color:0x8fc966,shape:'rabbit',icon:'🌿',next:'Thornhare',stage:0},Thornhare:{type:'grass',color:0x55a572,shape:'rabbit',icon:'🌿',next:'Floraknight',stage:1},Floraknight:{type:'grass',color:0x368d67,shape:'knight',icon:'🌿',stage:2},
 Aquapup:{type:'water',color:0x61becb,shape:'dog',icon:'💧',next:'Hydrofang',stage:0},Hydrofang:{type:'water',color:0x408ea9,shape:'dog',icon:'💧',next:'Leviaking',stage:1},Leviaking:{type:'water',color:0x416bc0,shape:'dragon',icon:'💧',stage:2},
 Voltling:{type:'electric',color:0xffcd57,shape:'fox',icon:'⚡',next:'Thunderbeast',stage:0,rare:true},Thunderbeast:{type:'electric',color:0xe4ae45,shape:'dragon',icon:'⚡',stage:1,rare:true},Stoneclaw:{type:'rock',color:0xb6a78a,shape:'rock',icon:'◆',stage:0},GigaGolem:{type:'rock',color:0xa59a85,shape:'golem',icon:'◆',stage:2},Stormjaw:{type:'electric',color:0x8272bc,shape:'dragon',icon:'⚡',stage:2,rare:true}
};
const TYPE_COLOR={fire:0xff843b,water:0x68ddff,grass:0xbaf567,electric:0xffe678,rock:0xdcc08a};
const REGIONS=[{name:'Emerald Valley',sub:'A small beginning. A wild possibility.',color:0x9bbd79,sky:0xbfdcca,hill:0x649f78,wild:['Leafbit','Aquapup','Flameling'],boss:'GigaGolem',level:6},{name:'Whispering Gorge',sub:'Rare creatures. Worth the climb.',color:0xc1ae8d,sky:0xd5d9c9,hill:0x9b907b,wild:['Stoneclaw','Voltling','Pyrowhisker'],boss:'Hydrofang',level:9},{name:'Thunder Peak',sub:'Prepare your team for the storm.',color:0x8d9ea2,sky:0xc5cddd,hill:0x7a829a,wild:['Thunderbeast','Thornhare','Hydrofang'],boss:'Stormjaw',level:12}];
let S=null,state='title',battle=null,battleSerial=0,keys={},walkTarget=null,near=null,toastTimer,confirmAction=null,muted=false,audio=null;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
function maxHP(m){return 40+m.level*9+SPECIES[m.species].stage*20+(m.trait==='heart'?22:0)}
function make(species,level){let m={id:uid(),species,level,xp:0,trait:null,hp:1};m.hp=maxHP(m);return m}
function active(){return S.party.find(m=>m.id===S.active)||S.party[0]}
function normalize(){if(!S.party.some(m=>m.id===S.active&&m.hp>0)){let m=S.party.find(m=>m.hp>0);if(m)S.active=m.id}S.coins=Math.max(0,Math.floor(S.coins));}
function save(){if(!S)return;try{localStorage.setItem(KEY,JSON.stringify(S));$('#save-status').textContent='● Auto-saved · V2';}catch{$('#save-status').textContent='Storage unavailable — keep this page open';}}
function readSave(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x?.v===2&&x.party?.length&&x.party.every(m=>SPECIES[m.species]&&Number.isFinite(m.hp)&&m.level>0))return x}catch{}return null}
function mode(s){state=s;keys={};walkTarget=null;$('#explore').hidden=s!=='explore';$('#labels').hidden=s!=='explore';$('#battle').hidden=!['battle','acting','switch'].includes(s);$('#quest').hidden=s!=='explore';$('#hud').hidden=['title','choose'].includes(s);$('#team').disabled=s!=='explore';$('#map').disabled=s!=='explore';}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function tone(type='select',strong=false){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type=type==='electric'?'sawtooth':type==='water'?'sine':'triangle';let f={fire:180,water:560,grass:380,electric:820,rock:110,select:640,win:900}[type]||450;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(type==='win'?1400:Math.max(50,f*.4),audio.currentTime+.25);g.gain.setValueAtTime(strong?.07:.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.36);o.start();o.stop(audio.currentTime+.4)}catch{}}
function btn(text,a,extra='',cls=''){return `<button class="${cls}" data-a="${a}" ${extra}>${text}</button>`}
function panel(html,cls=''){ $('#overlay').innerHTML=`<section class="panel ${cls}">${html}</section>`;}
function hpHTML(m){return `<div class="bar ${m.hp<maxHP(m)*.3?'low':''}"><i style="width:${Math.max(0,m.hp/maxHP(m)*100)}%"></i></div><span class="muted">${Math.ceil(m.hp)} / ${maxHP(m)} HP</span>`}
function sellValue(m){let d=SPECIES[m.species];return Math.floor((22+m.level*10)*(d.rare?1.4:1)*(1+d.stage*.35))}
function buyValue(m){return Math.ceil(sellValue(m)*1.65)}
function refreshHUD(){if(!S)return;normalize();$('#wallet').innerHTML=`◈ ${S.coins} <span class="muted"> · ${S.capsules} orbs · ${S.food} meals</span>`;let objectives=['Build a team. Defeat GigaGolem.','Train & evolve. Win Sky’s duel.','Prepare for Stormjaw’s awakening.','You are the Wildbound champion!'];$('#quest').innerHTML=`<div class="eyebrow">0${S.region+1} / ${REGIONS[S.region].name}</div><h3>${objectives[Math.min(S.progress,3)]}</h3><p>${S.progress===0?'Weaken wild monsters to 50% HP to guarantee capture. Trade spare catches for a stronger team.':S.progress===1?'Water beats fire. Grass beats water & rock. Bring meals and more than one partner.':S.progress===2?'Rock grounds electric attacks. Stormjaw has two phases. Train a full team before climbing.':'Explore, collect all 14 forms, and build your dream team.'}</p><div class="progress">${[0,1,2].map(i=>`<i class="${S.progress>i?'done':''}"></i>`).join('')}</div>`;}
function title(){mode('title');makeTitle();const saved=readSave();panel(`<div class="eyebrow">MARTIN’S MONSTER QUEST · V2</div><h1>A wild world.<br><em>Your kind<br>of adventure.</em></h1><p class="hero-copy">Find a friend. Make a trade. Cook up courage.<br>Build a team that can weather the storm.</p><div class="row">${saved?btn('Continue adventure','continue','','gold'):''}${btn(saved?'New adventure':'Begin adventure','new','',saved?'':'gold')}</div><p class="muted">A single-player 3D adventure · keyboard + touch<br>Original monsters. Real choices. All coins are in-game.</p>`,'title-panel');}
let chosenTrainer='Martin';
function choose(){mode('choose');panel(`<div class="eyebrow">EVERY ADVENTURE STARTS WITH A FRIEND</div><h2>Choose your first partner</h2><div class="row trainer-select">${['Martin','Sky','Leo'].map(n=>btn(n,'trainer',`data-id="${n}"`,n===chosenTrainer?'active':'')).join('')}</div><div class="grid starter-grid">${['Flameling','Leafbit','Aquapup'].map(n=>`<article class="card"><div class="icon">${SPECIES[n].icon}</div><h3>${n}</h3><span class="tag">${SPECIES[n].type.toUpperCase()}</span><p>${n==='Flameling'?'A brave fox. Strong against grass.':n==='Leafbit'?'A curious hare. Strong against water & rock.':'A loyal pup. Strong against fire.'}</p>${btn('Choose '+n,'starter',`data-id="${n}"`,'gold')}</article>`).join('')}</div><p class="muted">All partners evolve at levels 5 and 9. Change teammates anytime. Keyboard and touch always work together.</p>${btn('Back','title')}`);}
function start(species){let m=make(species,3);S={v:2,trainer:chosenTrainer,party:[m],active:m.id,coins:110,food:1,capsules:8,region:0,progress:0,pos:{x:0,z:7},hunts:0,claims:{},stats:{captures:0,sold:0,cooked:0,bought:0,wins:0,losses:0}};save();enterWorld();dialogue('Welcome to the wild',`${S.trainer}, monsters are companions — and valuable resources. Keep a catch, trade it at the market, or choose to turn it into a restorative meal. Your first goal: build a team strong enough to beat GigaGolem.`,()=>enterWorld());}
function dialogue(head,body,done){mode('story');confirmAction=done;panel(`<div class="eyebrow">TRAIL JOURNAL</div><h2>${head}</h2><p>${body}</p>${btn('Let’s go','story-next','','gold')}`)}
function enterWorld(){battleSerial++;battle=null;$('#overlay').innerHTML='';mode('explore');normalize();if(!S.party.some(m=>m.hp>0))S.party.forEach(m=>m.hp=maxHP(m));makeWorld();refreshHUD();save();}
function confirmation(head,body,action,back){mode('confirm');let consumed=false;confirmAction=()=>{if(consumed)return;consumed=true;action()};panel(`<div class="eyebrow">PLEASE CONFIRM</div><h2>${head}</h2><p>${body}</p><div class="row">${btn('Confirm','confirm','','gold')}${btn('Cancel','cancel')}</div>`);cancelAction=back;}
let cancelAction=()=>{};
function removeAllowed(id){let m=S.party.find(m=>m.id===id);return !!m&&S.party.length>1&&S.party.some(x=>x.id!==id&&x.hp>0)}
function teamPanel(){mode('team');refreshHUD();panel(`<button class="close" data-a="close">Back to trail</button><div class="eyebrow">YOUR COMPANIONS</div><h2>Room for every possibility</h2><p class="mini">Lead with a living partner. Training costs 45 coins per level. Evolve at Lv.5 / Lv.9; choose a lasting trait.</p><div class="grid">${S.party.map(m=>`<article class="card ${m.id===S.active?'active':''}"><span class="icon">${SPECIES[m.species].icon}</span><h3>${m.species}</h3><span class="tag">Lv.${m.level} · ${SPECIES[m.species].type} ${m.trait?'· '+m.trait:''}</span>${hpHTML(m)}<p>XP ${m.xp} / ${18+m.level*4}</p>${btn(m.id===S.active?'Leading':'Lead partner','lead',`data-id="${m.id}" ${m.hp<=0?'disabled':''}`)}${btn('Train · 45 ◈','train',`data-id="${m.id}" ${S.coins<45||m.level>=15?'disabled':''}`)}</article>`).join('')}</div><div class="row">${btn(`Eat meal · ${S.food} available`,'food',S.food<1?'disabled':'','mint')}${btn('Restart adventure','restart','','danger')}</div>`)}
function evolveNext(done){let m=S.party.find(m=>SPECIES[m.species].next&&m.level>=(SPECIES[m.species].stage===0?5:9));if(!m){done();return}mode('evolve');let old=m.species;m.species=SPECIES[old].next;m.hp=maxHP(m);tone('win',true);burst(new THREE.Vector3(0,2,0),TYPE_COLOR[SPECIES[m.species].type],35);save();panel(`<div class="eyebrow">A NEW CHAPTER</div><h2>${old} evolved into ${m.species}!</h2><p>A new silhouette. Greater strength. Choose a trait for this evolved partner.</p><div class="grid">${btn('Brave heart<small>+22 maximum HP</small>','trait','data-id="heart"','gold')}${btn('Wild spark<small>+20% attack damage</small>','trait','data-id="spark"','gold')}</div>`);evolutionChoice=t=>{m.trait=t;m.hp=maxHP(m);save();evolveNext(done)}}
let evolutionChoice=null;
function market(){mode('shop');refreshHUD();let stock=S.progress===0?[make('Flameling',3),make('Leafbit',3),make('Aquapup',3),make('Voltling',4)]:S.progress===1?[make('Pyrowhisker',6),make('Thornhare',6),make('Hydrofang',6),make('Stoneclaw',6)]:[make('Pyrostryke',9),make('Floraknight',9),make('Leviaking',9),make('Thunderbeast',9)];panel(`<button class="close" data-a="close">Back to trail</button><div class="eyebrow">THE WAYFARER MARKET · TIER ${Math.min(S.progress+1,3)}</div><h2>A catch can change your journey.</h2><p class="mini">Stronger and rarer monsters earn more. New stock unlocks after each main challenge. Buy prices are higher than resale prices.</p><div class="row">${btn('3 capture orbs · 20 ◈','orbs',S.coins<20?'disabled':'','gold')}${btn('Restorative meal · 25 ◈','buy-food',S.coins<25?'disabled':'')}</div><h3>Find a new partner</h3><div class="grid">${stock.map(m=>`<article class="card"><span class="icon">${SPECIES[m.species].icon}</span><h3>${m.species}</h3><p>Lv.${m.level} · ${SPECIES[m.species].rare?'Rare':'Companion'} · ${SPECIES[m.species].type}</p>${btn(`Buy · ${buyValue(m)} ◈`,'buy',`data-id="${m.species}" data-level="${m.level}" ${S.coins<buyValue(m)||S.party.length>=12?'disabled':''}`,'gold')}</article>`).join('')}</div><h3>Your monsters · choose carefully</h3><div class="grid">${S.party.map(m=>`<article class="card"><h3>${SPECIES[m.species].icon} ${m.species}</h3><p>Lv.${m.level} · ${m.hp>0?'Ready':'Resting'}</p>${btn(`Sell · ${sellValue(m)} ◈`,'sell',`data-id="${m.id}" ${!removeAllowed(m.id)?'disabled':''}`)}</article>`).join('')}</div><p class="muted">Your last living partner can never be sold or cooked. Maximum team: 12.</p>`)}
function kitchen(){mode('kitchen');refreshHUD();panel(`<button class="close" data-a="close">Back to trail</button><div class="eyebrow">THE LITTLE TRAIL KITCHEN</div><h2>A warm meal for the road.</h2><div class="recipe">✦ Choose one monster → confirm → receive ${'2–4'} trail meals.<br><span class="muted">The selected monster leaves permanently. A meal restores 55% HP to every living teammate and 25% HP to a fallen teammate.</span></div><div class="row">${btn(`Eat meal · ${S.food} available`,'food',S.food<1?'disabled':'','mint')}</div><div class="grid">${S.party.map(m=>`<article class="card"><h3>${SPECIES[m.species].icon} ${m.species}</h3><p>Lv.${m.level} → ${2+SPECIES[m.species].stage} meals</p>${btn('Make trail meals','cook',`data-id="${m.id}" ${!removeAllowed(m.id)?'disabled':''}`,'gold')}</article>`).join('')}</div>`)}
function eat(){if(S.food<1)return false;S.food--;S.party.forEach(m=>m.hp=Math.min(maxHP(m),m.hp+Math.ceil(maxHP(m)*(m.hp<=0?.25:.55))));save();refreshHUD();tone('grass');toast('A warm meal! Your whole team recovers.');return true}
function trailMap(){mode('map');panel(`<button class="close" data-a="close">Back to trail</button><div class="eyebrow">FOLLOW YOUR CURIOSITY</div><h2>The Wildbound trail</h2><div class="grid">${REGIONS.map((r,i)=>`<article class="card ${i===S.region?'active':''}"><span class="eyebrow">CHAPTER 0${i+1}</span><h3>${r.name}</h3><p>${r.sub}</p><p>${r.wild.join(' · ')}</p><p>Challenge: ${i===1?'Sky’s evolution duel':r.boss}</p>${btn(i===S.region?'You are here':i>S.progress?'Defeat the previous guardian':'Travel here','travel',`data-region="${i}" ${i>S.progress||i===S.region?'disabled':''}`,'gold')}</article>`).join('')}</div><p class="muted">In the world, tap a landmark to walk there, then Interact. The market and fountain are always safe.</p>`)}

// Rendering: distinct original silhouettes, shared materials, a single full-window WebGL canvas.
const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xbfdcca);scene.fog=new THREE.Fog(0xbfdcca,55,120);const camera=new THREE.PerspectiveCamera(40,1,.1,180);const ambient=new THREE.HemisphereLight(0xf4ffe4,0x557867,.65);scene.add(ambient);const sun=new THREE.DirectionalLight(0xfff0cc,.9);sun.position.set(-16,30,14);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-28,right:28,top:28,bottom:-28,near:1,far:80});sun.shadow.bias=-.001;scene.add(sun);
let world=new THREE.Group(),actors=new THREE.Group(),effects=new THREE.Group();scene.add(world,actors,effects);let player=null,follower=null,allyMesh=null,enemyMesh=null,landmarks=[],decorMonsters=[],particles=[],renderMode='title',camTarget=new THREE.Vector3(),cameraGoal=new THREE.Vector3();const materials=new Map();
function mat(color){if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.86,metalness:0,flatShading:true}));return materials.get(color)}
const geometries={sphere:new THREE.IcosahedronGeometry(1,1),round:new THREE.SphereGeometry(1,12,8),box:new THREE.BoxGeometry(1,1,1),cone:new THREE.ConeGeometry(1,1,7),cyl:new THREE.CylinderGeometry(1,1,1,12)};
function part(g,kind,color,x,y,z,sx,sy=sx,sz=sx,rz=0){let m=new THREE.Mesh(geometries[kind],mat(color));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.rotation.z=rz;m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
function monster(name,scale=1){let d=SPECIES[name],g=new THREE.Group(),c=d.color,cream=0xffe7b5,dark=0x263d3d;let big=d.stage;
 if(d.shape==='golem'||d.shape==='rock'){part(g,'sphere',c,0,1.05,0,.8,1,.65);part(g,'box',c,0,2.04,0,.85,.72,.8);for(let s of [-1,1]){part(g,'sphere',c,s*.91,1.2,0,.45,.75,.48);part(g,'box',c,s*.44,.26,0,.5,.52,.6);part(g,'box',0x9de7c4,s*.2,2.11,.42,.18,.09,.08)}part(g,'sphere',0xbaf7b6,0,1.3,.61,.25);}
 else{let dragon=d.shape==='dragon',rabbit=d.shape==='rabbit',knight=d.shape==='knight';part(g,'round',c,0,.86,0,.58,dragon?.79:.62,.7);part(g,'round',cream,0,.84,.46,.37,.44,.2);part(g,'round',c,0,1.6,.29,.63,.57,.58);part(g,'round',cream,0,1.4,.77,.35,.21,.18);part(g,'round',dark,0,1.49,.9,.09,.065,.055);
 for(let s of [-1,1]){part(g,'round',0xfffcef,s*.27,1.69,.78,.145,.17,.07);part(g,'round',dark,s*.28,1.69,.835,.075,.11,.035);part(g,'round',0xffffff,s*.3,1.73,.86,.025);part(g,'round',c,s*.4,.22,.23,.26,.22,.37);part(g,'round',c,s*.56,.86,.13,.19,.31,.22,s*-.2);let ear=part(g,rabbit?'round':'cone',c,s*.4,rabbit?2.35:2.17,.13,rabbit?.16:.24,rabbit?.72:.55,.19,s*-.17);part(g,rabbit?'round':'cone',rabbit?0xf1c3a3:cream,s*.4,rabbit?2.35:2.16,.24,rabbit?.07:.11,rabbit?.5:.31,.055,s*-.17);
 if(dragon){let wing=part(g,'cone',c,s*1.01,1.35,-.1,.64,1.45,.13,s*-.9);part(g,'cone',cream,s*1.12,1.35,0,.39,.8,.07,s*-.9);part(g,'cone',cream,s*.35,2.25,.1,.14,.65,.14,s*-.4)}if(knight)part(g,'sphere',0xe4d99e,s*.7,1.02,.05,.34,.43,.22);}
 if(d.type==='fire'){let tail=part(g,'cone',0xffb84b,.3,.72,-.87,.32,.8,.36,-.35);tail.rotation.x=-.8;part(g,'cone',0xffdf7e,.35,.86,-1.12,.22,.5,.22)}
 if(d.type==='grass'){for(let s of [-1,0,1])part(g,'cone',0x427e54,s*.2,2.1,-.12,.18,.65,.09,s*-.6)}
 if(d.type==='water'){part(g,'cone',0x9de9e5,0,1.0,-.88,.42,.68,.13,1);part(g,'cone',0x318298,0,2.14,.13,.22,.5,.1)}
 if(d.type==='electric'){for(let s of [-1,1])part(g,'box',0x986845,s*.52,1.46,.61,.17,.09,.1,.35);part(g,'cone',0xffed97,0,.8,-.86,.35,.9,.13,.5)}
 }
g.scale.setScalar(scale*(1+big*.14));g.userData={species:name,baseScale:scale*(1+big*.14),seed:Math.random()*6,hit:0,lunge:0};return g}
function trainer(){let g=new THREE.Group(),color=S?.trainer==='Sky'?0x568e67:S?.trainer==='Leo'?0x8a70a7:0x4e91a5;part(g,'box',color,0,.86,0,.49,.65,.32);part(g,'round',0xf1cda0,0,1.44,0,.31);part(g,'cyl',0xeb8765,0,1.69,0,.34,.15,.34);part(g,'box',0xeb8765,0,1.64,.25,.4,.07,.3);for(let s of [-1,1]){part(g,'box',0x385267,s*.15,.28,0,.2,.53,.21);part(g,'round',0xf1cda0,s*.34,.83,0,.1,.29,.1);part(g,'round',0x2a403b,s*.1,1.47,.28,.035)}part(g,'box',0xd5b478,0,.94,-.23,.36,.48,.24);return g}
function clearGroup(g){while(g.children.length)g.remove(g.children[0])}
function resetScene(){clearGroup(world);clearGroup(actors);clearGroup(effects);particles=[];decorMonsters=[];landmarks=[];$('#labels').innerHTML='';player=follower=allyMesh=enemyMesh=null;}
function ground(color){part(world,'cyl',0x62785f,0,-1.15,0,26,2,23);part(world,'cyl',color,0,-.15,0,26,.55,23);}
function tree(x,z,s=1){let g=new THREE.Group();part(g,'cyl',0x806747,0,.8,0,.16,1.7,.16);part(g,'sphere',0x4e9174,0,2.1,0,.95,1.1,.9);part(g,'sphere',0x80b183,.38,2.45,.12,.62,.65,.6);g.position.set(x,0,z);g.scale.setScalar(s);world.add(g)}
function rock(x,z,s=1,c=0xa0a48c){let m=part(world,'sphere',c,x,s*.35,z,s,.65*s,.85*s);m.rotation.y=x;}
function path(x,z,tx,tz){let n=Math.ceil(Math.hypot(tx-x,tz-z));for(let i=0;i<=n;i++)part(world,'cyl',0xe0cf9f,x+(tx-x)*i/n,.02,z+(tz-z)*i/n,1.18,.06,1.18)}
function building(x,z,kind){let g=new THREE.Group();if(kind==='heal'){part(g,'cyl',0xe9dcc0,0,.2,0,1.5,.5,1.5);part(g,'cyl',0x7bddcc,0,.49,0,1.18,.12,1.18);part(g,'cyl',0xdbd7b3,0,1,0,.28,1.1,.28);part(g,'sphere',0x97efc6,0,1.8,0,.4);}
 else if(kind==='boss'){for(let s of [-1,1])part(g,'box',0xc2ba96,s*1.65,1.8,0,.72,3.6,.9);part(g,'box',0xe1d3a9,0,3.5,0,4,.55,1);part(g,'sphere',0xffd778,0,3.8,0,.3);}
 else{part(g,'box',0xf2ddba,0,1,0,2.9,2,2);let roof=part(g,'cone',kind==='shop'?0xe28d67:0xe2b35c,0,2.5,0,2.3,1.4,1.75);roof.rotation.y=Math.PI/4;part(g,'box',0x476853,0,.85,1.04,.7,1.5,.1);for(let s of [-1,1])part(g,'box',0xa3daca,s*.95,1.2,1.05,.5,.6,.1);part(g,'box',0xa8784f,0,.55,1.8,3,.22,.8);for(let s of [-1,0,1])part(g,'sphere',kind==='shop'?0xffc96b:0x95bd65,s*.8,.86,1.8,.26);}
g.position.set(x,0,z);world.add(g)}
function addLand(id,label,x,z,kind,species){let p={id,label,x,z,kind,species};landmarks.push(p);if(['shop','heal','kitchen','boss'].includes(kind))building(x,z,kind);if(species){let m=monster(species,kind==='boss'?1.15:.7);m.position.set(x,.03,z+(kind==='boss'?1.8:0));world.add(m);decorMonsters.push(m)}let b=document.createElement('button');b.className='landmark';b.innerHTML=label;b.dataset.land=id;$('#labels').appendChild(b);p.el=b;}
function makeWorld(){resetScene();renderMode='world';let r=REGIONS[S.region];scene.background.setHex(r.sky);scene.fog.color.setHex(r.sky);ground(r.color);path(0,9,0,-12);path(0,5,-9,5);path(0,4,9,5);path(0,0,-10,-4);path(0,-3,10,-5);path(0,8,8,10);
for(let i=0;i<32;i++){let a=i*2.399,x=Math.cos(a)*(17+(i%3)*2),z=Math.sin(a)*(15+(i%4));if(S.region===0)tree(x,z,.9+(i%3)*.2);else rock(x,z,1.2+i%4,r.hill)}
for(let i=0;i<65;i++){let x=Math.sin(i*73.2)*16,z=Math.cos(i*21.3)*14;if(Math.abs(x)<2||landmarks.some(p=>Math.hypot(x-p.x,z-p.z)<3))continue;part(world,'cone',S.region===2?0xc1b5df:0xc4d99a,x,.22,z,.13,.48,.13);if(i%4===0)part(world,'sphere',i%8?0xffe7a2:0xeea888,x,.49,z,.16)}
part(world,'cyl',0x6abcb2,-11,.015,10,3.2,.08,2);rock(-13,11,.8);rock(-9,12,.7);addLand('shop','◈ MARKET',-9,5,'shop');addLand('heal','✦ HEALING SPRING',8,10,'heal');addLand('kitchen','♨ TRAIL KITCHEN',9,5,'kitchen');addLand('wild','♧ HUNTING GLADE',-10,-4,'wild',r.wild[S.hunts%r.wild.length]);addLand('rare','✧ RARE TRACKS',10,-5,'rare',S.region===0?'Voltling':S.region===1?'Thornhare':'Thunderbeast');addLand('boss',S.region===1?'⚑ SKY’S DUEL':`⚑ ${r.boss.toUpperCase()}`,0,-12,'boss',r.boss);addLand('cache','✦ SUPPLY CACHE',-16,2,'cache');
player=trainer();player.position.set(S.pos.x,0,S.pos.z);actors.add(player);follower=monster(active().species,.49);follower.position.copy(player.position).add(new THREE.Vector3(-1.3,0,1));actors.add(follower);cameraGoal.set(22,29,34);camTarget.set(0,0,-1);camera.position.copy(cameraGoal);camera.lookAt(camTarget);resize();}
function makeTitle(){resetScene();renderMode='title';ground(0xa3c385);scene.background.setHex(0xbfdcca);scene.fog.color.setHex(0xbfdcca);for(let i=0;i<12;i++)tree(Math.cos(i)*16,Math.sin(i)*13,1.4);['Flameling','Leafbit','Aquapup'].forEach((n,i)=>{let m=monster(n,1.55);m.position.set(2+i*3.3,0,1+(i===1?-2:0));m.rotation.y=-.4;actors.add(m);decorMonsters.push(m)});camera.position.set(20,12,25);camTarget.set(1,1,0);camera.lookAt(camTarget);resize();}
function makeArena(){resetScene();renderMode='battle';ground(REGIONS[S.region].color);part(world,'cyl',0xc5bd99,0,.015,0,9,.12,7);for(let i=0;i<12;i++){if(S.region===0)tree(Math.cos(i)*15,Math.sin(i)*12,1.3);else rock(Math.cos(i)*15,Math.sin(i)*13,2,REGIONS[S.region].hill)}allyMesh=monster(active().species,1.25);allyMesh.position.set(-3.7,0,1.7);allyMesh.rotation.y=.8;enemyMesh=monster(battle.enemy.species,battle.boss?1.6:1.2);enemyMesh.position.set(3.6,0,-1);enemyMesh.rotation.y=-.8;actors.add(allyMesh,enemyMesh);player=trainer();player.position.set(-6,0,4);player.rotation.y=.8;actors.add(player);camera.position.set(13,10,21);camTarget.set(0,1,0);camera.lookAt(camTarget);resize();}
function syncAlly(){if(!allyMesh)return;actors.remove(allyMesh);allyMesh=monster(active().species,1.25);allyMesh.position.set(-3.7,0,1.7);allyMesh.rotation.y=.8;actors.add(allyMesh)}
function burst(pos,color,count=20){for(let i=0;i<count;i++){let m=part(effects,'sphere',color,pos.x,pos.y,pos.z,.08+Math.random()*.11);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*6,2+Math.random()*4,(Math.random()-.5)*6),life:1})}}
function projectile(from,to,type,strong){let color=TYPE_COLOR[type];for(let i=0;i<(strong?28:13);i++){let m=part(effects,type==='electric'?'box':type==='water'?'round':'sphere',color,from.x,from.y+1.3,from.z,.12,.12,.12);particles.push({m,from:from.clone().add(new THREE.Vector3(0,1.3,0)),to:to.clone().add(new THREE.Vector3((Math.random()-.5)*.8,1.3+(Math.random()-.5)*.8,0)),life:1,flight:true,delay:i*.015})}}
function floater(text,side='enemy'){let d=document.createElement('div');d.className='floater '+side;d.textContent=text;$('#floaters').appendChild(d);setTimeout(()=>d.remove(),1100)}
function resize(){let w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=w<h?(renderMode==='world'?62:57):40;camera.updateProjectionMatrix();}
addEventListener('resize',resize);
let last=performance.now(),saveClock=0;
function animate(now){requestAnimationFrame(animate);let dt=Math.min((now-last)/1000,.045),t=now/1000;last=now;
if(state==='explore'&&player){let dx=(keys.right?1:0)-(keys.left?1:0),dz=(keys.down?1:0)-(keys.up?1:0);if(dx||dz)walkTarget=null;if(walkTarget){let v=new THREE.Vector2(walkTarget.x-player.position.x,walkTarget.z-player.position.z);if(v.length()<1.8){walkTarget=null}else{dx=v.x/v.length();dz=v.y/v.length()}}let len=Math.hypot(dx,dz);if(len){let speed=7.5*dt/Math.max(1,len);player.position.x=THREE.MathUtils.clamp(player.position.x+dx*speed,-18,18);player.position.z=THREE.MathUtils.clamp(player.position.z+dz*speed,-14,14);player.rotation.y=Math.atan2(dx,dz);player.position.y=Math.abs(Math.sin(t*12))*.09;S.pos={x:player.position.x,z:player.position.z};saveClock+=dt;if(saveClock>1){save();saveClock=0}}else player.position.y=0;follower.position.lerp(new THREE.Vector3(player.position.x-1.2,0,player.position.z+1),Math.min(1,dt*4));follower.rotation.y=player.rotation.y;follower.position.y=Math.abs(Math.sin(t*6))*.1;near=landmarks.find(p=>Math.hypot(player.position.x-p.x,player.position.z-p.z)<3);$('#nearby').textContent=near?near.label.replace(/<[^>]+>/g,'')+' · ready to interact':'Tap a landmark to walk there · explore at your own pace';$('#interact').disabled=!near;
landmarks.forEach(p=>{let v=new THREE.Vector3(p.x,3.8,p.z).project(camera);p.el.style.left=(v.x*.5+.5)*innerWidth+'px';p.el.style.top=(-v.y*.5+.5)*innerHeight+'px';p.el.style.display=v.z<1?'':'none'});}
for(let m of [...decorMonsters,allyMesh,enemyMesh].filter(Boolean)){let u=m.userData;m.position.y=Math.sin(t*2.7+u.seed)*.07;let scale=u.baseScale;m.scale.set(scale,scale*(1+Math.sin(t*2.7+u.seed)*.018),scale);if(u.hit>0){m.rotation.z=Math.sin(t*45)*u.hit*.15;u.hit=Math.max(0,u.hit-dt*2.5)}else m.rotation.z=0;if(u.lunge>0){m.position.x+=(m===allyMesh?1:-1)*Math.sin(u.lunge*Math.PI)*dt*6;u.lunge=Math.max(0,u.lunge-dt*3)}if(u.downed)m.rotation.z=1.3;}
particles=particles.filter(p=>{p.life-=dt;if(p.flight){let k=Math.max(0,Math.min(1,(1-p.life-p.delay)*2.4));p.m.position.lerpVectors(p.from,p.to,k);p.m.scale.setScalar(.1+Math.sin(k*Math.PI)*.12)}else{p.m.position.addScaledVector(p.v,dt);p.v.y-=8*dt;p.m.scale.multiplyScalar(.985)}if(p.life<=0){effects.remove(p.m);return false}return true});renderer.render(scene,camera);}
requestAnimationFrame(animate);

// Explicit turn ownership + encounter token: stale asynchronous turns cannot affect another battle.
function advantage(a,b){if(({fire:['grass'],grass:['water','rock'],water:['fire','rock'],electric:['water'],rock:['electric','fire']}[a]||[]).includes(b))return 1.5;if(({fire:['water','rock'],grass:['fire'],water:['grass','electric'],electric:['rock'],rock:['grass','water']}[a]||[]).includes(b))return .7;return 1}
function combatUI(message){if(!battle)return;let m=active(),e=battle.enemy;$('#ally-card').innerHTML=`<small>Lv.${m.level} · ${SPECIES[m.species].type}</small><b>${m.species}</b>${hpHTML(m)}<p class="muted">${S.trainer} · Energy ${battle.energy}/3</p>`;$('#enemy-card').innerHTML=`<small>Lv.${e.level} · ${SPECIES[e.species].type}</small><b>${e.species}</b>${hpHTML(e)}<p class="muted">${battle.boss?(battle.phase===2?'AWAKENED · PHASE II':S.region===1?'SKY’S EVOLVED PARTNER':'GUARDIAN'):`Capture chance: ${e.hp<=maxHP(e)*.5?'100%':'25% — weaken first'}`}</p>`;if(message)$('#battle-log').textContent=message;
$('#commands').innerHTML=btn('Quick strike<small>Build +1 energy</small>','attack',state!=='battle'?'disabled':'')+btn(`${SPECIES[m.species].icon} ${m.level>=5?'Power burst':'Element pulse'}<small>${m.level>=5?'2':'1'} energy · ${SPECIES[m.species].type}</small>`,'skill',state!=='battle'||battle.energy<(m.level>=5?2:1)?'disabled':'','gold')+btn(`Capture<small>${S.capsules} orbs · weaken to 50%</small>`,'capture',state!=='battle'||battle.boss||S.capsules<1||S.party.length>=12?'disabled':'')+btn('Switch<small>Living partners only</small>','switch',state!=='battle'?'disabled':'')+btn(`Meal<small>${S.food} · restores team</small>`,'battle-food',state!=='battle'||S.food<1?'disabled':'')+btn('Retreat<small>Keep your progress</small>','run',state!=='battle'?'disabled':'');}
function beginBattle(rare=false,boss=false){if(state!=='explore'||!S.party.some(m=>m.hp>0))return;mode('encounter');save();let r=REGIONS[S.region],species=boss?r.boss:rare?(S.region===0?'Voltling':S.region===1?'Thornhare':'Thunderbeast'):r.wild[S.hunts%r.wild.length],level=boss?r.level:rare?4+S.region*3:2+S.region*3+(S.hunts%2);let enemy=make(species,level);if(boss){enemy.hp+=25;enemy.bonus=25}battle={id:++battleSerial,enemy,boss,rare,phase:1,energy:2,turn:0};S.hunts++;mode('battle');makeArena();combatUI(boss?(S.region===1?'Sky: “Show me how you and your partners have grown!”':'A guardian blocks the trail. Prepare your team!'):'A wild '+species+' appeared! Weaken it to half HP for a guaranteed capture.');tone('select');}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function valid(id){return battle?.id===id&&battleSerial===id&&['acting','battle','switch'].includes(state)}
async function hit(attacker,defender,strong,enemy=false){let id=battle.id,type=strong?SPECIES[attacker.species].type:'rock',a=enemy?enemyMesh:allyMesh,d=enemy?allyMesh:enemyMesh;combatUI(`${enemy?attacker.species:S.trainer+': “'+attacker.species+'!”'} ${strong?'unleashes an elemental burst':'uses Quick strike'}!`);a.userData.lunge=1;tone(type,strong);projectile(a.position,d.position,type,strong);await wait(420);if(!valid(id))return false;let mult=strong?advantage(SPECIES[attacker.species].type,SPECIES[defender.species].type):1;let damage=Math.round((5+attacker.level*2+SPECIES[attacker.species].stage*4)*(strong?1.7:1)*mult*(attacker.trait==='spark'?1.2:1)*(enemy?.83:1));defender.hp=Math.max(0,defender.hp-damage);d.userData.hit=1;burst(d.position.clone().add(new THREE.Vector3(0,1.2,0)),TYPE_COLOR[type],strong?24:12);floater('-'+damage,enemy?'ally':'enemy');combatUI(`${damage} damage${mult>1?' · Super effective!':mult<1?' · Resisted.':'.'}${defender.hp===0?' '+defender.species+' is resting.':''}`);if(defender.hp===0)d.userData.downed=true;await wait(470);return valid(id)}
async function turn(action){if(state!=='battle'||!battle)return;let id=battle.id,m=active();if(action==='skill'&&battle.energy<(m.level>=5?2:1))return;if(action==='capture'&&(battle.boss||S.capsules<1||S.party.length>=12))return;if(action==='battle-food'&&S.food<1)return;mode('acting');combatUI();
if(action==='attack'||action==='skill'){let strong=action==='skill';battle.energy=strong?battle.energy-(m.level>=5?2:1):Math.min(3,battle.energy+1);if(!await hit(m,battle.enemy,strong))return;if(battle.enemy.hp<=0){if(battle.boss&&S.region===2&&battle.phase===1){battle.phase=2;battle.enemy.hp=maxHP(battle.enemy);battle.enemy.level+=1;enemyMesh.userData.downed=false;enemyMesh.userData.baseScale*=1.18;burst(enemyMesh.position.clone().add(new THREE.Vector3(0,2,0)),0xd3afff,50);floater('AWAKENED!');combatUI('Stormjaw awakens! Phase II — use meals and switch wisely.');tone('electric',true);await wait(850);if(!valid(id))return}else{await victory(false);return}}}
else if(action==='capture'){S.capsules--;let caught=battle.enemy.hp<=maxHP(battle.enemy)*.5||Math.random()<.25;combatUI('Capture orb — hold steady…');projectile(allyMesh.position,enemyMesh.position,'grass',true);tone('grass');await wait(700);if(!valid(id))return;if(caught){let caughtM=make(battle.enemy.species,battle.enemy.level);S.party.push(caughtM);S.stats.captures++;burst(enemyMesh.position.clone().add(new THREE.Vector3(0,1,0)),0xffdc7a,40);floater('CAUGHT!');await victory(true);return}else combatUI('It escaped the orb! Lower its HP before trying again.');}
else if(action==='battle-food'){eat();combatUI('The team shares a restorative trail meal.');await wait(350);if(!valid(id))return;}
else if(action==='run'){battleSerial++;enterWorld();toast('Back on the trail. Your progress is safe.');return;}
save();await enemyTurn(id);}
async function enemyTurn(id){if(!valid(id))return;mode('acting');battle.turn++;let strong=battle.turn%3===0||battle.phase===2&&battle.turn%2===0;if(!await hit(battle.enemy,active(),strong,true))return;if(active().hp<=0){let living=S.party.filter(m=>m.hp>0);if(!living.length){lose();return}mode('switch');switchPanel(true);save();return}mode('battle');combatUI(strong?'The enemy spent its burst. Your turn.':battle.turn%3===2?'The enemy is gathering power. A burst is coming next turn!':'Your turn. Attack, capture, switch or recover.');save();}
async function victory(captured){let b=battle,id=b.id;S.stats.wins++;let reward=b.boss?110+b.enemy.level*8:14+b.enemy.level*5;S.coins+=reward;let xp=14+b.enemy.level*6;S.party.filter(m=>m.hp>0).forEach(m=>{m.xp+=xp;while(m.xp>=18+m.level*4&&m.level<15){m.xp-=18+m.level*4;m.level++;m.hp=Math.min(maxHP(m),m.hp+24)}});if(b.boss&&S.progress===S.region)S.progress=Math.min(3,S.progress+1);combatUI(`${captured?'Caught '+b.enemy.species:'Victory'}! +${reward} coins · +${xp} team XP`);tone('win',true);save();await wait(700);if(!valid(id))return;battleSerial++;battle=null;evolveNext(()=>{enterWorld();dialogue(captured?'A new possibility':b.boss?'The trail opens':'Stronger together',`${captured?b.enemy.species+' joined your team. Keep it, sell it at the market, or choose to make meals. ':''}+${reward} coins and ${xp} XP for living partners.${b.boss?(S.progress===3?' You defeated awakened Stormjaw — you are the Wildbound champion!':' New market stock and the next region are unlocked on the Trail map.'):''}`,()=>enterWorld())});}
function lose(){battleSerial++;battle=null;S.stats.losses++;S.party.forEach(m=>m.hp=maxHP(m));S.pos={x:8,z:9};save();enterWorld();dialogue('A fresh start at the spring','The trail keeper restored your whole team. You kept every monster, coin and level. Train, pack meals, or try a different element — then challenge again.',()=>enterWorld());}
function switchPanel(forced=false){mode('switch');panel(`<div class="eyebrow">${forced?'YOUR PARTNER NEEDS REST':'TACTICAL SWITCH'}</div><h2>Who takes the lead?</h2><p>A voluntary switch uses your turn. Fallen partners cannot be selected.</p><div class="grid">${S.party.map(m=>`<article class="card"><h3>${m.species} · Lv.${m.level}</h3>${hpHTML(m)}${btn(m.hp<=0?'Resting':m.id===S.active?'On the field':'Choose','battle-switch',`data-id="${m.id}" data-forced="${forced}" ${m.hp<=0||m.id===S.active?'disabled':''}`,'gold')}</article>`).join('')}</div>${forced?'':btn('Back','back-battle')}`)}
function interact(){if(state!=='explore'||!near)return;tone();if(near.kind==='shop')market();else if(near.kind==='kitchen')kitchen();else if(near.kind==='heal'){S.party.forEach(m=>m.hp=maxHP(m));save();refreshHUD();burst(player.position,0x9cf0cf,30);toast('The spring restores and revives every partner.')}else if(near.kind==='wild')beginBattle();else if(near.kind==='rare')beginBattle(true);else if(near.kind==='boss'){if(S.progress>S.region){toast('Guardian cleared! Use the Trail map to continue.');return}beginBattle(false,true)}else if(near.kind==='cache'){let k='cache'+S.region;if(S.claims[k])toast('You already collected this cache. Hunt monsters to earn more.');else{S.claims[k]=true;S.coins+=45;S.capsules+=3;S.food++;save();refreshHUD();toast('Supply cache: +45 coins, +3 capture orbs, +1 meal!')}}}

// All UI actions have an allowed source state. Transactions are synchronous and revalidated.
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.land){if(state==='explore'){let p=landmarks.find(p=>p.id===b.dataset.land);walkTarget={x:p.x,z:p.z};toast('Walking to '+p.label+' · press E / Interact on arrival')}return}let a=b.dataset.a,id=b.dataset.id;tone();
if(a==='continue'&&state==='title'){S=readSave();if(S){normalize();enterWorld()}return}if(a==='new'&&state==='title'){if(readSave())confirmation('Start a new adventure?','This replaces only the V2 save. Your V1 save is untouched.',()=>choose(),()=>title());else choose();return}if(a==='title'&&state==='choose'){title();return}if(a==='trainer'&&state==='choose'){chosenTrainer=id;choose();return}if(a==='starter'&&state==='choose'&&['Flameling','Leafbit','Aquapup'].includes(id)){start(id);return}if(a==='story-next'&&state==='story'){let f=confirmAction;confirmAction=null;f?.();return}if(a==='confirm'&&state==='confirm'){let f=confirmAction;confirmAction=null;f?.();return}if(a==='cancel'&&state==='confirm'){cancelAction();return}if(a==='trait'&&state==='evolve'){let f=evolutionChoice;evolutionChoice=null;f?.(id);return}
if(a==='close'&&['team','shop','map','kitchen'].includes(state)){enterWorld();return}if(a==='travel'&&state==='map'){let r=+b.dataset.region;if(r>=0&&r<=Math.min(2,S.progress)){S.region=r;S.pos={x:0,z:7};enterWorld()}return}
if(a==='lead'&&state==='team'){let m=S.party.find(m=>m.id===id&&m.hp>0);if(m){S.active=id;save();teamPanel()}return}if(a==='train'&&state==='team'){let m=S.party.find(m=>m.id===id);if(m&&S.coins>=45&&m.level<15){S.coins-=45;m.level++;m.hp=Math.min(maxHP(m),m.hp+25);save();evolveNext(()=>teamPanel())}return}if(a==='restart'&&state==='team'){confirmation('Restart V2?','Your current V2 team, coins and journey will be replaced after you select a new partner.',()=>choose(),()=>teamPanel());return}
if(a==='food'&&['team','kitchen'].includes(state)){let s=state;if(eat())s==='team'?teamPanel():kitchen();return}
if(state==='shop'){if(a==='buy'){let level=+b.dataset.level,allowed=S.progress===0?['Flameling','Leafbit','Aquapup','Voltling']:S.progress===1?['Pyrowhisker','Thornhare','Hydrofang','Stoneclaw']:['Pyrostryke','Floraknight','Leviaking','Thunderbeast'];let expected=S.progress===0?(id==='Voltling'?4:3):S.progress===1?6:9;if(!allowed.includes(id)||level!==expected)return;let m=make(id,level),price=buyValue(m);if(S.coins>=price&&S.party.length<12){S.coins-=price;S.party.push(m);S.stats.bought++;save();market();toast(m.species+' joined your team!')}return}if(a==='orbs'&&S.coins>=20){S.coins-=20;S.capsules+=3;save();market();return}if(a==='buy-food'&&S.coins>=25){S.coins-=25;S.food++;save();market();return}if(a==='sell'&&removeAllowed(id)){let m=S.party.find(m=>m.id===id);confirmation('Sell '+m.species+'?',`This Lv.${m.level} monster will leave permanently. Receive ${sellValue(m)} coins.`,()=>{if(removeAllowed(id)){S.coins+=sellValue(m);S.party=S.party.filter(x=>x.id!==id);normalize();S.stats.sold++;save()}market()},()=>market());return}}
if(a==='cook'&&state==='kitchen'&&removeAllowed(id)){let m=S.party.find(m=>m.id===id);confirmation('Turn '+m.species+' into meals?',`This permanently consumes the selected monster and creates ${2+SPECIES[m.species].stage} restorative meals. It cannot be undone.`,()=>{if(removeAllowed(id)){S.food+=2+SPECIES[m.species].stage;S.party=S.party.filter(x=>x.id!==id);normalize();S.stats.cooked++;save();toast('✦ A little sparkle… your trail meals are ready!')}kitchen()},()=>kitchen());return}
if(['attack','skill','capture','battle-food','run'].includes(a)&&state==='battle'){await turn(a);return}if(a==='switch'&&state==='battle'){switchPanel();return}if(a==='back-battle'&&state==='switch'){if(active().hp<=0)return;$('#overlay').innerHTML='';mode('battle');combatUI();return}if(a==='battle-switch'&&state==='switch'){let m=S.party.find(m=>m.id===id&&m.hp>0);if(!m||m.id===S.active)return;let forced=active().hp<=0;S.active=id;save();$('#overlay').innerHTML='';syncAlly();if(forced){mode('battle');combatUI(m.species+' takes the field!')}else{mode('acting');combatUI(m.species+' takes the field!');await enemyTurn(battle.id)}return}
});
$('#team').onclick=()=>{if(state==='explore')teamPanel()};$('#map').onclick=()=>{if(state==='explore')trailMap()};$('#interact').onclick=interact;$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'♪ Muted':'♪ Sound';if(!muted)tone()};
const keymap={w:'up',ArrowUp:'up',s:'down',ArrowDown:'down',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right'};
addEventListener('keydown',e=>{let k=keymap[e.key]||keymap[e.key.toLowerCase()];if(k){e.preventDefault();if(state==='explore')keys[k]=true}if(e.key.toLowerCase()==='e'&&!e.repeat)interact()});addEventListener('keyup',e=>{delete keys[keymap[e.key]||keymap[e.key.toLowerCase()]]});
$$('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(state!=='explore')return;b.setPointerCapture(e.pointerId);keys[b.dataset.dir]=true});for(let ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>{delete keys[b.dataset.dir]})});
addEventListener('blur',()=>{keys={};walkTarget=null;save()});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};walkTarget=null;save()}});addEventListener('pagehide',save);
// Read-only diagnostics for reproducible QA; no gameplay mutation or cheat controls.
window.MQ={snapshot:()=>JSON.parse(JSON.stringify({state,save:S,battle,position:player?{x:player.position.x,z:player.position.z}:null,renderer:renderer.info.render,version:'2.0.0'})),storageKey:KEY};
title();
