(()=>{const claude=location.pathname.includes('kehan-claude');document.body.classList.toggle('claude-flight',claude);let en=new URLSearchParams(location.search).get('lang')==='en';const bar=document.createElement('div');bar.id='devicebar';bar.setAttribute('role','toolbar');bar.setAttribute('aria-orientation','vertical');bar.innerHTML='<a id="kitHome">HUB</a><button id="kitLanguage"></button><button id="kitFullscreen">Full</button><button id="kitPause">Pause</button>';document.body.append(bar);document.querySelector('#kitHome').href='../'+(location.pathname.includes('harrison-zavier')?'harrison-zavier':'kehan')+'-hub.html';const notice=document.createElement('div');notice.id='deviceNotice';notice.hidden=true;document.body.append(notice);const pauseView=document.createElement('div');pauseView.id='devicePause';pauseView.hidden=true;pauseView.innerHTML='<strong></strong><button></button>';document.body.append(pauseView);let oldLanguage=null;
function refresh(){if(claude)en=window.CLAUDE_LANG?.language==='en';else if(window.__reviewLanguage)en=__reviewLanguage.language==='en';bar.setAttribute('aria-label',en?'Game tools':'游戏工具栏');document.querySelector('#kitLanguage').textContent=en?'中文':'EN';document.querySelector('#kitFullscreen').textContent=en?'Full':'全屏';document.querySelector('#kitPause').textContent=en?'Pause':'暂停';pauseView.querySelector('strong').textContent=en?'Adventure paused':'冒险已暂停';pauseView.querySelector('button').textContent=en?'Resume':'继续';}
function state(){if(claude)return !!window.GAME?.paused;if(window.kehan)return kehan.snapshot().paused;return window.__soloEngine?.state==='paused';}
function setPause(value){if(claude){window.GAME?.setPaused(value);pauseView.hidden=!window.GAME?.paused;}else if(window.kehan)kehan.setPaused(value);else{const g=window.__soloEngine;if(g&&value!==state()&&['paused','playing','treasure'].includes(g.state))document.querySelector('#pause')?.click();}}
document.querySelector('#kitPause').onclick=()=>{setPause(!state());refresh();};pauseView.querySelector('button').onclick=()=>setPause(false);
document.querySelector('#kitLanguage').onclick=()=>{if(claude)window.CLAUDE_LANG?.toggle();else{oldLanguage=oldLanguage||document.querySelector('#review-tools button');oldLanguage?.click();}refresh();};
document.querySelector('#kitFullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else throw Error('unsupported');}catch{notice.textContent=en?'Fullscreen is optional. Safari: Share, Add to Home Screen. Direct browser play also works.':'全屏不是运行条件。Safari 可用分享、添加到主屏幕，也可直接在浏览器里玩。';notice.hidden=false;setTimeout(()=>notice.hidden=true,7000);}};
function size(){document.documentElement.style.setProperty('--device-height',((window.visualViewport?.height)||innerHeight)+'px');}
size();addEventListener('resize',size);if(window.visualViewport)visualViewport.addEventListener('resize',()=>{size();dispatchEvent(new Event('resize'));});
for(const event of ['blur','pagehide'])addEventListener(event,()=>setPause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)setPause(true);});
const findOld=()=>{const panel=document.querySelector('#review-tools');if(panel){oldLanguage=panel.querySelector('button');panel.style.display='none';}refresh();};findOld();addEventListener('load',findOld,{once:true});
let lastPaused=null;setInterval(()=>{if(claude&&state()!==lastPaused){lastPaused=state();pauseView.hidden=!lastPaused;refresh();}},200);window.__deviceKit={setPause,state,refresh};})();