const {chromium}=require('C:/GemstoneKingdom/Prism/ai-bounty-board/games/lisha-quentin/cooperation/coral-crew/game/node_modules/playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'), report={started:new Date().toISOString(),checks:[],errors:[],notes:['Headless Chromium with software WebGL; not physical iPad or human acceptance.']};
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end('missing')}});
let browser;
const check=(name,details)=>{report.checks.push({name,details});console.log('PASS '+name)};
(async()=>{await new Promise(r=>server.listen(8786,'127.0.0.1',r));try{
browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:8786/');await p.waitForFunction(()=>window.MQ);await p.screenshot({path:path.join(__dirname,'01-title.png')});const persisted={v:2,trainer:'Martin',party:[{id:'one',species:'Leafbit',level:3,xp:0,trait:null,hp:67},{id:'two',species:'Flameling',level:3,xp:0,trait:null,hp:67}],active:'one',coins:110,food:1,capsules:8,region:0,progress:0,pos:{x:0,z:7},hunts:0,claims:{},stats:{captures:0,sold:0,cooked:0,bought:0,wins:0,losses:0}};const snap=()=>p.evaluate(()=>MQ.snapshot());async function closeStory(){if((await snap()).state==='story')await p.locator('[data-a=story-next]').click()}
// Clearly separate boundary fixture; never counted as ordinary progression.
let fixture=structuredClone(persisted);fixture.party.forEach(m=>m.hp=1);fixture.pos={x:-10,z:-2};await p.addInitScript(x=>localStorage.setItem('martin-monster-quest-v2-wildbound-1',JSON.stringify(x)),fixture);await p.reload();await p.locator('[data-a=continue]').click();await p.locator('#interact').click();await p.locator('[data-a=attack]').click();await p.waitForTimeout(2100);assert.equal((await snap()).state,'switch');assert(await p.locator('[data-a=battle-switch]:disabled').count()>=1);check('Boundary fixture: cannot switch to fallen partner');await p.locator('[data-a=battle-switch]:not(:disabled)').click();await p.locator('[data-a=attack]').click();await p.waitForTimeout(2200);assert.equal((await snap()).state,'story');assert((await snap()).save.party.every(m=>m.hp>0));assert.equal((await snap()).save.coins,persisted.coins);check('Boundary fixture: full defeat revives team without lost coins');await closeStory();
await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(__dirname,'05-portrait.png')});assert(await p.locator('#interact').isVisible());await p.locator('#team').click();await p.locator('[data-a=close]').click();check('Portrait buttons and return usable');await p.setViewportSize({width:1180,height:820});await p.screenshot({path:path.join(__dirname,'06-tablet.png')});check('Tablet viewport rendered (not real iPad)');assert.deepEqual(report.errors,[]);check('No browser JavaScript errors');report.status='passed';
}catch(e){report.status='failed';report.failure=e.stack;console.error(e)}finally{report.ended=new Date().toISOString();await browser?.close();await new Promise(r=>server.close(r));report.cleanup='Task browser and HTTP server closed';fs.writeFileSync(path.join(__dirname,'boundary-results.json'),JSON.stringify(report,null,2))}})();
