const {chromium}=require('C:/GemstoneKingdom/Prism/ai-bounty-board/games/lisha-quentin/cooperation/coral-crew/game/node_modules/playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'), report={started:new Date().toISOString(),checks:[],errors:[],notes:['Headless Chromium with software WebGL; not physical iPad or human acceptance.']};
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end('missing')}});
let browser;
const check=(name,details)=>{report.checks.push({name,details});console.log('PASS '+name)};
(async()=>{await new Promise(r=>server.listen(8786,'127.0.0.1',r));try{
browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:8786/');await p.waitForFunction(()=>window.MQ);await p.screenshot({path:path.join(__dirname,'01-title.png')});await p.locator('[data-a=new]').click();await p.screenshot({path:path.join(__dirname,'02-partners.png')});await p.locator('[data-a=starter][data-id=Leafbit]').click();
const snap=()=>p.evaluate(()=>MQ.snapshot());let before=await snap();await p.keyboard.down('w');await p.waitForTimeout(180);await p.keyboard.up('w');assert.deepEqual((await snap()).position,before.position);check('Story blocks keyboard movement');await p.locator('[data-a=story-next]').click();
before=await snap();await p.keyboard.down('d');await p.waitForTimeout(250);await p.keyboard.up('d');assert((await snap()).position.x>before.position.x);check('Keyboard movement');
await p.locator('[data-dir=left]').dispatchEvent('pointerdown',{pointerId:44,pointerType:'touch',bubbles:true});await p.waitForTimeout(200);await p.locator('[data-dir=left]').dispatchEvent('pointercancel',{pointerId:44,pointerType:'touch'});let stopped=(await snap()).position;await p.waitForTimeout(150);assert.deepEqual((await snap()).position,stopped);check('Touch direction + pointercancel stops movement (synthetic pointer)');
async function go(id){await p.locator(`[data-land=${id}]`).click();await p.waitForFunction(id=>{const a=MQ.snapshot();const coords={wild:[-10,-4],shop:[-9,5],heal:[8,10],kitchen:[9,5],boss:[0,-12]};return a.position&&Math.hypot(a.position.x-coords[id][0],a.position.z-coords[id][1])<2},id,{timeout:12000});await p.locator('#interact').click()}
async function closeStory(){if((await snap()).state==='story')await p.locator('[data-a=story-next]').click()}
async function capture(){await go('wild');let pos=(await snap()).position;await p.keyboard.down('d');await p.waitForTimeout(150);await p.keyboard.up('d');assert.deepEqual((await snap()).position,pos);for(let n=0;n<15;n++){let s=await snap();if(s.state==='story'){await closeStory();return}if(s.state==='evolve'){await p.locator('[data-a=trait]').first().click();continue}if(s.state==='battle'){let e=s.battle.enemy,hp=40+e.level*9;await p.locator(e.hp<=hp*.5?'[data-a=capture]':'[data-a=attack]').click()}await p.waitForTimeout(1050)}throw Error('Capture loop timed out')}
await capture();check('Real battle, damage, capture, battle movement lock',(await snap()).save.stats);await p.screenshot({path:path.join(__dirname,'03-world.png')});await go('heal');await capture();check('Second normal capture');
await go('shop');let s=await snap(),sell=s.save.party[1],coins=s.save.coins;await p.locator(`[data-a=sell][data-id="${sell.id}"]`).click();await p.locator('[data-a=confirm]').click();assert((await snap()).save.coins>coins);assert(!(await snap()).save.party.some(m=>m.id===sell.id));check('Confirmed sale changes coins and removes exact monster');
coins=(await snap()).save.coins;await p.locator('[data-a=buy][data-id=Flameling]').click();assert((await snap()).save.coins<coins);check('Purchase subtracts coins and adds playable monster');await p.locator('[data-a=close]').click();await go('kitchen');s=await snap();const food=s.save.food,cook=s.save.party.find(m=>m.species==='Aquapup');await p.locator(`[data-a=cook][data-id="${cook.id}"]`).click();await p.locator('[data-a=confirm]').click();assert((await snap()).save.food===food+2);await p.locator('[data-a=food]').click();assert((await snap()).save.food===food+1);check('Confirmed cooking consumes selected monster; meal actually consumed');await p.locator('[data-a=close]').click();await p.locator('#team').click();s=await snap();let lead=s.save.active;for(let i=0;i<2;i++){await p.locator(`[data-a=train][data-id="${lead}"]`).click();if((await snap()).state==='evolve')await p.locator('[data-a=trait][data-id=heart]').click()}assert((await snap()).save.party.find(m=>m.id===lead).species==='Thornhare');check('Normal earned coins fund training, evolution and trait');await p.locator('[data-a=close]').click();const persisted=(await snap()).save;await p.reload();await p.locator('[data-a=continue]').click();assert.deepEqual((await snap()).save.party,persisted.party);assert.equal((await snap()).save.coins,persisted.coins);check('Refresh preserves team, coins and progress');
await go('wild');await p.screenshot({path:path.join(__dirname,'04-battle.png')});await p.locator('[data-a=run]').click();
// Clearly separate boundary fixture; never counted as ordinary progression.
let fixture=structuredClone(persisted);fixture.party.forEach(m=>m.hp=1);fixture.pos={x:-10,z:-2};await p.addInitScript(x=>localStorage.setItem('martin-monster-quest-v2-wildbound-1',JSON.stringify(x)),fixture);await p.reload();await p.locator('[data-a=continue]').click();await p.locator('#interact').click();await p.locator('[data-a=attack]').click();await p.waitForTimeout(2100);assert.equal((await snap()).state,'switch');assert(await p.locator('[data-a=battle-switch]:disabled').count()>=1);check('Boundary fixture: cannot switch to fallen partner');await p.locator('[data-a=battle-switch]:not(:disabled)').click();await p.locator('[data-a=attack]').click();await p.waitForTimeout(2200);assert.equal((await snap()).state,'story');assert((await snap()).save.party.every(m=>m.hp>0));assert.equal((await snap()).save.coins,persisted.coins);check('Boundary fixture: full defeat revives team without lost coins');await closeStory();
await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(__dirname,'05-portrait.png')});assert(await p.locator('#interact').isVisible());await p.locator('#team').click();await p.locator('[data-a=close]').click();check('Portrait buttons and return usable');await p.setViewportSize({width:1180,height:820});await p.screenshot({path:path.join(__dirname,'06-tablet.png')});check('Tablet viewport rendered (not real iPad)');assert.deepEqual(report.errors,[]);check('No browser JavaScript errors');report.status='passed';
}catch(e){report.status='failed';report.failure=e.stack;console.error(e)}finally{report.ended=new Date().toISOString();await browser?.close();await new Promise(r=>server.close(r));report.cleanup='Task browser and HTTP server closed';fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(report,null,2))}})();
