/* Local-only multitrack sampler. Imported recordings are never uploaded. */
(async function(){'use strict';
const C=window.ArrangerCore,$=s=>document.querySelector(s),clone=x=>JSON.parse(JSON.stringify(x));
let project=null,baseline=null,ctx=null,files=new Map(),buffers=new Map(),baseURL=null,live=[],nodes=new Map(),started=0,playing=false,raf=0,midiAccess=null,recorder=null,stream=null,recorded=[],micURL=null,loadEpoch=0;
const status=s=>$('#status').textContent=s;
const error=e=>status('未完成 / Not completed: '+e.message);
const name=s=>({party:'花园派对 / Garden',storm:'风雨将至 / Storm',rescue:'一起救援 / Rescue',feast:'团圆宴会 / Reunion',demo:'合成音演示 / Demo'}[s]||s);
function scene(){return project?.scenes.find(s=>s.id===$('#scene').value);}
async function audio(){if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')await ctx.resume();return ctx;}
const outputs=new Set();
function stop(){loadEpoch++;live.forEach(s=>{try{s.stop()}catch(e){}});live=[];outputs.forEach(m=>{m.disconnect();m._limit.disconnect()});outputs.clear();nodes.clear();playing=false;cancelAnimationFrame(raf);$('#playhead').value=0;$('#clock').textContent='0.00 s';}
function projectKey(){return 'classroom-arranger:'+project.version+':'+project.title;}
function install(p){stop();C.validate(p);project=clone(p);baseline=clone(p);$('#title').textContent=p.title||'声音编排';$('#scene').replaceChildren(...p.scenes.map(s=>new Option(s.language+' · '+name(s.group),s.id)));$('#workspace').hidden=false;$('#empty').hidden=true;render();status('已载入 '+p.tracks.length+' 轨 / '+p.scenes.length+' 场景。原始音频不改变。');}
async function getBuffer(path,context=ctx){if(buffers.has(path))return buffers.get(path);let bytes;
 if(files.size){const f=files.get(path)||files.get(path.split('/').pop());if(!f)throw Error('Missing local audio: '+path);bytes=await f.arrayBuffer();}
 else {if(!baseURL)throw Error('请先选择私密文件夹 / Import a private folder first');const u=new URL(path,baseURL);if(u.origin!==location.origin)throw Error('Cross-origin audio refused');const r=await fetch(u,{credentials:'omit'});if(!r.ok)throw Error('Audio HTTP '+r.status);bytes=await r.arrayBuffer();}
 const b=await context.decodeAudioData(bytes);buffers.set(path,b);return b;
}
async function loadScene(s){const a=await audio();await Promise.all([...s.stems.map(st=>st.file),...project.samples.map(sm=>sm.file)].map(f=>getBuffer(f,a)));}
function bus(context,destination,t){const gain=context.createGain(),pan=context.createStereoPanner();gain.gain.value=C.trackEnabled(t,project.tracks)?t.gain:0;pan.pan.value=t.pan;gain.connect(pan);pan.connect(destination);return{gain,pan};}
function master(context){const m=context.createGain();m.gain.value=Number($('#master').value);const limit=context.createDynamicsCompressor();limit.threshold.value=-3;limit.knee.value=0;limit.ratio.value=20;limit.attack.value=.003;limit.release.value=.1;m.connect(limit);limit.connect(context.destination);m._limit=limit;if(context===ctx)outputs.add(m);return m;}
function schedule(context,s,when,trackNodes){const sources=[];const run=(buffer,t,at,velocity=1,offset=0,duration=null)=>{const src=context.createBufferSource(),g=context.createGain();src.buffer=buffer;g.gain.value=velocity;src.connect(g);g.connect(trackNodes.get(t).gain);if(duration)src.start(when+at,offset,duration);else src.start(when+at,offset);sources.push(src);};
 s.stems.forEach(st=>run(buffers.get(st.file),st.track,0));s.events.forEach(e=>{const sample=project.samples.find(sm=>sm.id===e.sample);run(buffers.get(sample.file),e.track,e.at,e.velocity,e.offset||0,e.duration);});return sources;
}
async function play(){stop();const epoch=++loadEpoch,s=scene();if(!s)return;await loadScene(s);if(epoch!==loadEpoch)return;const out=master(ctx);nodes=new Map(project.tracks.map(t=>[t.id,bus(ctx,out,t)]));started=ctx.currentTime+.08;live=schedule(ctx,s,started,nodes);playing=true;
 const tick=()=>{if(!playing)return;const t=Math.max(0,ctx.currentTime-started);$('#clock').textContent=t.toFixed(2)+' s';$('#playhead').value=Math.min(1,t/s.duration);if(t>=s.duration){stop();status('播放结束 / Playback complete');return;}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);status('播放中 / Playing. 推子即时生效，时间编辑会停止播放。');}
function updateBuses(){for(const t of project.tracks){const n=nodes.get(t.id);if(n){n.gain.gain.setTargetAtTime(C.trackEnabled(t,project.tracks)?t.gain:0,ctx.currentTime,.025);n.pan.pan.setTargetAtTime(t.pan,ctx.currentTime,.025);}}}
function addControl(label,type,value,min,max,step,fn){const l=document.createElement('label');l.textContent=label+' ';const i=document.createElement('input');i.type=type;if(type==='checkbox')i.checked=!!value;else{i.value=value;i.min=min;i.max=max;i.step=step;}i.oninput=()=>fn(type==='checkbox'?i.checked:Number(i.value));l.append(i);return l;}
function render(){const s=scene();$('#lanes').replaceChildren();$('#pads').replaceChildren();if(!s)return;$('#scene-note').textContent=s.duration.toFixed(1)+' s · '+s.events.length+' 声音事件 / events';
 project.tracks.forEach((t,index)=>{const row=document.createElement('section');row.className='lane';const title=document.createElement('strong');title.textContent=t.label;row.append(title);const fader=addControl('音量 / Gain','range',t.gain,0,1.5,.01,v=>{t.gain=v;updateBuses();});row.append(fader,addControl('声像 / Pan','range',t.pan,-1,1,.01,v=>{t.pan=v;updateBuses();}),addControl('静音 M','checkbox',t.mute,0,1,1,v=>{t.mute=v;updateBuses();}),addControl('独听 S','checkbox',t.solo,0,1,1,v=>{t.solo=v;updateBuses();}));
 const timeline=document.createElement('div');timeline.className='lane-time';timeline.setAttribute('aria-label',t.label+'时间线');for(const e of s.events.filter(e=>e.track===t.id)){const b=document.createElement('button');b.className='event';b.style.left=(e.at/s.duration*100)+'%';b.style.width=Math.max(3,e.duration/s.duration*100)+'%';b.title=e.at.toFixed(2)+' s';b.textContent='•';b.onclick=()=>editEvent(e);timeline.append(b);}if(t.kind==='stem')timeline.textContent=t.id==='voice'?'已验收人声 / Accepted voice':'V4 环境轨 / V4 environment';row.append(timeline);$('#lanes').append(row);
 });
 project.samples.forEach((sample,index)=>{const b=document.createElement('button');b.className='pad';b.textContent=(index+1)+' · '+sample.label;b.onclick=()=>trigger(sample,.85).catch(error);$('#pads').append(b);});
 $('#event-sample').replaceChildren(...project.samples.map(sm=>new Option(sm.label,sm.id)));$('#event-at').max=Math.max(0,s.duration-.01);$('#event-editor').hidden=true;
}
function editEvent(e){stop();$('#event-editor').hidden=false;$('#edit-at').value=e.at;$('#edit-at').max=scene().duration-e.duration;$('#edit-velocity').value=e.velocity;$('#edit-title').textContent=project.samples.find(s=>s.id===e.sample).label;$('#apply-event').onclick=()=>{const at=Number($('#edit-at').value),vel=Number($('#edit-velocity').value);if(at<0||at+e.duration>scene().duration||vel<0||vel>1)return error(Error('时间或力度超出范围'));e.at=at;e.velocity=vel;render();};$('#delete-event').onclick=()=>{scene().events=scene().events.filter(x=>x!==e);render();};}
function addEvent(sample,at,velocity){const s=scene();if(at<0||at+sample.duration>s.duration+.001)throw Error('声音会超出场景；请提前时间点 / Event exceeds scene');if(s.events.length>=500)throw Error('Event limit');s.events.push({id:'added-'+Date.now()+'-'+s.events.length,sample:sample.id,track:sample.track,at:+at.toFixed(4),velocity,offset:0,duration:sample.duration});}
async function trigger(sample,velocity){await audio();const b=await getBuffer(sample.file,ctx),t=project.tracks.find(t=>t.id===sample.track);if(!C.trackEnabled(t,project.tracks))return;const out=master(ctx),n=bus(ctx,out,t),s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=b;g.gain.value=velocity;s.connect(g);g.connect(n.gain);s.start();live.push(s);s.onended=()=>{live=live.filter(x=>x!==s);n.gain.disconnect();n.pan.disconnect();out.disconnect();out._limit.disconnect();outputs.delete(out);};
 if($('#capture-events').checked&&playing){const at=ctx.currentTime-started;addEvent(sample,at,velocity);status('已录入触发事件 / Pad event recorded');}
}
function download(name,bytes,type){const u=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
async function renderAudio(){const s=scene();await loadScene(s);const offline=new OfflineAudioContext(2,Math.ceil(s.duration*48000),48000),out=master(offline),buses=new Map(project.tracks.map(t=>[t.id,bus(offline,out,t)]));schedule(offline,s,0,buses);return offline.startRendering();}
async function exportMix(){stop();status('本地导出 / Rendering locally…');const b=await renderAudio(),w=C.wav(b);download(scene().id+'-mix.wav',w.bytes,'audio/wav');status('已导出 WAV；峰值保护增益 '+w.normalizationGain.toFixed(3)+'。原件未改。');}
async function importFiles(list){if(list.length>250)throw Error('Too many files');stop();loadEpoch++;files=new Map();buffers.clear();let config=null;const names=new Map();for(const f of list){if(f.size>128*1024*1024)throw Error('Single file exceeds 128 MB');const key=f.webkitRelativePath?f.webkitRelativePath.split('/').slice(1).join('/'):f.name;if(key==='arrangement.json'||f.name==='arrangement.json')config=f;files.set(key,f);if(!names.has(f.name))names.set(f.name,f);else names.set(f.name,null);}for(const[n,f]of names)if(f)files.set(n,f);if(!config)throw Error('请选择包含 arrangement.json 与 audio 的整个文件夹');baseURL=null;install(JSON.parse(await config.text()));}
async function demo(){await audio();files=new Map();baseURL=null;buffers.clear();const tracks=[],samples=[];for(let i=0;i<8;i++){const b=ctx.createBuffer(1,Math.round(ctx.sampleRate*.3),ctx.sampleRate),x=b.getChannelData(0);for(let k=0;k<x.length;k++)x[k]=Math.sin(2*Math.PI*(220+i*73)*k/ctx.sampleRate)*Math.exp(-k/ctx.sampleRate*17)*.18;const file='demo'+i+'.wav';buffers.set(file,b);tracks.push({id:'t'+i,label:'演示音 '+(i+1),gain:.6,pan:0,kind:'sample'});samples.push({id:'s'+i,track:'t'+i,label:'合成音 '+(i+1),duration:.3,file,midi_note:60+i});}install({schema:'classroom-audio-arrangement/1.0',version:'demo-1.0',title:'合成音演示 · 不是学生声音',tracks,samples,scenes:[{id:'demo',group:'demo',language:'DEMO',duration:8,stems:[],events:samples.map((sm,i)=>({id:'e'+i,at:i*.75,sample:sm.id,track:sm.track,duration:.3,velocity:.8,offset:0}))}]});}
function savePreset(){C.validate(project);const p={schema:'classroom-audio-preset/1.0',project_version:project.version,project_title:project.title,tracks:project.tracks,scenes:project.scenes.map(s=>({id:s.id,events:s.events}))};try{localStorage.setItem(projectKey(),JSON.stringify(p));status('已保存到此浏览器，不是发给老师 / Saved on this browser only');}catch(e){status('浏览器无法保存，请导出 JSON');}return p;}
function applyPreset(p){if(p.schema!=='classroom-audio-preset/1.0'||p.project_version!==project.version||p.project_title!==project.title)throw Error('Preset belongs to another project/version');const candidate=clone(project);candidate.tracks=p.tracks;for(const s of candidate.scenes){const replacement=p.scenes.find(x=>x.id===s.id);if(replacement)s.events=replacement.events;}C.validate(candidate);stop();project=candidate;render();}
async function midi(){if(!navigator.requestMIDIAccess||!window.isSecureContext)throw Error('当前浏览器不支持 MIDI；请使用屏幕垫或数字键 / MIDI unavailable');midiAccess=await navigator.requestMIDIAccess({sysex:false});const attach=()=>{midiAccess.inputs.forEach(input=>input.onmidimessage=e=>{const[statusByte,n,v]=e.data,kind=statusByte&240;if(kind===144&&v>0){const sample=project?.samples.find(sm=>sm.midi_note===n);if(sample)trigger(sample,v/127).catch(error);}if(kind===176&&project){const t=project.tracks[(statusByte&15)%project.tracks.length];if(n===7)t.gain=v/127;if(n===10)t.pan=v/127*2-1;updateBuses();render();}});status('MIDI 输入已连接 '+midiAccess.inputs.size+' 个 / note-on、CC7/CC10');};attach();midiAccess.onstatechange=attach;}
async function recordMic(){if(recorder?.state==='recording'){recorder.stop();return;}if(!$('#consent').checked)throw Error('先确认本次录音用途与授权');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('录音需支持的浏览器及 HTTPS/localhost');stop();stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});recorded=[];try{recorder=new MediaRecorder(stream);}catch(e){stream.getTracks().forEach(t=>t.stop());stream=null;throw e;}recorder.ondataavailable=e=>{if(e.data.size)recorded.push(e.data)};recorder.onstop=()=>{stream?.getTracks().forEach(t=>t.stop());stream=null;const blob=new Blob(recorded,{type:recorder.mimeType});if(micURL)URL.revokeObjectURL(micURL);micURL=URL.createObjectURL(blob);$('#recorded').src=micURL;$('#recorded').hidden=false;$('#save-recording').hidden=false;$('#save-recording').onclick=()=>download('classroom-recording.'+(blob.type.includes('mp4')?'m4a':'webm'),blob,blob.type);$('#record').textContent='开始本人录音 / Record';status('录音仅在本机。先试听，再另行交给本地克隆生成器。');};try{recorder.start();}catch(e){stream?.getTracks().forEach(t=>t.stop());stream=null;throw e;}$('#record').textContent='停止录音 / Stop recording';status('正在录音 / Recording locally');}
$('#master').oninput=()=>{outputs.forEach(m=>m.gain.setTargetAtTime(Number($('#master').value),ctx.currentTime,.025));};
$('#files').onchange=e=>importFiles([...e.target.files]).catch(error);$('#loose-files').onchange=e=>importFiles([...e.target.files]).catch(error);$('#demo').onclick=()=>demo().catch(error);$('#play').onclick=()=>play().catch(error);$('#stop').onclick=()=>{loadEpoch++;stop();render();};$('#scene').onchange=()=>{loadEpoch++;stop();render();};$('#save').onclick=()=>{try{savePreset()}catch(e){error(e)}};$('#restore').onclick=()=>{try{const s=localStorage.getItem(projectKey());if(!s)throw Error('No saved preset');applyPreset(JSON.parse(s));status('已恢复保存的编排')}catch(e){error(e)}};$('#reset').onclick=()=>{stop();project=clone(baseline);render();status('恢复版本默认值，原文件未改');};$('#export-json').onclick=()=>{try{download('voice-preset.json',JSON.stringify(savePreset(),null,2),'application/json')}catch(e){error(e)}};$('#preset-file').onchange=async e=>{try{applyPreset(JSON.parse(await e.target.files[0].text()))}catch(e){error(e)}};
$('#add-event').onclick=()=>{try{stop();addEvent(project.samples.find(s=>s.id===$('#event-sample').value),Number($('#event-at').value),Number($('#event-velocity').value));render()}catch(e){error(e)}};$('#export-wav').onclick=()=>exportMix().catch(error);$('#export-midi').onclick=()=>{try{download('animal-events.mid',C.midi(project,scene()),'audio/midi');status('MIDI 只含触发时间与力度，不含声音；请配合采样映射使用。')}catch(e){error(e)}};$('#connect-midi').onclick=()=>midi().catch(error);$('#record').onclick=()=>recordMic().catch(error);
$('#export-avatar').onclick=async()=>{try{const st=scene().stems.find(x=>x.track==='voice');if(!st)throw Error('No voice stem');await audio();const b=await getBuffer(st.file),e=C.envelope(b);download('speaking-envelope.json',JSON.stringify(e),'application/json');status('已导出音量驱动口型包络；不是音素级口型、也不是完整数字人。')}catch(e){error(e)}};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.repeat)return;const i=Number(e.key)-1;if(project&&i>=0&&i<project.samples.length){e.preventDefault();trigger(project.samples[i],.85).catch(error);}});window.addEventListener('pagehide',()=>{stop();if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());if(midiAccess)midiAccess.inputs.forEach(i=>i.onmidimessage=null);});
try{if(location.protocol.startsWith('http')){const url=new URL('../arrangement.json',location.href);const r=await fetch(url,{credentials:'omit'});if(r.ok){baseURL=new URL('.',url);install(await r.json());}}}catch(e){status('导入私密素材，或用演示音体验调音 / Import a private folder or use demo');}
window.__voiceWorkbench={demo,play,stop,exportMix,getProject:()=>clone(project),getScene:()=>clone(scene()),applyPreset,renderAudio};
})();
