import {chromium} from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{}),headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const errors=[],results=[];const base=process.env.TEST_URL||'http://127.0.0.1:18940';const room='BROWSER'+Date.now().toString().slice(-6);
try{const pages=[];for(let i=0;i<3;i++){const ctx=await browser.newContext({viewport:{width:i===0?1024:640,height:i===0?768:480},hasTouch:i===2,isMobile:i===2});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/?room='+room);await page.locator('#nickname').fill('Explorer '+(i+1));if(i===0)await page.screenshot({path:'qa/landing.png'});await page.locator('#start').click();await page.waitForFunction(()=>window.__skyvale?.state.online,{timeout:20000});pages.push(page);}
 await pages[0].waitForFunction(()=>window.__skyvale.state.players.length===3);results.push('Three separate browser contexts joined one world');
 await pages[0].bringToFront();const p=pages[0];await p.locator('#scene canvas').click({position:{x:700,y:400}});const before=await p.evaluate(()=>window.__skyvale.state.local);await p.keyboard.down('KeyW');await p.waitForTimeout(1600);await p.keyboard.up('KeyW');await p.waitForTimeout(600);const after=await p.evaluate(()=>window.__skyvale.state.local);await p.screenshot({path:'qa/world.png'});if(before.z-after.z<3)throw Error('Movement failed '+JSON.stringify({before,after}));const stopped=await p.evaluate(()=>window.__skyvale.state.local);await p.waitForTimeout(500);const idle=await p.evaluate(()=>window.__skyvale.state.local);if(Math.hypot(idle.x-stopped.x,idle.z-stopped.z)>.5)throw Error('Input stuck');results.push('Keyboard movement and release stop passed');
 await p.screenshot({path:'qa/world.png'});const third=pages[2];await third.setViewportSize({width:1024,height:768});await third.screenshot({path:'qa/tablet.png'});await third.locator('#joystick').dispatchEvent('pointercancel',{pointerId:1});if((await third.evaluate(()=>window.__skyvale.state.input.x))!==0)throw Error('Pointer cancel stuck');results.push('Tablet layout and pointer cancellation passed');
 await pages[1].reload();await pages[1].locator('#start').click();await pages[1].waitForFunction(()=>window.__skyvale.state.online);results.push('Refresh / rejoin passed');
 const stats=await p.evaluate(()=>window.__skyvale.state);if(errors.length)throw Error(errors.join(';'));fs.writeFileSync('qa/browser-results.json',JSON.stringify({base,results,errors,drawCalls:stats.drawCalls,cleanup:'browser closed in finally',physicalIPad:'NOT TESTED'},null,2));console.log(JSON.stringify({results,errors,drawCalls:stats.drawCalls}));
}finally{await browser.close();}
