import WebSocket from 'ws';import assert from 'node:assert/strict';import fs from 'node:fs';import {RINGS,TREES,ANIMALS,FIRE,CABIN} from '../public/shared.js';
const base=process.env.TEST_WS||'ws://127.0.0.1:18940';const room='QA'+Date.now();const peers=[];const results=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function join(name){const ws=new WebSocket(base),p={ws,id:null,state:null,error:null};peers.push(p);ws.on('message',d=>{const m=JSON.parse(d);if(m.type==='welcome')p.id=m.id;if(m.type==='state')p.state=m;if(m.type==='error')p.error=m.text;});await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});ws.send(JSON.stringify({type:'join',room,name}));for(let i=0;i<60&&!p.id&&!p.error;i++)await sleep(100);return p;}
function send(p,m){p.ws.send(JSON.stringify(m));}async function act(p,action){send(p,{type:'action',action});await sleep(420);}
async function go(p,t){const deadline=Date.now()+14000;while(Date.now()<deadline){const a=p.state?.players.find(x=>x.id===p.id);if(!a){await sleep(100);continue;}const dx=t.x-a.x,dz=t.z-a.z,n=Math.hypot(dx,dz);if(n<2){send(p,{type:'input',x:0,z:0});await sleep(150);return;}send(p,{type:'input',x:dx/n,z:dz/n});await sleep(80);}throw Error('Travel timed out');}
try{const a=await join('QA one'),b=await join('QA two'),c=await join('QA three');await sleep(200);assert.equal(a.state.players.length,3);const d=await join('QA four');assert(d.error);d.ws.close();results.push('Three real WebSockets; fourth rejected');await act(a,'interact');assert.equal(a.state.world.rings.filter(Boolean).length,0);results.push('Remote interaction rejected');
 for(const t of RINGS){await go(a,t);await act(a,'fly');await act(a,'interact');}assert(a.state.world.rings.every(Boolean));results.push('Flight and all three rings');
 for(const t of TREES){await go(a,t);await act(a,'interact');}await go(a,FIRE);await act(a,'interact');assert(a.state.world.fire);assert.equal(a.state.world.gathered,3);results.push('Orchard and campfire');
 for(const t of ANIMALS){await go(a,t);await act(a,'interact');await act(a,'interact');}assert.equal(a.state.world.produce,3);await go(a,CABIN);for(let i=0;i<3;i++)await act(a,'interact');assert.equal(a.state.world.cabin,3);results.push('Three animals, three produce, three construction stages');
 await act(a,'home');await act(a,'interact');assert(a.state.world.celebrated);await sleep(200);assert.deepEqual(a.state.world,b.state.world);assert.deepEqual(a.state.world,c.state.world);results.push('Full quest completion synchronized across three players');
 c.ws.close();await sleep(300);const e=await join('QA return');assert(e.state.world.celebrated);results.push('Rejoin retains shared progress');fs.writeFileSync('qa/network-results.json',JSON.stringify({base,results},null,2));console.log(JSON.stringify({results}));
}finally{for(const p of peers)p.ws.close();}
