const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d');
const lang=()=>window.BeastKingsI18n?.get?.()||'zh',tt=(zh,en)=>lang()==='zh'?zh:en;
let slot=0,lastFrame=performance.now(),lastHud=0,mode='duel',paused=false,ended=false,winner=null;
const input={},pointers=new Map(),pressedKeys=new Set(),keymap={KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',Space:'jump',ArrowUp:'jump',KeyJ:'punch',KeyI:'kick',KeyK:'spin',KeyL:'teleport',KeyU:'super'};
const mk=(id,name,x,face)=>({id,name,x,y:470,vx:0,vy:0,face,hp:100,energy:100,charges:0,cd:{punch:0,kick:0,spin:0,teleport:0,super:0},action:'idle',anim:0,invuln:0,flash:0,respawn:0});
let state={status:'lobby',mode,connected:[true,true],players:[mk(0,'FROST',280,1),mk(1,'EMBER',920,-1)],targets:[],effects:[]};
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2200)}
function resetTargets(){state.targets=[];for(let i=0;i<5;i++)state.targets.push({id:i,x:190+i*200,y:470,hp:28,maxHp:28,respawn:0,flash:0})}
function resetRound(){state.players=[mk(0,'FROST',280,1),mk(1,'EMBER',920,-1)];state.effects=[];winner=null;ended=false;paused=false;state.status='playing';state.mode=mode;if(mode==='crown')resetTargets();else state.targets=[];updateUI()}
function release(){pointers.clear();pressedKeys.clear();for(const k of Object.keys(input))input[k]=false;document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'))}
function rebuild(){for(const k of Object.values(keymap))input[k]=false;for(const k of pressedKeys)input[k]=true;for(const k of pointers.values())input[k]=true;document.querySelectorAll('[data-key]').forEach(b=>b.classList.toggle('held',!!input[b.dataset.key]))}
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,b.dataset.key);rebuild()});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>{pointers.delete(e.pointerId);rebuild()})});
window.addEventListener('keydown',e=>{const k=keymap[e.code];if(k){e.preventDefault();pressedKeys.add(k);rebuild()}});window.addEventListener('keyup',e=>{const k=keymap[e.code];if(k){e.preventDefault();pressedKeys.delete(k);rebuild()}});window.addEventListener('blur',release);
function hit(attacker,target,damage,push=0){if(target.invuln>0||target.hp<=0)return;target.hp=Math.max(0,target.hp-damage);target.flash=.12;target.vx+=(Math.sign(target.x-attacker.x)||attacker.face)*push;state.effects.push({type:'hit',x:target.x,y:target.y-55,life:.5,color:attacker.id});if(target.hp<=0){if(mode==='duel'){ended=true;state.status='ended';winner=attacker.name}else{target.respawn=1.4}}}
function attack(p,key){if(p.cd[key]>0||p.hp<=0)return;const other=state.players[1-p.id],dx=(other.x-p.x)*p.face,dist=Math.abs(other.x-p.x);p.action=key;p.anim=.2;
 if(key==='punch'){p.cd.punch=.36;if(dx>-20&&dist<100)hit(p,other,9,75)}
 else if(key==='kick'){p.cd.kick=.7;if(dx>-25&&dist<145)hit(p,other,15,135)}
 else if(key==='spin'){p.cd.spin=2.5;if(dist<155)hit(p,other,19,160);state.effects.push({type:'spin',x:p.x,y:p.y-55,life:.5,color:p.id})}
 else if(key==='teleport'){p.cd.teleport=3;p.x=Math.max(50,Math.min(1150,p.x+p.face*230));state.effects.push({type:'blink',x:p.x,y:p.y-55,life:.5,color:p.id})}
 else if(key==='super'){p.cd.super=4;if(dist<430)hit(p,other,23,190);state.effects.push({type:'super',x:p.x,y:p.y-60,life:.5,color:p.id})}
}
function attackTarget(p,key){if(mode!=='crown'||!['punch','kick','spin','super'].includes(key))return;let range={punch:100,kick:145,spin:155,super:430}[key],damage={punch:9,kick:15,spin:19,super:23}[key];for(const t of state.targets){if(t.hp>0&&Math.abs(t.x-p.x)<range){t.hp=Math.max(0,t.hp-damage);t.flash=.12;if(t.hp===0){p.charges++;t.respawn=1.4;state.effects.push({type:'crown',x:t.x,y:t.y-45,life:.5,color:p.id});if(p.charges>=5){ended=true;state.status='ended';winner=p.name}}}}
}
let lastPressed={};
function step(dt){if(paused||ended||state.status!=='playing')return;for(const p of state.players){for(const k in p.cd)p.cd[k]=Math.max(0,p.cd[k]-dt);p.anim=Math.max(0,p.anim-dt);p.invuln=Math.max(0,p.invuln-dt);p.flash=Math.max(0,p.flash-dt);if(p.hp<=0&&mode==='crown'){p.respawn-=dt;if(p.respawn<=0){p.hp=100;p.x=p.id?920:280;p.y=470;p.energy=100;p.invuln=1}}}
 const p=state.players[0],dir=(input.right?1:0)-(input.left?1:0);if(dir){p.face=dir;p.x=Math.max(50,Math.min(1150,p.x+dir*280*dt))}if(input.jump&&p.energy>0){if(p.y>=470)p.vy=-360;p.vy-=520*dt;p.energy=Math.max(0,p.energy-30*dt)}else p.energy=Math.min(100,p.energy+35*dt);p.vy+=700*dt;p.y=Math.max(150,Math.min(470,p.y+p.vy*dt));if(p.y>=470)p.vy=0;p.x=Math.max(50,Math.min(1150,p.x+p.vx*dt));p.vx*=Math.pow(.05,dt);
 for(const key of ['punch','kick','spin','teleport','super']){if(input[key]&&!lastPressed[key]){attack(p,key);attackTarget(p,key)}lastPressed[key]=!!input[key]}
 const ai=state.players[1];if(ai.hp>0){const dx=p.x-ai.x;ai.face=dx<0?-1:1;if(Math.abs(dx)>115)ai.x+=Math.sign(dx)*185*dt;if(Math.abs(dx)<105&&ai.cd.punch<=0&&Math.random()<dt*2.2)attack(ai,'punch');else if(Math.abs(dx)<145&&ai.cd.kick<=0&&Math.random()<dt*.8)attack(ai,'kick');else if(ai.cd.super<=0&&Math.random()<dt*.16)attack(ai,'super');if(mode==='crown'){let live=state.targets.filter(t=>t.hp>0).sort((a,b)=>Math.abs(a.x-ai.x)-Math.abs(b.x-ai.x))[0];if(live){ai.x+=Math.sign(live.x-ai.x)*120*dt;if(Math.abs(live.x-ai.x)<110&&ai.cd.punch<=0){ai.cd.punch=.5;live.hp=Math.max(0,live.hp-8);if(live.hp===0){ai.charges++;live.respawn=1.4;if(ai.charges>=5){ended=true;state.status='ended';winner=ai.name}}}}}}
 for(const t of state.targets){t.flash=Math.max(0,t.flash-dt);if(t.hp<=0){t.respawn-=dt;if(t.respawn<=0){t.hp=t.maxHp;t.x=140+Math.random()*920}}}
 state.effects=state.effects.filter(e=>(e.life-=dt)>0);updateUI()}
function updateUI(){const s=state;$('#connection').textContent=tt('● Git 单机重现','● Git solo replay');$('#you').textContent=tt('你是 FROST','YOU ARE FROST');$('#modeLabel').textContent=mode==='duel'?tt('对战','DUEL'):tt('王冠争夺','CROWN HUNT');for(let i=0;i<2;i++){let p=s.players[i];$('#hp'+i).textContent=Math.ceil(p.hp)+' HP';$('#bar'+i).style.width=p.hp+'%';$('#power'+i).textContent=(i?tt('火焰守护兽','FIRE GUARDIAN'):tt('冰霜守护兽','ICE GUARDIAN'))+(mode==='crown'?' · '+p.charges+'/5':'')}$('#energyBar').style.width=s.players[0].energy+'%';$('#pause').disabled=s.status!=='playing';$('#overlay').hidden=s.status==='playing';$('#start').hidden=s.status!=='lobby';$('#resume').hidden=!paused;$('#rematch').hidden=!ended;$('#join').hidden=true;$('#modes').hidden=s.status==='playing';if(s.status==='lobby'){$('#title').textContent=tt('初版：两只 Beast，一顶王冠。','Original build: two beasts, one crown.');$('#explain').textContent=tt('这是 2026-09-12 初版规则的 Git 单机重现：Frost 对 AI Ember。','Git-playable recreation of the 2026-09-12 original rules: Frost vs AI Ember.')}else if(paused){$('#title').textContent=tt('已暂停','Paused');$('#explain').textContent=tt('准备好以后继续。','Resume when ready.')}else if(ended){$('#title').textContent=winner===state.players[0].name?tt('你赢了！','You reign!'):tt('Ember 赢了这一局','Ember reigns this round');$('#explain').textContent=mode==='duel'?tt('把对手 HP 打到 0。','Opponent HP reached zero.'):tt('先击破 5 个目标即可称王。','First to five targets becomes King.')}}
$('#pause').onclick=()=>{if(state.status==='playing'){paused=true;state.status='paused';updateUI()}};$('#resume').onclick=()=>{paused=false;state.status='playing';updateUI()};$('#start').onclick=resetRound;$('#rematch').onclick=resetRound;$('#join').onclick=resetRound;$('#leave').onclick=()=>{state.status='lobby';paused=false;ended=false;updateUI()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));state.mode=mode;updateUI()});
function language(){const set=(sel,zh,en)=>{const el=$(sel);if(el)el.textContent=tt(zh,en)};document.title=tt('Beast Kings · 初版 Git 重现','Beast Kings · Original Git Replay');set('.brand small','NATHAN + LEO · 初版规则','NATHAN + LEO · ORIGINAL RULES');set('#pause','Ⅱ 暂停','Ⅱ Pause');set('#leave','离开','Leave');set('.eyebrow','天空就是竞技场','THE SKY IS YOUR ARENA');document.querySelector('[data-mode="duel"]').innerHTML=tt('⚔ 对战<small>把对手 HP 打到 0</small>','⚔ Duel<small>Opponent HP → 0</small>');document.querySelector('[data-mode="crown"]').innerHTML=tt('♛ 王冠争夺<small>击破 5 个目标 → King</small>','♛ Crown Hunt<small>Defeat 5 targets → King</small>');set('.guide','◀ ▶ 移动 · 点按 ↑ 跳跃，按住飞行\n近身拳 · 更远踢 · 旋转全打\nBlink 瞬移 · Star 超能力','◀ ▶ Move · Tap ↑ to jump, hold to fly\nPunch close · Kick farther · Spin all around\nBlink forward · Star fires your superpower');set('#joinLink','GitHub Pages 单机重现 · 原版多人服务器源码仍保留。','GitHub Pages solo replay · original multiplayer server source is preserved.');updateUI()}
window.addEventListener('bk-language',language);language();updateUI();
function loop(now){const dt=Math.min(.033,(now-lastFrame)/1000);lastFrame=now;step(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
const colors=[['#71e3ff','#287fac','#153f67'],['#ffc071','#d96639','#7b3643']];
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill();}
function beast(p,t){let c=colors[p.id],bob=p.y===470?Math.sin(t*3+p.id)*2:0;ellipse(p.x,483,48-(470-p.y)*.05,10,'#0005');ctx.save();ctx.translate(p.x,p.y+bob);ctx.scale(p.face,1);if(!p.hp){ctx.rotate(Math.PI/2);ctx.globalAlpha=.5;}if(p.invuln)ctx.globalAlpha=.55+.3*Math.sin(t*30);if(p.flash)c=['#fff','#fff','#b5e6ff'];let active=p.anim>0;
 if(p.y<460){poly([[-26,-40],[-94,-94],[-79,-24],[-36,-9]],c[2]);poly([[26,-40],[83,-91],[72,-17],[30,-8]],c[1]);}
 poly([[-29,-35],[-85,-9],[-100,-28],[-80,-36],[-55,-52]],c[2]);ellipse(-22,-13,19,17,c[2]);ellipse(24+(active&&p.action==='kick'?35:0),-12,20,17,c[1]);ellipse(0,-54,43,49,c[1]);ellipse(8,-48,25,33,c[0]);
 ellipse(-2,-96,43,35,c[1]);poly([[-33,-113],[-35,-151],[-12,-123]],'#e2f5ef');poly([[19,-120],[37,-146],[38,-104]],'#e2f5ef');poly([[-35,-80],[-49,-93],[-45,-60],[-29,-70]],c[0]);ellipse(23,-91,26,19,c[0]);ellipse(29,-96,5,4,c[2]);ellipse(8,-112,10,11,'#f5ffff');ellipse(12,-111,4,7,'#12253b');poly([[0,-124],[21,-117],[20,-122],[2,-132]],c[2]);ctx.strokeStyle=c[2];ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(14,-82);ctx.lineTo(37,-84);ctx.stroke();poly([[23,-84],[26,-76],[30,-85]],'#fff');
 let reach=active&&p.action==='punch'?42:0;ellipse(38+reach,-52,23,18,c[1]);for(let z=0;z<3;z++)poly([[49+reach,-62+z*8],[60+reach,-58+z*8],[49+reach,-55+z*8]],'#eefbff');ellipse(-32,-58,15,23,c[2]);
 if(p.charges){ctx.globalAlpha=1;ctx.strokeStyle='#ffdb72';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-65,68,0,Math.PI*2);ctx.stroke();for(let j=0;j<p.charges;j++)ellipse(Math.cos(t+j*1.25)*69,-65+Math.sin(t+j*1.25)*69,5,5,'#ffe99d');}ctx.restore();ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillStyle=p.id?'#ffc889':'#a8edff';ctx.fillText(p.name+(p.id===slot?'  |  YOU':''),p.x,p.y-169);if(p.respawn>0){ctx.fillStyle='#fff';ctx.fillText('BACK IN '+Math.ceil(p.respawn),p.x,p.y-190);}}
function render(ms){let t=ms/1000;ctx.clearRect(0,0,1200,580);let grad=ctx.createLinearGradient(0,0,0,580);grad.addColorStop(0,'#111c38');grad.addColorStop(.7,'#384468');grad.addColorStop(1,'#1b2c42');ctx.fillStyle=grad;ctx.fillRect(0,0,1200,580);ellipse(600,140,95,95,'#ffebba');ellipse(600,140,118,118,'#ffdf9b0b');for(let i=0;i<55;i++){let x=(i*193)%1200,y=(i*47)%260;ellipse(x,y,1.2,1.2,'#e0eaff77');}
 poly([[0,290],[120,185],[240,306],[385,142],[520,324],[720,206],[880,304],[1030,130],[1200,282],[1200,580],[0,580]],'#172b45');poly([[0,355],[156,300],[260,374],[434,272],[602,360],[803,315],[1000,371],[1200,291],[1200,580],[0,580]],'#243a51');
 for(let i=0;i<6;i++){let x=i*240-30;poly([[x,459],[x+9,295],[x+27,264],[x+51,298],[x+62,459]],'#172a3d');poly([[x+14,314],[x+29,284],[x+35,363],[x+23,406]],i%2?'#d77a5360':'#55cbd660');}
 ellipse(600,523,650,82,'#080f20');poly([[20,470],[1180,470],[1144,520],[56,520]],'#607185');poly([[56,520],[1144,520],[1100,555],[97,555]],'#263b50');ctx.strokeStyle='#b7d6d680';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(25,470);ctx.lineTo(1175,470);ctx.stroke();for(let i=0;i<13;i++){ctx.strokeStyle='#8196a33b';ctx.beginPath();ctx.moveTo(80+i*85,474);ctx.lineTo(65+i*86,513);ctx.stroke();}ellipse(600,493,105,12,'#ffe6a218');
 const s=state||{players:[{id:0,name:'FROST',x:280,y:470,face:1,hp:100,charges:0},{id:1,name:'EMBER',x:920,y:470,face:-1,hp:100,charges:0}],targets:[],effects:[]};
 for(let target of s.targets)if(target.hp>0){ctx.save();ctx.translate(target.x,target.y);let b=Math.sin(t*3+target.id)*4;ellipse(0,8,24,7,'#0004');poly([[-26,-30+b],[-19,-63+b],[0,-78+b],[23,-58+b],[29,-28+b],[0,-12+b]],target.flash?'#fff':'#b0a0e7');ellipse(-8,-48+b,4,6,'#2d294c');ellipse(9,-48+b,4,6,'#2d294c');ctx.fillStyle='#332e50';ctx.fillRect(-24,-95,48,5);ctx.fillStyle='#d6c5ff';ctx.fillRect(-24,-95,48*target.hp/28,5);ctx.restore();}
 for(let p of s.players)beast(p,t);
 for(let e of s.effects){let a=e.life/.5,c=e.color?'#ffb766':'#83e8ff';ctx.save();ctx.globalAlpha=a;ctx.strokeStyle=c;ctx.lineWidth=5;ctx.translate(e.x,e.y);if(e.type==='super'){ctx.fillStyle=c;ctx.shadowBlur=30;ctx.shadowColor=c;ctx.fillRect(e.color?-330:0,-7,330,14);}else if(e.type==='crown'){ctx.font='50px Arial';ctx.textAlign='center';ctx.fillStyle='#ffe389';ctx.fillText('\u265b',0,-30*(1-a));}else{ctx.beginPath();ctx.arc(0,0,(1-a)*80+15,0,Math.PI*2);ctx.stroke();for(let j=0;j<8;j++){let ang=j*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(ang)*30*(1-a),Math.sin(ang)*30*(1-a));ctx.lineTo(Math.cos(ang)*100*(1-a),Math.sin(ang)*100*(1-a));ctx.stroke();}}ctx.restore();}
 requestAnimationFrame(render);}
requestAnimationFrame(render);


