function setGameText(element,value){const raw=String(value);const text=window.__reviewLanguage?.translate(raw)??raw;if(element.textContent!==text)element.textContent=text;}
import * as THREE from './vendor/three.module.js';
const $=id=>document.getElementById(id), clamp=THREE.MathUtils.clamp, V=THREE.Vector3;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0a1029);scene.fog=new THREE.FogExp2(0x181b39,.006);
const camera=new THREE.PerspectiveCamera(53,innerWidth/innerHeight,.1,900);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){setGameText($('boot'),'无法启动 3D，请使用支持 WebGL 的浏览器打开。');throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer:coarse)').matches?1.25:1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;$('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xaacbff,0x4c2460,2.6));const sun=new THREE.DirectionalLight(0xffdcc0,3.2);sun.position.set(-25,65,25);sun.castShadow=true;sun.shadow.mapSize.set(matchMedia('(pointer:coarse)').matches?768:2048,matchMedia('(pointer:coarse)').matches?768:2048);Object.assign(sun.shadow.camera,{left:-80,right:80,top:90,bottom:-90,near:1,far:180});sun.shadow.bias=-.0005;scene.add(sun);const blueLight=new THREE.DirectionalLight(0x5eaaff,2);blueLight.position.set(40,20,-50);scene.add(blueLight);
const materials={};function mat(c,em=0,metal=.1){const key=[c,em,metal].join();return materials[key]??=new THREE.MeshStandardMaterial({color:c,roughness:.62,metalness:metal,emissive:em,emissiveIntensity:em?1.1:0,flatShading:true});}
function mesh(geo,m,p,x=0,y=0,z=0){const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;p.add(o);return o;}
const box=(p,w,h,d,c,x=0,y=0,z=0,em=0)=>mesh(new THREE.BoxGeometry(w,h,d),mat(c,em),p,x,y,z);
const sphere=(p,r,c,x=0,y=0,z=0,em=0,detail=1)=>mesh(new THREE.IcosahedronGeometry(r,detail),mat(c,em),p,x,y,z);
function ring(p,r,t,c,x=0,y=0,z=0){const m=mesh(new THREE.TorusGeometry(r,t,8,72),mat(c,c),p,x,y,z);m.rotation.x=-Math.PI/2;return m;}
function cyl(p,r1,r2,h,c,x=0,y=0,z=0,n=12){return mesh(new THREE.CylinderGeometry(r1,r2,h,n),mat(c),p,x,y,z);}
let seed=417;function rand(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646;}
// Stars, Earth and the ringed moon are geometry, so the whole game runs offline.
const starsGeo=new THREE.BufferGeometry(),stars=[];for(let i=0;i<1800;i++){const a=rand()*Math.PI*2,b=rand()*Math.PI,r=240+rand()*180;stars.push(Math.sin(b)*Math.cos(a)*r,Math.abs(Math.cos(b))*r-20,Math.sin(b)*Math.sin(a)*r);}
starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));scene.add(new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xe2e8ff,size:.65,sizeAttenuation:true})));
const earth=new THREE.Group();scene.add(earth);earth.position.set(-100,91,-178);sphere(earth,25,0x2788b6,0,0,0,0,3);for(let i=0;i<23;i++){const a=rand()*6.28,b=rand()*3.14;const patch=sphere(earth,3+rand()*5,0x68cbb3,Math.sin(b)*Math.cos(a)*24,Math.cos(b)*24,Math.sin(b)*Math.sin(a)*24);patch.scale.set(1,.5,1.1);}const atmosphere=mesh(new THREE.SphereGeometry(26,32,32),new THREE.MeshBasicMaterial({color:0x6dccff,transparent:true,opacity:.11,side:THREE.BackSide}),earth);atmosphere.scale.setScalar(1.08);
const moon=sphere(scene,17,0x977c9d,95,62,-200,0,2);const moonRing=ring(scene,29,.15,0xb795a7,95,62,-200);moonRing.rotation.set(1.15,.35,.15);
// Faceted island, lava veins, crystal fields and a landing station.
const world=new THREE.Group();scene.add(world);const ground=cyl(world,58,49,7,0x40354e,0,-3.5,-27,72);ground.receiveShadow=true;const edge=cyl(world,49,27,14,0x211d34,0,-14,-27,16);
const topGeo=new THREE.PlaneGeometry(108,108,28,28);topGeo.rotateX(-Math.PI/2);const pp=topGeo.attributes.position;for(let i=0;i<pp.count;i++){let x=pp.getX(i),z=pp.getZ(i);pp.setY(i,Math.sin(x*.25)*Math.cos(z*.23)*.25-.08);}topGeo.computeVertexNormals();const surface=mesh(topGeo,mat(0x514054),world,0,0,-27);
const lavaMat=new THREE.MeshBasicMaterial({color:0xff805c});for(let i=0;i<14;i++){const pts=[];let x=-50+rand()*100,z=-72+rand()*90;for(let j=0;j<7;j++)pts.push(new V(x+(rand()-.5)*5,.1,z+j*2));const curve=new THREE.CatmullRomCurve3(pts);mesh(new THREE.TubeGeometry(curve,20,.11,5,false),lavaMat,world);}
for(let i=0;i<130;i++){let x=(rand()-.5)*111,z=-78+rand()*108;if(Math.abs(x)<8&&z<23)continue;const s=.5+rand()*2.7;const rock=sphere(world,s,[0x665574,0x77627b,0x393c58][i%3],x,s*.45,z,0,0);rock.scale.set(1,.6+rand(),.8);rock.rotation.set(rand(),rand()*3,rand());}
for(let i=0;i<30;i++){const x=(rand()>.5?1:-1)*(12+rand()*36),z=-70+rand()*94;const group=new THREE.Group();world.add(group);group.position.set(x,0,z);for(let j=0;j<3;j++){const crystal=cyl(group,0,.55,2+rand()*3,0x81b4d9,j*.6,.9,rand(),5);crystal.rotation.z=(j-1)*.3;crystal.material=mat(0x87bfd1,0x20495e);}}
for(let i=0;i<8;i++){const angle=i/8*Math.PI*2;const rock=sphere(world,8+rand()*6,0x3b3656,Math.cos(angle)*65,-2,Math.sin(angle)*65-27,0,0);rock.scale.y=2;}
const station=new THREE.Group();scene.add(station);station.position.set(0,0,66);cyl(station,19,19,2,0x27324b,0,-1,0,12);cyl(station,17,18,.25,0x5b6e86,0,.02,0,12);ring(station,16,.08,0x7ceae5,0,.2,0);for(let i=0;i<8;i++){const a=i/8*6.28;box(station,1,.15,4,0xbce5df,Math.cos(a)*13,.22,Math.sin(a)*13).rotation.y=-a;}for(let i=0;i<4;i++){cyl(station,.2,.2,4,0x384965,(i<2?-1:1)*14,2,i%2?-9:9);sphere(station,.28,0x91f3fa,(i<2?-1:1)*14,4,i%2?-9:9,0x4fc4cc);}
const landingRing=ring(world,5,.1,0x80dacd,0,.16,19);box(world,4,.1,.25,0xe0e4c8,0,.2,19);box(world,.25,.1,4,0xe0e4c8,0,.2,19);
function ship(big=false){const g=new THREE.Group();const body=sphere(g,1,0xd3e3eb,0,1.5,0,0,1);body.scale.set(2,1,4);box(g,2,1,4,0xb8c6da,0,1.2,0);const canopy=sphere(g,1,0x1d4f70,0,2,-1.4,0x082432,2);canopy.scale.set(1.2,.7,1.5);for(const s of[-1,1]){const wing=box(g,3,.23,2.6,0x6482a1,s*2.4,1,1);wing.rotation.z=s*.12;box(g,.55,.5,3.6,0x26394c,s*2,1,1.8);sphere(g,.48,0x8df9fd,s*2,1,3.6,0x52dafa);const tail=box(g,.15,1.5,1.2,0xf6b56c,s*1.1,2.2,2.1);tail.rotation.z=s*.25;box(g,.18,1,.18,0x26344a,s*1.2,.1,.7);}box(g,.3,.1,2,0xffca83,0,2.3,.5);g.userData.big=big;if(big)g.scale.set(3,2.5,3.5);return g;}
const mothership=ship(true);scene.add(mothership);mothership.position.set(-15,13,64);const shuttle=ship();scene.add(shuttle);shuttle.position.set(0,.5,57);
function astronaut(){const g=new THREE.Group();const body=box(g,.9,1.1,.6,0xede9df,0,1.3,0);box(g,.6,.35,.1,0xf9b268,0,1.55,-.36);box(g,.55,.7,.35,0x718aa4,0,1.4,.43);const head=sphere(g,.62,0xf2eee4,0,2.2,0,0,2);const visor=sphere(g,.51,0x142c4b,0,2.23,-.24,0x0a2339,2);visor.scale.set(1,.65,.7);box(g,.3,.1,.08,0x8af8ff,-.14,2.32,-.59,0x54b6bf);const legs=[];for(const s of[-1,1]){const leg=new THREE.Group();leg.position.set(s*.25,.93,0);g.add(leg);box(leg,.35,.8,.4,0xaec5d9,0,-.4,0);box(leg,.39,.24,.64,0x364863,0,-.78,-.09);legs.push(leg);const arm=box(g,.3,.8,.32,0xd3dfe4,s*.65,1.3,-.05);arm.rotation.x=-.5;}const gun=box(g,.28,.28,1.05,0x263d5c,.65,1.3,-.7);box(g,.15,.15,.12,0x72e6f5,.65,1.3,-1.26,0x63dcff);g.userData.legs=legs;return g;}
const player=astronaut();scene.add(player);player.position.set(0,0,69);player.visible=false;
function monster(x,z,boss=false){const g=new THREE.Group();scene.add(g);g.position.set(x,0,z);const size=boss?3.2:1;const torso=sphere(g,1.05,boss?0x4b3049:0xac635b,0,1.15,0,0,1);torso.scale.set(1,.95,.8);sphere(g,.65,0x59394d,0,2,0,0,0);for(const s of[-1,1]){sphere(g,.29,0xffd98d,s*.27,2.08,-.54,0xff732e,1);const horn=cyl(g,0,.22,.95,0xe2b188,s*.63,2.5,0,5);horn.rotation.z=-s*.4;const leg=box(g,.52,.8,.65,0x51394f,s*.55,.45,0);const arm=sphere(g,.45,0x8a5055,s*1.04,1.03,0,0,0);arm.scale.set(.65,1.4,1);}box(g,.5,.22,.2,0xffac5c,0,1.7,-.67,0xcc3a13);if(boss){for(let i=0;i<5;i++){const sp=cyl(g,0,.27,1.1,0xe7ad7e,0,1.3+i*.2,.55,5);sp.rotation.x=.8;}sphere(g,.4,0xffb35c,0,1.12,-.75,0xe85123);}g.scale.setScalar(size);const bar=new THREE.Group();g.add(bar);bar.position.y=3;const back=box(bar,1.8,.12,.03,0x231d31);const fill=box(bar,1.75,.09,.04,0xffb17a,0,0,-.025);return {g,boss,hp:boss?36:4,max:boss?36:4,timer:boss?3:1.2+rand()*2,base:new V(x,0,z),fill,flash:0,dead:false};}
let enemies=[];let projectiles=[],shots=[],effects=[];let treasure=new THREE.Group();scene.add(treasure);treasure.position.set(0,0,-76);cyl(treasure,2.8,3.4,.7,0x2d3f59,0,.3,0,8);ring(treasure,2.8,.08,0xffcb6e,0,.8,0);const core=sphere(treasure,.9,0xffdfa1,0,2.4,0,0xffb842,0);const coreRing=ring(treasure,1.5,.04,0xffd69f,0,2.4,0);coreRing.rotation.x=.8;const beam=mesh(new THREE.CylinderGeometry(.3,.3,25,16),new THREE.MeshBasicMaterial({color:0xffd68a,transparent:true,opacity:.1,depthWrite:false}),treasure,0,13,0);treasure.visible=false;
const keys=new Set();let phase='title',phaseTime=0,hp=100,timeLeft=360,kills=0,yaw=0,vy=0,shootCD=0,iceCD=0,invuln=0,paused=false,fireHeld=false,stickX=0,stickY=0,mute=false,audio=null,last=performance.now(),globalTime=0,toastTime=0,shake=0,runDistance=0;
function sound(freq=440,duration=.1,type='sine',volume=.08){if(mute||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.4,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function initAudio(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function toast(t,d=3){setGameText($('toast'),t);$('toast').classList.add('show');toastTime=d;}
function setMission(n,title){setGameText($('phase'),n);setGameText($('objective'),title);}
function disposeObject(obj){scene.remove(obj);obj.traverse(x=>{if(x.isMesh)x.geometry.dispose();});}
function burst(pos,color,count=16,scale=1){for(let i=0;i<count;i++){const m=sphere(scene,.08+rand()*.1,color,pos.x,pos.y,pos.z,color,0);effects.push({m,v:new V((rand()-.5)*8,(rand()-.2)*7,(rand()-.5)*8).multiplyScalar(scale),life:.5+rand()*.5,max:1});}}
function reset(){for(const e of enemies)disposeObject(e.g);for(const p of [...projectiles,...shots,...effects])disposeObject(p.m);enemies=[monster(-7,-9),monster(8,-18),monster(-11,-31),monster(9,-41),monster(-3,-47),monster(0,-62,true)];projectiles=[];shots=[];effects=[];hp=100;timeLeft=360;kills=0;iceCD=0;iceShield=0;invuln=0;shootCD=0;vy=0;yaw=0;runDistance=0;paused=false;phaseTime=0;setGameText($('pause'),'Ⅱ');releaseJoy();keys.clear();fireHeld=false;stickX=stickY=0;player.position.set(0,0,69);player.rotation.set(0,0,0);player.visible=false;mothership.position.set(-15,13,125);mothership.visible=true;shuttle.position.set(0,.5,57);shuttle.rotation.set(0,0,0);treasure.visible=false;earth.visible=true;earth.scale.setScalar(1);$('modal').classList.add('hidden');$('bossHud').classList.add('hidden');$('interact').classList.add('hidden');$('target').classList.add('hidden');$('compass').classList.add('hidden');$('hurt').style.opacity=0;}
function start(){initAudio();reset();phase='arrival';$('intro').classList.add('hidden');$('hud').classList.remove('hidden');$('bottom').classList.add('hidden');$('joystick').classList.add('hidden');setMission('01 / 曙光号','正在前往安全区');toast('Kehan，地球需要你！',4);sound(330,.5,'sine');}
function arrive(){phase='safe';phaseTime=0;player.visible=true;player.position.set(0,0,69);mothership.position.set(-15,13,80);showControls();setMission('02 / 安全区','靠近小飞船，按 E 登船');toast('安全抵达！沿发光平台走向小飞船。',4);}
function showControls(){$('bottom').classList.remove('hidden');if(matchMedia('(pointer:coarse)').matches)$('joystick').classList.remove('hidden');}
function board(){if(phase!=='safe'||player.position.distanceTo(new V(0,0,57))>9)return;phase='flight';phaseTime=0;player.visible=false;$('interact').classList.add('hidden');$('bottom').classList.add('hidden');$('joystick').classList.add('hidden');setMission('03 / 小飞船','穿越陨石带 · 登陆熔焰星');toast('抓紧！目的地：熔焰星。',4);sound(100,1,'sawtooth',.05);}
function land(){phase='combat';phaseTime=0;player.visible=true;player.position.set(0,0,15);shuttle.position.set(0,.7,23);showControls();$('target').classList.remove('hidden');$('compass').classList.remove('hidden');setMission('04 / 熔焰星','击败守卫，找到熔焰巨兽');toast('按住 J 射击 · F 冻住火球 · 空格跳跃',5);}
function getTarget(){const fwd=new V(-Math.sin(yaw),0,-Math.cos(yaw));let target=null,best=Infinity;for(const e of enemies){if(e.dead)continue;const d=e.g.position.clone().sub(player.position);const len=d.length();if(len>38||d.normalize().dot(fwd)<.1)continue;const score=len+(1-d.dot(fwd))*10;if(score<best){best=score;target=e;}}return target;}
function fire(){if(phase!=='combat'||shootCD>0||paused)return;shootCD=.19;const target=getTarget();const pos=player.position.clone().add(new V(.5,1.45,-.7).applyAxisAngle(new V(0,1,0),player.rotation.y));let dir=target?target.g.position.clone().add(new V(0,target.boss?3.8:1.25,0)).sub(pos).normalize():new V(-Math.sin(yaw),0,-Math.cos(yaw));const m=box(scene,.13,.13,1.4,0xa5f6ff,pos.x,pos.y,pos.z,0x65deff);m.quaternion.setFromUnitVectors(new V(0,0,1),dir);shots.push({m,v:dir.multiplyScalar(53),life:1.3,prev:pos.clone()});sound(800+rand()*150,.07,'triangle',.035);}
function ice(){if(phase!=='combat'||iceCD>0||paused)return;iceCD=5;const pulse=mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshBasicMaterial({color:0x8aebff,transparent:true,opacity:.26,wireframe:true}),scene,player.position.x,1,player.position.z);effects.push({m:pulse,pulse:true,life:.7,max:.7});let count=0;for(const p of projectiles){if(!p.frozen&&p.m.position.distanceTo(player.position)<29){p.frozen=true;p.life=4.5;p.m.material=mat(0x66dfff,0x118dcc);p.m.children.forEach(c=>{if(c.material)c.material.color.setHex(0x69dfff);});p.m.geometry.dispose();p.m.geometry=new THREE.IcosahedronGeometry(p.radius*1.2,0);count++;}}sound(1300,.6,'sine',.1);toast(count?'❄ 冻住了 '+count+' 个火球！':'❄ 冰霜护盾展开：靠近的火球会被冻结',2);iceShield=1.5;}
let iceShield=0;
function jump(){if((phase==='combat'||phase==='safe')&&player.position.y<.05&&!paused){vy=9;sound(340,.16,'sine',.04);}}
function enemyFire(e){const from=e.g.position.clone().add(new V(0,e.boss?4.2:1.7,e.boss?-2:-.7));const aim=player.position.clone().add(new V(0,1,0));const dir=aim.sub(from).normalize();const radius=e.boss?1.8:.48;const m=sphere(scene,radius,0xffad45,from.x,from.y,from.z,0xff581b,1);const shell=mesh(new THREE.IcosahedronGeometry(radius*1.3,1),new THREE.MeshBasicMaterial({color:0xff6534,transparent:true,opacity:.22}),m);projectiles.push({m,v:dir.multiplyScalar(e.boss?11:9),radius,boss:e.boss,frozen:false,life:9});if(e.boss){shake=.16;sound(75,.5,'sawtooth',.09);toast('超大火球！按 F 冰冻，或横向躲开！',2.3);}else sound(140,.13,'sine',.025);}
function damage(n){if(invuln>0||phase!=='combat')return;hp=Math.max(0,hp-n);invuln=1.2;shake=.4;$('hurt').style.opacity=.7;sound(90,.22,'sawtooth',.08);if(hp<=0)end(false,'你被熔焰怪打倒了。地球失去了星核的保护。<br>再试一次：看到火球就释放冰魔法！');}
function hitEnemy(e){e.hp--;e.flash=.1;burst(e.g.position.clone().add(new V(0,e.boss?3:1,0)),0xffd895,5);e.fill.scale.x=Math.max(0,e.hp/e.max);sound(e.boss?210:330,.08,'triangle',.03);if(e.hp<=0){e.dead=true;e.g.visible=false;kills++;burst(e.g.position.clone().add(new V(0,e.boss?3:1,0)),e.boss?0xffb867:0xf89b80,e.boss?55:20,e.boss?1.7:1);if(e.boss){treasure.visible=true;$('bossHud').classList.add('hidden');setMission('05 / 星核已解锁','走到金色星核旁，拯救地球！');toast('巨兽倒下了！快去拿回金色星核！',5);hp=Math.min(100,hp+30);sound(660,.5);}else{hp=Math.min(100,hp+7);toast('守卫击败！恢复 7 点护盾',1.4);}}}
function end(win,text){phase=win?'won':'lost';paused=false;keys.clear();fireHeld=false;stickX=stickY=0;$('interact').classList.add('hidden');$('bottom').classList.add('hidden');$('joystick').classList.add('hidden');$('target').classList.add('hidden');$('bossHud').classList.add('hidden');$('modal').classList.remove('hidden');$('resume').classList.add('hidden');setGameText($('resultIcon'),win?'✦':'☄');setGameText($('resultKicker'),win?'EARTH IS SAFE':'MISSION FAILED');setGameText($('resultTitle'),win?'Kehan，地球得救了！':'地球失去了保护');$('resultText').innerHTML=text;setGameText($('restart'),'再挑战一次 ↗');if(win){burst(player.position.clone().add(new V(0,3,0)),0x9df4ff,75,2);sound(880,1);}else{earth.visible=false;burst(earth.position,0xff854d,100,12);sound(65,1,'sawtooth',.08);}}
function pause(){if(['title','won','lost'].includes(phase))return;paused=!paused;keys.clear();fireHeld=false;stickX=stickY=0;setGameText($('pause'),paused?'▶':'Ⅱ');$('modal').classList.toggle('hidden',!paused);if(paused){$('resume').classList.remove('hidden');setGameText($('resultIcon'),'Ⅱ');setGameText($('resultKicker'),'MISSION PAUSED');setGameText($('resultTitle'),'冒险暂停');setGameText($('resultText'),'休息一下，地球的倒计时也暂停了。');setGameText($('restart'),'重新挑战');}}
function update(dt){globalTime+=dt;core.rotation.y+=dt;core.position.y=2.4+Math.sin(globalTime*2)*.25;coreRing.rotation.z+=dt*.4;earth.rotation.y+=dt*.025;moonRing.rotation.z+=dt*.003;if(phase==='title'){mothership.position.set(13,13+Math.sin(globalTime*.7),15);mothership.rotation.y=-.4;shuttle.position.set(12,1,4);camera.position.set(52,32,72);camera.lookAt(0,12,-15);return;}
if(paused)return;phaseTime+=dt;toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');shootCD=Math.max(0,shootCD-dt);iceCD=Math.max(0,iceCD-dt);invuln=Math.max(0,invuln-dt);iceShield=Math.max(0,iceShield-dt);shake=Math.max(0,shake-dt);$('hurt').style.opacity=Math.max(0,invuln-.65)*.75;
if(phase==='arrival'){const t=clamp(phaseTime/5,0,1);mothership.rotation.y=0;mothership.position.set(-15,13+Math.sin(t*3),125-45*t);camera.position.set(18,23,113-32*t);camera.lookAt(mothership.position.clone().add(new V(0,0,-8)));if(t===1)arrive();}
if(phase==='flight'){const t=clamp(phaseTime/4,0,1);shuttle.position.set(Math.sin(t*Math.PI)*3,.5+Math.sin(t*Math.PI)*14,57-34*t);shuttle.rotation.z=Math.sin(t*6)*.1;camera.position.copy(shuttle.position).add(new V(9,6,15));camera.lookAt(shuttle.position.clone().add(new V(0,1,-8)));if(t===1)land();}
if(phase==='safe'||phase==='combat'){
if(keys.has('ArrowLeft')||keys.has('KeyQ'))yaw+=dt*1.8;if(keys.has('ArrowRight')||keys.has('KeyE')&&phase==='combat')yaw-=dt*1.8;
let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+stickX,mz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+stickY;const move=new V(mx,0,mz);if(move.length()>1)move.normalize();move.applyAxisAngle(new V(0,1,0),yaw);const speed=keys.has('ShiftLeft')||Math.hypot(stickX,stickY)>.85?10:7.5;player.position.addScaledVector(move,speed*dt);runDistance+=move.length()*dt*speed;
if(phase==='safe'){const off=player.position.clone().sub(new V(0,player.position.y,66));if(off.length()>16)player.position.copy(new V(0,player.position.y,66).add(off.setLength(16)));const near=player.position.distanceTo(new V(0,0,57))<9;$('interact').classList.toggle('hidden',!near);}else{player.position.x=clamp(player.position.x,-48,48);player.position.z=clamp(player.position.z,-79,26);}
vy-=23*dt;player.position.y=Math.max(0,player.position.y+vy*dt);if(player.position.y===0)vy=0;player.rotation.y=yaw;const legSwing=move.length()>.1?Math.sin(runDistance*1.6)*.65:0;player.userData.legs[0].rotation.x=legSwing;player.userData.legs[1].rotation.x=-legSwing;player.visible=!(invuln>0&&Math.floor(invuln*12)%2===0);
const camPos=player.position.clone().add(new V(Math.sin(yaw)*10,6.7,Math.cos(yaw)*10));camera.position.lerp(camPos,1-Math.exp(-dt*7));const look=player.position.clone().add(new V(-Math.sin(yaw)*5,2.1,-Math.cos(yaw)*5));camera.lookAt(look);if(shake>0)camera.position.x+=(rand()-.5)*shake;if(fireHeld||keys.has('KeyJ'))fire();
}
if(phase==='combat'){
timeLeft=Math.max(0,timeLeft-dt);if(timeLeft<=0){end(false,'没能及时拿到星核，地球被熔焰风暴吞没了。<br>再挑战一次，把星核带回家！');return;}
for(const e of enemies){if(e.dead)continue;const dist=e.g.position.distanceTo(player.position);e.g.rotation.y=Math.atan2(player.position.x-e.g.position.x,player.position.z-e.g.position.z)+Math.PI;e.g.position.y=Math.sin(globalTime*(e.boss?2:4)+e.base.x)*.09;e.flash=Math.max(0,e.flash-dt);e.g.scale.setScalar((e.boss?3.2:1)*(e.flash>0?1.07:1));if(dist<(e.boss?39:31)){e.timer-=dt;if(!e.boss&&dist>10){const dir=player.position.clone().sub(e.g.position);dir.y=0;e.g.position.addScaledVector(dir.normalize(),dt*1.1);}if(e.boss){$('bossHud').classList.remove('hidden');setGameText($('bossHint'),e.timer<.85?'⚠ 正在蓄力！准备冰冻':'超大火球 · 冰冻可以保护你');$('bossBar').style.width=e.hp/e.max*100+'%';if(e.timer<.85)e.g.scale.setScalar(3.2+Math.sin(globalTime*19)*.06);setMission('04 / BOSS 战','击败熔焰巨兽 · F 冰冻超大火球');}if(e.timer<=0){enemyFire(e);e.timer=e.boss?3.7:2.6+rand()*1.4;}if(dist<(e.boss?4.5:1.8))damage(e.boss?18:9);}}
for(let i=shots.length-1;i>=0;i--){const p=shots[i];p.prev.copy(p.m.position);p.m.position.addScaledVector(p.v,dt);p.life-=dt;const seg=new THREE.Line3(p.prev,p.m.position),point=new V();let hit=false;for(const e of enemies){if(e.dead)continue;const center=e.g.position.clone().add(new V(0,e.boss?3.8:1.3,0));seg.closestPointToPoint(center,true,point);if(point.distanceTo(center)<(e.boss?3.3:1.25)){hitEnemy(e);hit=true;break;}}if(hit||p.life<=0){disposeObject(p.m);shots.splice(i,1);}}
for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;if(!p.frozen){if(iceShield>0&&p.m.position.distanceTo(player.position)<29){p.frozen=true;p.life=4.5;p.m.material=mat(0x66dfff,0x118dcc);p.m.children.forEach(c=>{if(c.material)c.material.color.setHex(0x69dfff);});p.m.geometry.dispose();p.m.geometry=new THREE.IcosahedronGeometry(p.radius*1.2,0);}else p.m.position.addScaledVector(p.v,dt);}p.m.rotation.y+=dt*(p.frozen?.5:3);if(!p.frozen&&p.m.position.distanceTo(player.position.clone().add(new V(0,1.1,0)))<p.radius+.65){damage(p.boss?24:11);p.life=0;burst(p.m.position,0xffb768,12);}if(p.m.position.y<-2)p.life=0;if(p.life<=0){if(p.frozen)burst(p.m.position,0x96e9ff,10);disposeObject(p.m);projectiles.splice(i,1);}}
const boss=enemies.find(e=>e.boss);const dist=Math.round(player.position.distanceTo(treasure.position));const bearing=Math.atan2(treasure.position.x-player.position.x,player.position.z-treasure.position.z)+yaw;const marker=Math.cos(bearing)>.65?'↑':Math.cos(bearing)<-.65?'↓':Math.sin(bearing)>0?'→':'←';setGameText($('distance'),marker+(boss.dead?' 星核已解锁 · ':' 星核信号 · ')+dist+' m');if(boss.dead&&dist<3.5)end(true,'你击败了熔焰巨兽，找回了生命星核。<br>蓝色地球再次闪耀。你是大家的太空英雄！');
}
for(let i=effects.length-1;i>=0;i--){const p=effects[i];p.life-=dt;if(p.pulse){p.m.scale.setScalar(1+(1-p.life/p.max)*29);p.m.material.opacity=Math.max(0,p.life/p.max*.3);}else{p.v.y-=dt*9;p.m.position.addScaledVector(p.v,dt);p.m.scale.setScalar(Math.max(0,p.life));}if(p.life<=0){if(p.pulse)p.m.material.dispose();disposeObject(p.m);effects.splice(i,1);}}
setGameText($('healthText'),hp);$('healthBar').style.width=hp+'%';setGameText($('timer'),String(Math.floor(timeLeft/60)).padStart(2,'0')+':'+String(Math.floor(timeLeft%60)).padStart(2,'0'));$('timer').style.color=timeLeft<60?'#ff9a85':'';setGameText($('iceLabel'),iceCD>0?Math.ceil(iceCD)+' 秒':'冰冻魔法');$('iceFill').style.height=iceCD/5*100+'%';
}
$('start').onclick=start;$('restart').onclick=start;$('resume').onclick=pause;$('pause').onclick=pause;$('sound').onclick=()=>{mute=!mute;setGameText($('sound'),mute?'♪̸':'♫');};$('interact').onclick=board;$('ice').onpointerdown=e=>{e.preventDefault();ice();};$('jump').onpointerdown=e=>{e.preventDefault();jump();};$('fire').onpointerdown=e=>{e.preventDefault();fireHeld=true;e.currentTarget.setPointerCapture(e.pointerId);};$('fire').onpointerup=()=>fireHeld=false;$('fire').onpointercancel=()=>fireHeld=false;
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;keys.add(e.code);if(e.code==='Space')jump();if(e.code==='KeyF'||e.code==='KeyK')ice();if(e.code==='KeyE')board();if(e.code==='Escape'||e.code==='KeyP')pause();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();fireHeld=false;stickX=stickY=0;releaseJoy();joyId=null;drag=null;if(!paused&&!['title','won','lost'].includes(phase))pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&!['title','won','lost'].includes(phase))pause();});
let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{if(phase==='combat'||phase==='safe'){drag={x:e.clientX,id:e.pointerId};renderer.domElement.setPointerCapture(e.pointerId);if(e.pointerType==='mouse'&&e.button===0)fireHeld=true;}});renderer.domElement.addEventListener('pointermove',e=>{if(drag&&drag.id===e.pointerId){yaw-=(e.clientX-drag.x)*.005;drag.x=e.clientX;}});renderer.domElement.addEventListener('pointerup',()=>{drag=null;fireHeld=false;});renderer.domElement.addEventListener('pointercancel',()=>{drag=null;fireHeld=false;});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
let joyId=null;function joy(e){const r=$('joystick').getBoundingClientRect();let x=(e.clientX-r.x-r.width/2)/(r.width*.37),y=(e.clientY-r.y-r.height/2)/(r.height*.37);const len=Math.max(1,Math.hypot(x,y));stickX=x/len;stickY=y/len;$('stick').style.transform=`translate(${stickX*32}px,${stickY*32}px)`;}
$('joystick').onpointerdown=e=>{e.preventDefault();joyId=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);joy(e);};$('joystick').onpointermove=e=>{if(joyId===e.pointerId)joy(e);};function releaseJoy(){joyId=null;stickX=stickY=0;$('stick').style.transform='';}$('joystick').onpointerup=releaseJoy;$('joystick').onpointercancel=releaseJoy;
addEventListener('resize',()=>{const w=visualViewport?.width||innerWidth,h=visualViewport?.height||innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);});
// Read-only state helps verify the actual running game. Scenario controls exist only in explicit QA mode.
window.kehan={setPaused:value=>{if(paused!==value&&!['title','won','lost'].includes(phase))pause();},snapshot:()=>({phase,paused,hp,timeLeft,kills,iceCD,player:{x:player.position.x,y:player.position.y,z:player.position.z},enemies:enemies.map(e=>({boss:e.boss,hp:e.hp,dead:e.dead,x:e.g.position.x,z:e.g.position.z})),fireballs:projectiles.map(p=>({frozen:p.frozen,boss:p.boss,x:p.m.position.x,y:p.m.position.y,z:p.m.position.z})),treasure:treasure.visible})};
if(new URLSearchParams(location.search).has('qa'))window.kehan.qa={land:()=>{start();land();},move:(x,z)=>{player.position.set(x,0,z);},fireball:(boss=false)=>{const e=enemies.find(e=>e.boss===boss);enemyFire(e);const p=projectiles.at(-1);p.m.position.copy(player.position).add(new V(0,1.2,-7));p.v.set(0,0,9);},setHp:n=>hp=n,setTime:n=>timeLeft=n,damage,kill:()=>{for(const e of enemies){while(!e.dead)hitEnemy(e);}},boss:()=>{player.position.set(0,0,-42);},snapshot:window.kehan.snapshot};
$('boot').classList.add('hidden');function frame(now){let remaining=Math.min(Math.max((now-last)/1000,0),.25);last=now;while(remaining>0.000001){const dt=Math.min(remaining,1/60);update(dt);remaining-=dt;}renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
